export default {
    translation: {
      Login: {
        Title: "Pro pokračování je vyžadování přihlášení.",
        Username_or_Email: "Uživatelské jméno nebo Email",
        Password: "Heslo",
        Login_Button: "Přihlásit se",
        Forgot_Password: "Zapoměl jsi heslo?",
        Username_or_Email_Desc: "Je nutné zadat uživatelské jméno nebo e-mail.",
        Account_Password_Desc: "Zadejte heslo svého účtu..",
        Account_Incorrect: "Nebyl nalezen žádný účet odpovídající těmto přihlašovacím údajům.",
        Many_Attempts: "Proběhlo příliš mnoho pokusů o přihlášení. Prosím zkuste to znovu později.",
        Recaptcha_Error: "Nepodařilo se ověřit data reCAPTCHA.",
        Request_Failed: "Požadavek se nezdařil se stavovým kódem 404",
        CSRF_Token: "Neshoda tokenu CSRF."
      },
      Reset_Password: {
        Password_Reset: "Požádat o resetování hesla",
        Email: "Email",
        New_Password_Required: "Je vyžadováno nové heslo.",
        Password_Characters_Min: "Vaše nové heslo by mělo mít alespoň 8 znaků.",
        Password_Not_Match: "Vaše nové heslo se neshoduje.",
        Account_Email: "Zadejte e-mailovou adresu svého účtu, abyste obdrželi pokyny k obnovení hesla.",
        Valid_Email: "Chcete-li pokračovat, musíte zadat platnou e-mailovou adresu.",
        Send_Email: "Poslat Email",
        Return_to_Login: "Zpět k přihlášení",
        Reset_Password: "Obnovit heslo",
        New_Password: "Nové heslo",
        New_Password_Desc: "Hesla musí mít alespoň 8 znaků.",
        Confirm_New_Password: "Potvrdit nové heslo",
        Send_Email_Link: "Poslali jsme Vám e-mailem odkaz pro obnovení hesla!"
      },
      Two_Factor_Auth: {
        Device_Checkpoint: "Kontrolní bod zařízení",
        Recovery_Code: "Kód pro obnovení",
        Authentication_Code: "Authentication Code",
        Enter_Two_Factor_Desc_1: "Zadejte dvoufaktorový token vygenerovaný vaším zařízením.",
        Enter_Two_Factor_Desc_2: "Abyste mohli pokračovat, zadejte jeden z obnovovacích kódů vygenerovaných při nastavování dvoufaktorového ověřování na tomto účtu.",
        Lost_Device: "Ztratil jsem zařízení",
        Have_Device: "Mám své zařízení",
        Continue: "pokračovat"
      },
      Account_Overview: {
        Two_Factor_Activate_Desc_1: "Abyste mohli pokračovat, musíte zadat ověřovací kód.",
        Two_Factor_Activate_Desc_2: "Ve vašem účtu je aktuálně povolena dvoufaktorová autentizace.",
        Two_Factor_Activate_Desc_3: "Authenticator kód musí mít 6 číslic.",
        Two_Factor_Active_Title: "Dvoufaktorové ověřování povoleno",
        Two_Factor_Active_Desc_1: "Ve vašem účtu byla povolena dvoufaktorová autentizace. Pokud ztratíte přístup ke svému autentizačnímu zařízení, budete muset pro přístup k účtu použít jeden z níže zobrazených kódů.",
        Two_Factor_Active_Desc_2: "Tyto kódy se již nebudou zobrazovat.",
        Two_Factor_Active_Desc_3: "Vezměte si je prosím na vědomí a uložte je do zabezpečeného úložiště, jako je správce hesel.",
        Two_Factor_Active_Button: "Zavřít",
        Two_Factor_Disabled_Desc: "V současné době nemáte na svém účtu povoleno dvoufaktorové ověřování. Klikněte na tlačítko níže a začněte jej konfigurovat.",
        Two_Factor_Disable_Desc_1: "Abyste mohli pokračovat, musíte zadat své aktuální heslo.",
        Two_Factor_Disable_Desc_2: "Abyste zakázali dvoufaktorovou autentizaci, budete muset zadat heslo k účtu.",
        Two_Factor_Disable_Title: "Aktuální heslo",
        Two_Factor_Disable_Button: "Zakázat dvoufaktorové",
        Two_Factor_Setup_Desc_1: "Po naskenování QR obrázku zadejte kód ze svého ověřovacího zařízení.",
        Two_Factor_Setup_Desc_2: "Alternativně zadejte následující token do své autentizační aplikace:",
        Two_Factor_Setup_Button: "Nastavení",
        Two_Factor_Incorrect_Password: "Zadané heslo nebylo platné.",
        Button_Disable: "Zakázat",
        Button_Enable: "Povolit",
        Create_Api_Desc_Title: "Popis",
        Create_Api_Desc: "Popis tohoto klíče API.",
        Create_Api_Ips_Title: "Povolené adresy IP",
        Create_Api_Ips_Desc: "Nechte prázdné, aby jakákoli IP adresa mohla používat tento klíč API, jinak uveďte každou IP adresu na nový řádek.",
        Create_Api_Button: "Vytvořit",
        Update_Email_Desc_1: "Musíte zadat své aktuální heslo k účtu.",
        Update_Email_Required: "E-mail je povinné pole",
        Update_Email_Success_Title: "Úspěch",
        Update_Email_Success: "Váš primární e-mail byl aktualizován.",
        Update_Email_Error_Title: "Chyba",
        Update_Email_Button: "Aktualizovat e-mail",
        Update_Password_Title: "Nové heslo",
        Update_Password_Desc_1: "Musíte zadat své aktuální heslo.",
        Update_Password_Desc_2: "Potvrzení hesla neodpovídá heslu, které jste zadali.",
        Update_Password_Desc_3: "Vaše nové heslo by mělo mít alespoň 8 znaků a mělo by být jedinečné pro tento web.",
        Update_Password_Required: "Heslo je povinné pole",
        Update_Password_Button: "Aktualizovat heslo",
        Update_Password_Error: "Zadané heslo bylo pro tento účet neplatné.",
        Update_Password_Min: "Heslo musí mít alespoň 8 znaků",
        Confirm_Password: "Potvrdit heslo",
        Account_Page_Title: "Přehled účtu",
        Account_Two_Factor_Required_Title: "2-Factor Required",
        Account_Two_Factor_Required_Desc: "Váš účet musí mít povolenou dvoufaktorovou autentizaci, aby mohl pokračovat.",
        Account_Update_Email_Title: "Aktualizovat e-mailovou adresu",
        Account_Setup_Two_Factor_Title: "Konfigurovat dvoufaktor",
        Api_Page_Title: "Account API",
        Api_Create_Title: "Vytvořit klíč API",
        Api_List_Title: "Klíče API",
        Api_List_Loading: "Načítání...",
        Api_List_Empty: "Pro tento účet neexistují žádné klíče API.",
        Api_List_Used_1: "Naposledy použito: ",
        Api_List_Used_2: "Nikdy",
        Api_Delete_Title: "Potvrdit smazání klíče",
        Api_Delete_Button: "Ano, odstranit klíč",
        Api_Delete_Desc: "Opravdu chcete smazat tento klíč API? Všechny požadavky, které jej používají, budou okamžitě zrušeny a selžou.",
        Api_Setup_Title: "Váš klíč API",
        Api_Setup_Desc: "Klíč API, který jste požadovali, je zobrazen níže. Uložte jej prosím na bezpečné místo, nebude se znovu zobrazovat.",
        Api_Min_Characters: "Popis musí mít alespoň 4 znaky",
        Api_Setup_Button: "Zavřít",
        Api_Ip_Incorrect_1: "IP adresa 1 musí být platná IP adresa.",
        Api_Ip_Incorrect_2: "IP adresa 2 musí být platná IP adresa.",
        Api_Ip_Incorrect_3: "IP adresa 3 musí být platná IP adresa."
      },
      Search: {
        Search_Title: "Hledaný výraz",
        Search_Desc_1: "Začněte hledat alespoň tři znaky.",
        Search_Desc_2: "Zadejte název serveru, uuid nebo alokaci pro zahájení vyhledávání."
      },
      Dashboard: {
        Dash_Page_Title: "Panel",
        Dash_Show_Server_1: "Zobrazují se servery ostatních",
        Dash_Show_Server_2: "Zobrazují se vaše servery",
        Dash_Show_Server_3: "Neexistují žádné další servery k zobrazení.",
        Dash_Show_Server_4: "K vašemu účtu nejsou přidruženy žádné servery."
      },
      Server_Row: {
        Server_Unlimited: "Neomezeno",
        Server_Suspended: "Pozastaveno",
        Server_Connect_Error: "Chyba připojení",
        Server_Transferring: "Přenos",
        Server_Installing: "Instalace",
        Server_Restoring_Backup: "Obnovuji zálohu",
        Server_Unavailable: "Není k dispozici",
        Server_Of: "z"
      },
      Elements: {
        Elements_Cancel_Button: "Zrušit",
        Elements_Copy_Text: "Zkopírováno do schránky.",
        Elements_Error: "Aplikace zaznamenala chybu při vykreslování tohoto zobrazení. Zkuste obnovit stránku."
      },
      Server: {
        Server_Page_Title: "Konzole",
        Server_Transfer_Console: "Přenos se nezdařil.",
        Server_Archived_Console: "Server byl úspěšně archivován, pokus o připojení k cílovému uzlu..",
        Server_Send_Command: "Zadejte příkaz...",
        Server_State_Console: "Server označen jako ",
        Server_State_Starting: "spouštění",
        Server_State_Offline: "offline",
        Server_State_Stopping: "zastavení",
        Server_State_Running: "běží",
        Server_State_Connect: "Připojování...",
        Server_State_Install: "Tento server právě běží proces instalace a většina akcí není k dispozici.",
        Server_State_Transfer: "Tento server je aktuálně přenášen do jiného uzlu a všechny akce jsou nedostupné.",
        Server_Button_Start: "Start",
        Server_Button_Restart: "Restartovat",
        Server_Button_Kill: "Zabít",
        Server_Button_Stop: "Stop",
        Server_Memory_Graph_Title: "Využití paměti",
        Server_Cpu_Graph_Title: "Využití CPU",
        Server_Graph_Desc: "Server je offline.",
        Server_Websocket_Error: "Došlo k chybě při ověřování pověření poskytnutých pro websocket. Obnovte prosím stránku.",
        Server_Connect_Server: "Máme nějaké potíže s připojením k vašemu serveru, čekejte prosím..."
      },
      Server_Backup: {
        Backup_Page_Title: "Zálohy",
        Backup_Empty_1: "Zdá se, že nám došly zálohy, zkuste se vrátit o stránku.",
        Backup_Empty_2: "Zdá se, že pro tento server nejsou aktuálně uloženy žádné zálohy.",
        Backup_Forbidden: "Pro tento server nelze vytvořit zálohy, protože limit zálohování je nastaven na 0.",
        Backup_Information: "pro tento server byly vytvořeny zálohy.",
        Backup_Create_Title_1: "Vytvořit zálohu serveru",
        Backup_Create_Title_2: "Název zálohy",
        Backup_Create_Title_3: "Ignorované soubory a adresáře",
        Backup_Create_Title_4: "Zamčeno",
        Backup_Create_Desc_1: "Pokud je zadán, název, který by měl být použit k odkazování na tuto zálohu.",
        Backup_Create_Desc_2: "Zadejte soubory nebo složky, které chcete při generování této zálohy ignorovat. Ponechte prázdné, chcete-li použít obsah souboru .pteroignore v kořenovém adresáři serveru, pokud je přítomen. Kromě negování pravidla je podporována shoda se zástupnými znaky u souborů a složek přidáním předponou cesty vykřičníkem.",
        Backup_Create_Desc_3: "Zabraňuje smazání této zálohy, dokud nebude explicitně odemčena.",
        Backup_Create_Start_Button: "Spustit zálohování",
        Backup_Create_Button: "Vytvořit zálohu",
        Backup_Created_Title: "Odemknout tuto zálohu?",
        Backup_Created_Desc_1: "Opravdu chcete tuto zálohu odemknout? Nebude již chráněna před automatickým nebo náhodným smazáním.",
        Backup_Created_Button: "Ano, odemknout",
        Backup_Restore_Title: "Obnovit tuto zálohu?",
        Backup_Restore_Desc_1: "Tento server bude zastaven, aby bylo možné obnovit zálohu. Jakmile bude zálohování spuštěno, nebudete moci ovládat stav napájení serveru, přistupovat ke správci souborů ani vytvářet další zálohy, dokud nebude dokončeno.",
        Backup_Restore_Desc_2: "Opravdu chcete pokračovat?",
        Backup_Restore_Desc_3: "Před obnovením této zálohy odstraňte všechny soubory a složky.",
        Backup_Restore_Button: "Obnovit zálohu",
        Backup_Delete_Title: "Smazat tuto zálohu?",
        Backup_Delete_Desc_1: "Opravdu chcete smazat tuto zálohu? Toto je trvalá operace a po smazání zálohu nelze obnovit.",
        Backup_Delete_Button: "Ano, smazat zálohu",
        Backup_SubMenu_Download: "Stáhnout",
        Backup_SubMenu_Restore: "Obnovit",
        Backup_SubMenu_Unlock: "Odemknout",
        Backup_SubMenu_Lock: "Zamknout",
        Backup_SubMenu_Delete: "Smazat"
      },
      Server_Databases: {
        Database_Page_Title: "Databáze",
        Database_Show_Empty: "Zdá se, že nemáte žádné databáze.",
        Database_Show_Forbidden: "Pro tento server nelze vytvořit databáze.",
        Database_Limit_Desc: "databáze byly přiděleny tomuto serveru.",
        Database_Create_Title_1: "Vytvořit novou databázi",
        Database_Create_Title_2: "Název databáze",
        Database_Create_Title_3: "Připojení z",
        Database_Create_Desc_1: "Popisný název instance vaší databáze.",
        Database_Create_Desc_2: "Odkud by měla být povolena připojení. Pro zástupné znaky použijte %.",
        Database_Create_Button_1: "Vytvořit databázi",
        Database_Create_Button_2: "Nová databáze",
        Database_Create_Error_1: "Při zpracování tohoto požadavku došlo k neočekávané chybě, zkuste to prosím znovu.",
        Database_Create_Error_2: "Musí být poskytnut název databáze.",
        Database_Create_Error_3: "Název databáze musí mít alespoň 3 znaky.",
        Database_Create_Error_4: "Název databáze nesmí přesáhnout 48 znaků.",
        Database_Create_Error_5: "Název databáze by měl obsahovat pouze alfanumerické znaky, podtržítka, pomlčky a/nebo tečky.",
        Database_Create_Error_6: "Musí být zadána hodnota připojení.",
        Database_Create_Error_7: "Musí být poskytnuta platná adresa připojení.",
        Database_Delete_Title_1: "Potvrdit smazání databáze",
        Database_Delete_Title_2: "Potvrdit název databáze",
        Database_Delete_Title_3: "Podrobnosti o připojení k databázi",
        Database_Delete_Title_4: "Koncový bod",
        Database_Delete_Title_5: "Připojení z",
        Database_Delete_Title_6: "Uživatelské jméno",
        Database_Delete_Title_7: "Heslo",
        Database_Delete_Title_8: "JDBC spojovací řetězec",
        Database_Rotate_Button: "Otočit heslo",
        Database_Delete_Desc_1: `Smazání databáze je trvalá akce, nelze ji vrátit zpět. Tím trvale smažete databázi "{{database}}" a odstraníte všechna související data.`,
        Database_Create_Desc_2: "Zadejte název databáze pro potvrzení smazání.",
        Database_Delete_Button: "Smazat databázi",
        Database_Delete_Error_1: "Musí být poskytnut název databáze.",
        Database_Delete_Error_2: "Nebyl nalezen žádný hostitel databáze, který splňuje požadavky pro tento server."
      },
      Server_Files: {
        Files_Page_Title: "Správce souborů",
        Files_Create_Button: "Nový soubor",
        Files_Directory_Empty: "Tento adresář se zdá být prázdný.",
        Files_Show_Files_Max: "Tento adresář je příliš velký pro zobrazení v prohlížeči, což omezuje výstup na prvních 250 souborů.",
        Files_Chmod_Title: "Režim souborů",
        Files_Chmod_Button: "Aktualizovat",
        Files_Delete_File_Or_Directory_Title: "Smazat toto",
        Files_Delete_File_Or_Directory_Button: "Ano, smazat",
        Files_Delete_File_Or_Directory_Desc: "Smazání souborů je trvalá operace, tuto akci nelze vrátit zpět.",
        Files_Delete_File: "Soubor",
        Files_Delete_Directory: "Adresář",
        Files_Delete_Title: "Smazat tyto soubory?",
        Files_Delete_Desc_1: "Opravdu chcete smazat {{selected}} soubor(y)?",
        Files_Delete_Desc_2: "Smazání níže uvedených souborů je trvalá operace, tuto akci nelze vrátit zpět.",
        Files_Delete_Desc_3: "ostatní",
        Files_Delete_Button: "Ano, smazat soubory",
        Files_SubMenu_Rename: "Přejmenovat",
        Files_SubMenu_Move: "Přesunout",
        Files_SubMenu_Permissions: "Oprávnění",
        Files_SubMenu_Copy: "Kopírovat",
        Files_SubMenu_Archive: "Archiv",
        Files_SubMenu_Unarchive: "Zrušit archivaci",
        Files_SubMenu_Download: "Stáhnout",
        Files_SubMenu_Delete: "Smazat",
        Files_Edit_Ptero_Ignore_1: "Upravujete a",
        Files_Edit_Ptero_Ignore_2: "soubor. Všechny zde uvedené soubory nebo adresáře budou ze zálohování vyloučeny. Zástupné znaky jsou podporovány použitím hvězdičky",
        Files_Edit_Ptero_Ignore_3: "Předchozí pravidlo můžete negovat přidáním vykřičníku",
        Files_Edit_Save_Button: "Uložit obsah",
        Files_Create_Title: "Název souboru",
        Files_Create_Desc: "Zadejte název, pod kterým má být tento soubor uložen.",
        Files_Create_Error: "Název souboru je povinné pole",
        Files_Create_Button: "Vytvořit soubor",
        Files_Message_Archiving: "Archivuji soubory...",
        Files_Message_Deleting: "Mazání souborů...",
        Files_Create_Directory_Title: "Název adresáře",
        Files_Create_Directory_Desc_1: "Musí být poskytnut platný název adresáře.",
        Files_Create_Directory_Desc_2: "Tento adresář bude vytvořen jako",
        Files_Create_Directory_Button: "Vytvořit adresář",
        Files_Move_Desc_1: "Zadejte nový název a adresář tohoto souboru nebo složky vzhledem k aktuálnímu adresáři.",
        Files_Move_Desc_2: "Nové umístění:",
        Files_Drag_Desc: "Přetáhněte soubory k nahrání.",
        Files_Drag_Button: "Nahrát",
        Files_Error_1: "Je vyžadován název souboru.",
        Files_Error_2: "Na vzdáleném hostiteli došlo k chybě: Soubor nelze přesunout nebo přejmenovat, cíl již existuje."
      },
      Server_Users: {
        User_Page_Title: "Uživatelé",
        User_Sub_Users_Empty: "Zdá se, že nemáte žádné poduživatele.",
        User_Create_Title_1: "Vytvořit nového poduživatele",
        User_Create_Title_2: "E-mail uživatele",
        User_Create_Sub_User_Desc_1: "Zadejte e-mailovou adresu uživatele, kterého chcete pozvat jako dílčího uživatele tohoto serveru.",
        User_Create_Sub_User_Desc_2: "E-mailové adresy nesmí přesáhnout 191 znaků.",
        User_Create_Sub_User_Desc_3: "Musí být poskytnuta platná e-mailová adresa.",
        User_Modify_Or_View_Email_Title: "oprávnění pro {{subuser}}",
        User_Modify_Title: "Upravit",
        User_View_Title: "Zobrazit",
        User_Modify_Button: "Uložit",
        User_Create_Button_1: "Pozvat uživatele",
        User_Create_Button_2: "Nový uživatel",
        User_Create_Sub_User_Desc: "Při vytváření nebo úpravě jiných uživatelů lze vybrat pouze oprávnění, která jsou aktuálně přiřazena vašemu účtu.",
        User_Delete_Title: "Smazat tohoto poduživatele?",
        User_Delete_Desc_1: "Opravdu chcete odstranit tohoto poduživatele? Okamžitě bude mít veškerý přístup k tomuto serveru.",
        User_Delete_Button: "Ano, odebrat poduživatele",
        User_Show_2FA: "2FA povoleno",
        User_Show_Permissions: "Oprávnění",
        User_Create_Sub_Title_1: "Ovládání",
        User_Create_Sub_Title_2: "Uživatel",
        User_Create_Sub_Title_3: "Soubor",
        User_Create_Sub_Title_4: "Záloha",
        User_Create_Sub_Title_5: "Přidělení",
        User_Create_Sub_Title_6: "Spuštění",
        User_Create_Sub_Title_7: "Databáze",
        User_Create_Sub_Title_8: "Plán",
        User_Create_Sub_Title_9: "Nastavení",
        User_Create_Desc_1: "Oprávnění, která řídí schopnost uživatelů ovládat stav napájení serveru nebo odesílat příkazy.",
        User_Create_Desc_2: "Oprávnění, která uživateli umožňují spravovat další poduživatele na serveru. Nikdy nebudou moci upravovat svůj vlastní účet nebo přidělovat oprávnění, která sami nemají.",
        User_Create_Desc_3: "Oprávnění, která řídí schopnost uživatele upravovat souborový systém pro tento server.",
        User_Create_Desc_4: "Oprávnění, která řídí schopnost uživatele generovat a spravovat zálohy serveru.",
        User_Create_Desc_5: "Oprávnění, která řídí schopnost uživatele upravit alokaci portů pro tento server.",
        User_Create_Desc_6: "Oprávnění, která řídí schopnost uživatele zobrazit spouštěcí parametry tohoto serveru.",
        User_Create_Desc_7: "Oprávnění, která řídí přístup uživatele ke správě databáze pro tento server.",
        User_Create_Desc_8: "Oprávnění, která řídí přístup uživatele ke správě plánu pro tento server.",
        User_Create_Desc_9: "Oprávnění, která řídí přístup uživatele k nastavení tohoto serveru.",
        User_Create_Option_Desc_1: "Konzole",
        User_Create_Option_Desc_2: "Start",
        User_Create_Option_Desc_3: "Stop",
        User_Create_Option_Desc_4: "Restartovat",
        User_Create_Option_Desc_5: "Vytvořit",
        User_Create_Option_Desc_6: "Přečíst",
        User_Create_Option_Desc_7: "Aktualizovat",
        User_Create_Option_Desc_8: "Smazat",
        User_Create_Option_Desc_9: "Přečíst obsah",
        User_Create_Option_Desc_10: "Archiv",
        User_Create_Option_Desc_11: "SFTP",
        User_Create_Option_Desc_12: "Stáhnout",
        User_Create_Option_Desc_13: "Obnovit",
        User_Create_Option_Desc_14: "Docker-image",
        User_Create_Option_Desc_15: "Zobrazit_heslo",
        User_Create_Option_Desc_16: "Přejmenovat",
        User_Create_Option_Desc_17: "Přeinstalovat",
        User_Create_Option_Description_1: "Umožňuje uživateli odesílat příkazy do instance serveru přes konzolu.",
        User_Create_Option_Description_2: "Umožňuje uživateli spustit server, pokud je zastaven.",
        User_Create_Option_Description_3: "Umožňuje uživateli zastavit server, pokud je spuštěn.",
        User_Create_Option_Description_4: "Umožňuje uživateli provést restart serveru. To mu umožňuje spustit server, pokud je offline, ale neuvede server do zcela zastaveného stavu.",
        User_Create_Option_Description_5: "Umožňuje uživateli vytvářet nové poduživatele pro server.",
        User_Create_Option_Description_6: "Umožňuje uživateli zobrazit dílčí uživatele a jejich oprávnění pro server.",
        User_Create_Option_Description_7: "Umožňuje uživateli upravovat ostatní poduživatele.",
        User_Create_Option_Description_8: "Umožňuje uživateli smazat dílčího uživatele ze serveru.",
        User_Create_Option_Description_9: "Umožňuje uživateli vytvářet další soubory a složky prostřednictvím panelu nebo přímého nahrávání.",
        User_Create_Option_Description_10: "Umožňuje uživateli prohlížet obsah adresáře, ale ne prohlížet obsah nebo stahovat soubory.",
        User_Create_Option_Description_11: "Umožňuje uživateli zobrazit obsah daného souboru. To uživateli také umožní stahovat soubory.",
        User_Create_Option_Description_12: "Umožňuje uživateli aktualizovat obsah existujícího souboru nebo adresáře.",
        User_Create_Option_Description_13: "Umožňuje uživateli smazat soubory nebo adresáře.",
        User_Create_Option_Description_14: "Umožňuje uživateli archivovat obsah adresáře a také dekomprimovat existující archivy v systému.",
        User_Create_Option_Description_15: "Umožňuje uživateli připojit se k SFTP a spravovat soubory serveru pomocí ostatních přiřazených oprávnění k souboru.",
        User_Create_Option_Description_16: "Umožňuje uživateli vytvářet nové zálohy pro tento server.",
        User_Create_Option_Description_17: "Umožňuje uživateli zobrazit všechny zálohy, které pro tento server existují.",
        User_Create_Option_Description_18: "Umožňuje uživateli odstranit zálohy ze systému.",
        User_Create_Option_Description_19: "Umožňuje uživateli stáhnout zálohu pro server. Nebezpečí: umožňuje uživateli přístup ke všem souborům na serveru v záloze.",
        User_Create_Option_Description_20: "Umožňuje uživateli obnovit zálohu pro server. Nebezpečí: toto umožňuje uživateli smazat všechny soubory serveru v tomto procesu.",
        User_Create_Option_Description_21: "Umožňuje uživateli zobrazit všechny alokace aktuálně přiřazené tomuto serveru. Uživatelé s jakoukoli úrovní přístupu k tomuto serveru mohou vždy zobrazit primární alokaci.",
        User_Create_Option_Description_22: "Umožňuje uživateli přiřadit serveru další alokace.",
        User_Create_Option_Description_23: "Umožňuje uživateli změnit alokaci primárního serveru a připojit poznámky ke každé alokaci.",
        User_Create_Option_Description_24: "Umožňuje uživateli smazat alokaci ze serveru.",
        User_Create_Option_Description_25: "Umožňuje uživateli zobrazit spouštěcí proměnné serveru.",
        User_Create_Option_Description_26: "Umožňuje uživateli upravit spouštěcí proměnné pro server.",
        User_Create_Option_Description_27: "Umožňuje uživateli upravit obraz Dockeru používaný při spuštění serveru.",
        User_Create_Option_Description_28: "Umožňuje uživateli vytvořit novou databázi pro tento server.",
        User_Create_Option_Description_29: "Umožňuje uživateli zobrazit databázi přidruženou k tomuto serveru.",
        User_Create_Option_Description_30: "Umožňuje uživateli otočit heslo v instanci databáze. Pokud uživatel nemá oprávnění view_password, neuvidí aktualizované heslo.",
        User_Create_Option_Description_31: "Umožňuje uživateli odstranit instanci databáze z tohoto serveru.",
        User_Create_Option_Description_32: "Umožňuje uživateli zobrazit heslo spojené s instancí databáze pro tento server.",
        User_Create_Option_Description_33: "Umožňuje uživateli vytvářet nové plány pro tento server.",
        User_Create_Option_Description_34: "Umožňuje uživateli zobrazit plány a úkoly s nimi spojené pro tento server.",
        User_Create_Option_Description_35: "Umožňuje uživateli aktualizovat plány a plánovat úlohy pro tento server.",
        User_Create_Option_Description_36: "Umožňuje uživateli smazat plány pro tento server.",
        User_Create_Option_Description_37: "Umožňuje uživateli přejmenovat tento server.",
        User_Create_Option_Description_38: "Umožňuje uživateli spustit přeinstalaci tohoto serveru."
      },
      Server_Network: {
        Network_Page_Title: "Síť",
        Network_Alocations_Desc_1: "Momentálně používáte {{data}} z {{limit}} povolených alokací pro tento server.",
        Network_Create_Alocation_Button: "Vytvořit alokaci",
        Network_Hostname: "Název hostitele",
        Network_IP_Address: "IP adresa",
        Network_Port: "Port",
        Network_Notes: "Poznámky",
        Network_Primary: "Primární",
        Network_Primary_Button: "Nastavit jako primární",
        Network_Delete_Title: "Odstranit toto přidělení?",
        Network_Delete_Button: "Smazat",
        Network_Delete_Desc_1: "Tato alokace bude okamžitě odstraněna z vašeho serveru. Opravdu chcete pokračovat?",
        Network_Error_1: "Automatické přidělování serveru není pro tuto instanci povoleno.",
      },
      Server_Schedules: {
        Task_Page_Title: "Plány",
        Task_Empty_Message: "Pro tento server nejsou nakonfigurovány žádné plány.",
        Task_Create_Button: "Vytvořit plán",
        Task_Edit_Button: "Uložit změny",
        Task_Delete_Title: "Smazat plán?",
        Task_Delete_Button_1: "Ano, smazat plán",
        Task_Delete_Desc: "Opravdu chcete smazat tento plán? Všechny úlohy budou odstraněny a všechny běžící procesy budou ukončeny.",
        Task_Delete_Button_2: "Smazat",
        Task_Create_Title: "Vytvořit nový plán",
        Task_Edit_Title: "Upravit plán",
        Task_Create_Or_Edit_Title_1: "Název plánu",
        Task_Create_Or_Edit_Title_2: "Pouze když je server online",
        Task_Create_Or_Edit_Title_3: "Plán povolen",
        Task_Create_Or_Edit_Desc_1: "Lidsky čitelný identifikátor pro tento plán.",
        Task_Create_Or_Edit_Desc_2: "Systém plánů podporuje použití syntaxe Cronjob při definování, kdy mají úlohy začít běžet. Pomocí polí výše určete, kdy se mají tyto úlohy spustit.",
        Task_Create_Or_Edit_Desc_3: "Tento plán spusťte pouze tehdy, když je server ve spuštěném stavu.",
        Task_Create_Or_Edit_Desc_4: "Tento plán bude proveden automaticky, pokud je povolen.",
        Task_Create_Or_Edit_Minute: "Minuta",
        Task_Create_Or_Edit_Hour: "Hodina",
        Task_Create_Or_Edit_Day_Of_Month: "Den v měsíci",
        Task_Create_Or_Edit_Month: "Měsíc",
        Task_Create_Or_Edit_Day_Of_Week: "Den v týdnu",
        Task_New_Task_Button: "Nový úkol",
        Task_Run_Task_Button: "Spustit nyní",
        Task_Cron_Row_Minute: "minuta",
        Task_Cron_Row_Hour: "Hodina",
        Task_Cron_Row_Day_Month: "Den (měsíc)",
        Task_Cron_Row_Month: "Měsíc",
        Task_Cron_Row_Day_Week: "Den (týden)",
        Task_Task_Page_Title: "Úkoly",
        Task_Task_Processing: "Zpracovávání",
        Task_Task_Last_Run: "Poslední spuštění v:",
        Task_Task_Next_Run: "Další spuštění v:",
        Task_Task_Never: "Nikdy",
        Task_Task_NA: "n/a",
        Task_Task_Edit_Button: "Upravit",
        Task_Task_Active: "Aktivní",
        Task_Task_Inactive: "Neaktivní",
        Task_Task_Delete_Title: "Potvrdit smazání úkolu",
        Task_Task_Delete_Button: "Smazat úlohu",
        Task_Task_Delete_Desc: "Opravdu chcete smazat tuto úlohu? Tuto akci nelze vrátit zpět.",
        Task_Task_Files_And_Folders_Message: "Ignorování souborů a složek:",
        Task_Task_Continue_Message: "Pokračuje při selhání",
        Task_Task_Time_Message: "o {{time}}s později",
        Task_Task_Edit_Title: "Upravit úkol",
        Task_Task_Create_Title: "Vytvořit úkol",
        Task_Task_Create_Or_Edit_Command: "Odeslat příkaz",
        Task_Task_Create_Or_Edit_Power: "Odeslat akci napájení",
        Task_Task_Create_Or_Edit_Backup: "Vytvořit zálohu",
        Task_Task_Create_Or_Edit_Title_1: "Časový posun (v sekundách)",
        Task_Task_Create_Or_Edit_Title_2: "Úžitková zátěž",
        Task_Task_Create_Or_Edit_Title_3: "Ignorované soubory",
        Task_Task_Create_Or_Edit_Title_4: "Pokračovat při selhání",
        Task_Task_Create_Or_Edit_Title_5: "Akce",
        Task_Task_Create_Or_Edit_Desc_1: "Doba čekání po provedení předchozí úlohy před spuštěním této úlohy. Pokud se jedná o první úlohu v plánu, nebude použita.",
        Task_Task_Create_Or_Edit_Desc_2: "Volitelné. Zahrnout soubory a složky, které mají být z této zálohy vyloučeny. Ve výchozím nastavení bude použit obsah vašeho souboru .pteroignore. Pokud jste dosáhli limitu zálohy, nejstarší záloha bude otočena.",
        Task_Task_Create_Or_Edit_Desc_3: "Pokud tato úloha selže, budou spuštěny budoucí úlohy.",
        Task_Task_Create_Or_Edit_Option_1: "Spusťte server",
        Task_Task_Create_Or_Edit_Option_2: "Restartujte server",
        Task_Task_Create_Or_Edit_Option_3: "Zastavit server",
        Task_Task_Create_Or_Edit_Option_4: "Ukončit server",
        Task_Task_Create_Or_Edit_Error_1: "Musí být poskytnuta datová část úlohy.",
        Task_Task_Create_Or_Edit_Error_2: "Časový posun musí být platné číslo mezi 0 a 900.",
        Task_Task_Create_Or_Edit_Error_3: "Musí být zadána hodnota časového posunu.",
        Task_Task_Create_Or_Edit_Error_4: "Časový posun musí být alespoň 0 sekund.",
        Task_Task_Create_Or_Edit_Error_5: "Časový posun musí být menší než 900 sekund.",
        Task_Task_Create_Or_Edit_Error_6: "Úlohu zálohování nelze vytvořit, když je limit zálohování serveru nastaven na 0."
      },
      Server_Settings: {
        Settings_Page_Title: "Nastavení",
        Settings_SFTP_Title_1: "Podrobnosti SFTP",
        Settings_SFTP_Title_2: "Adresa serveru",
        Settings_SFTP_Title_3: "Uživatelské jméno",
        Settings_SFTP_Desc_1: "Vaše heslo SFTP je stejné jako heslo, které používáte pro přístup k tomuto panelu.",
        Settings_SFTP_Button: "Spustit SFTP",
        Settings_Debug_Title_1: "Informace o ladění",
        Settings_Debug_Title_2: "Uzel",
        Settings_Debug_Title_3: "ID serveru",
        Settings_Reinstall_Title_1: "Přeinstalovat server",
        Settings_Reinstall_Title_2: "Potvrdit přeinstalaci serveru",
        Settings_Reinstall_Button: "Ano, přeinstalovat server",
        Settings_Reinstall_Desc_1: "Váš server bude zastaven a některé soubory mohou být během tohoto procesu smazány nebo upraveny, opravdu chcete pokračovat?",
        Settings_Reinstall_Desc_2: "Přeinstalace serveru jej zastaví a poté znovu spusťte instalační skript, který jej původně nastavil.",
        Settings_Reinstall_Desc_3: "Během tohoto procesu mohou být některé soubory smazány nebo upraveny, před pokračováním prosím zálohujte svá data.",
        Settings_Reinstall_Success: "Váš server zahájil proces přeinstalace.",
        Settings_Reinstall_Error: "Nelze navázat připojení k počítači, na kterém běží tento server. Zkuste to prosím znovu.",
        Settings_Rename_Server_Title_1: "Změnit název serveru",
        Settings_Rename_Server_Title_2: "Název serveru",
        Settings_Rename_Server_Button: "Uložit",
        Settings_Rename_Required: "Název je povinné pole"
      },
      Server_Startup: {
        Startup_Page_Title: "Nastavení spouštění",
        Startup_Command_Title_1: "Příkaz pro spuštění",
        Startup_Docker_Title: "Obrázek dockeru",
        Startup_Docker_Desc: "Toto je pokročilá funkce, která vám umožňuje vybrat obraz Dockeru, který se má použít při spuštění této instance serveru.",
        Startup_Docker_Error: "Obrázek Dockeru tohoto serveru byl ručně nastaven administrátorem a nelze jej změnit prostřednictvím tohoto uživatelského rozhraní.",
        Startup_Variables_Title: "Proměnné",
        Startup_Variables_Read: "Pouze pro čtení",
        Startup_Server_Error_Title: "Jejda!",
      },
      Server_Features: {
        Features_Invalid_Java_Title_1: "Neplatná verze Java, aktualizovat obrázek Docker?",
        Features_Invalid_Java_Desc_1: "Tento server nelze spustit, protože není splněna požadovaná verze Java.",
        Features_Invalid_Java_Desc_2: `Stisknutím tlačítka "Aktualizovat obrázek Dockeru" níže potvrzujete, že obrázek Dockeru, který tento server používá, bude změněn na obrázek níže, který má verzi Java, kterou požadujete.`,
        Features_Invalid_Java_Desc_3: "Vyberte prosím verzi Java ze seznamu níže.",
        Features_Invalid_Java_Button_1: "Aktualizovat obrázek Docker",
        Features_Invalid_Java_Button_2: "Zrušit",
        Features_Accept_Eula_Title: "Přijmout Minecraft® EULA",
        Features_Accept_Eula_Desc_1: `Stisknutím tlačítka "Přijímám" níže vyjadřujete svůj souhlas s`,
        Features_Accept_Eula_Desc_2: "Minecraft® EULA",
        Features_Accept_Eula_Button_1: "Přijímám",
        Features_Accept_Eula_Button_2: "Zrušit",
        Features_Invalid_GSL_Title: "Neplatný token GSL!",
        Features_Invalid_GSL_Desc_1: "Zdá se, že váš přihlašovací token k hernímu serveru (GSL token) je neplatný nebo vypršela.",
        Features_Invalid_GSL_Desc_2: "Můžete buď vygenerovat nový a zadat jej níže, nebo nechat pole prázdné, chcete-li jej zcela odstranit.",
        Features_Invalid_GSL_Desc_3: "GSL Token",
        Features_Invalid_GSL_Desc_4: "Navštivte https://steamcommunity.com/dev/managegameservers a vygenerujte token.",
        Features_Invalid_GSL_Button: "Aktualizovat GSL token",
        Features_Invalid_PID_Title_1: "Byl dosažen limit paměti nebo procesu...",
        Features_Invalid_PID_Title_2: "Dosažen možný limit zdrojů...",
        Features_Invalid_PID_Desc_1: "Tento server dosáhl maximálního limitu procesu nebo paměti.",
        Features_Invalid_PID_Desc_2: "Zvyšování",
        Features_Invalid_PID_Desc_3: "container_pid_limit",
        Features_Invalid_PID_Desc_4: "v konfiguraci křídel,",
        Features_Invalid_PID_Desc_5: "config.yml",
        Features_Invalid_PID_Desc_6: ", může pomoci vyřešit tento problém.",
        Features_Invalid_PID_Desc_7: "Poznámka: Aby se změny konfiguračního souboru projevily, musí být Wings restartovány",
        Features_Invalid_PID_Desc_8: "Tento server se pokouší využít více zdrojů, než je přiděleno. Kontaktujte prosím administrátora a uveďte níže uvedenou chybu.",
        Features_Invalid_PID_Desc_9: "pthread_create se nezdařilo, pravděpodobně nedostatek paměti nebo byly dosaženy limity procesu/prostředku",
        Features_Invalid_Disk_Title: "Nedostatek místa na disku...",
        Features_Invalid_Disk_Desc_1: "Tento server má nedostatek volného místa na disku a nemůže dokončit proces instalace nebo aktualizace.",
        Features_Invalid_Disk_Desc_2: "Zajistěte, aby měl počítač dostatek místa na disku zadáním",
        Features_Invalid_Disk_Desc_3: "df -h",
        Features_Invalid_Disk_Desc_4: "na počítači hostujícím tento server. Problém vyřešíte odstraněním souborů nebo zvětšením dostupného místa na disku.",
        Features_Invalid_Disk_Desc_5: "Tento server má nedostatek volného místa na disku a nemůže dokončit proces instalace nebo aktualizace. Kontaktujte prosím správce a informujte je o problémech s místem na disku.",
      },
      Server_States: {
        Server_Installing_Title: "Spuštění instalačního programu",
        Server_Installing_Desc: "Váš server by měl být brzy připraven, zkuste to prosím znovu za několik minut.",
        Server_Suspended_Title: "Server pozastaven",
        Server_Suspended_Desc: "Tento server je pozastaven a nelze k němu získat přístup.",
        Server_Transferring_Title: "Přenos",
        Server_Transferring_Desc: "Váš server se přenáší do nového uzlu, vraťte se prosím později.",
        Server_Restoring_Title: "Obnovování ze zálohy",
        Server_Restoring_Desc: "Váš server se právě obnovuje ze zálohy, vraťte se prosím za několik minut."
      },
      Page_Titles: {
        Title_Console: "Konzole",
        Title_File_Manager: "Správce souborů",
        Title_Databases: "Databáze",
        Title_Schedules: "Plány",
        Title_Users: "Uživatelé",
        Title_Backups: "Zálohy",
        Title_Network: "Síť",
        Title_Startup: "Spuštění",
        Title_Settings: "Nastavení",
        Title_API_Credentials: "Pověření API"
      },
      Errors: {
        Error_Key_Undefined: "Interní chyba: Klíč pro tuto zprávu nebyl nastaven, kontaktujte autora: Ferks#7575",
        Error_Server_Title: "Něco se pokazilo",
        Error_Server_Desc: "Požadovaný zdroj nebyl nalezen.",
        Error_Connection: "Při komunikaci se strojem, na kterém běží tento server, došlo k chybě. Tato chyba byla zaznamenána, zkuste to prosím znovu.",
        Error_Network: "Chyba sítě",
        Error_Permission_Title: "Přístup odepřen",
        Error_Permission_Desc: "Nemáte oprávnění pro přístup k této stránce.",
        Error_Variables_1: "Pole hodnoty je povinné.",
        Error_Variables_2: "Hodnota musí být 1 číslice.",
        Error_Variables_3: "Tato hodnota není platná.",
        Error_Variables_4: "Hodnota musí být alespoň 1.",
        Error_Variables_5: "Tato hodnota je větší než limit.",
        Error_Variables_6: "Formát hodnoty je neplatný.",
        Error_Variables_7: "Hodnota může obsahovat pouze písmena, čísla a pomlčky."
      },
      System_Translation: {
        System_Change_Language_Title: "Konfigurovat jazyk",
        System_Change_Language_Desc: "Vyberte jazyk, který se má vykreslit na vašem panelu."
      }
    }
}
