export default {
	translation: {
		Login: {
			Title: "Se connecter pour continuer",
			Username_or_Email: "Nom d'utilisateur ou e-mail",
			Password: "Mot de passe",
			Login_Button: "Connexion",
			Forgot_Password: "Mot de passe oublié ?",
			Username_or_Email_Desc: "Un nom d'utilisateur ou un e-mail doit être fourni.",
			Account_Password_Desc: "Veuillez entrer le mot de passe de votre compte.",
			Account_Incorrect: "Aucun compte correspondant à ces informations d'identification n'a pu être trouvé.",
			Many_Attempts: "Il y a eu trop de tentatives de connexion. Veuillez réessayer plus tard.",
			Recaptcha_Error: "Échec de la validation des données reCAPTCHA.",
			Request_Failed: "La demande a échoué avec le code d'erreur 404",
			CSRF_Token: "Non-conformité du jeton CSRF."
		},
		Reset_Password: {
			Password_Reset: "Demander la réinitialisation du mot de passe",
			Email: "email",
			New_Password_Required: "Un nouveau mot de passe est nécessaire.",
			Password_Characters_Min: "Votre nouveau mot de passe doit comporter au moins 8 caractères.",
			Password_Not_Match: "Votre nouveau mot de passe ne correspond pas.",
			Account_Email: "Saisissez l'adresse électronique de votre compte pour recevoir des instructions sur la réinitialisation de votre mot de passe.",
			Valid_Email: "Une adresse électronique valide doit être fournie pour continuer.",
			Send_Email: "Envoyer un e-mail",
			Return_to_Login: "Retour à la page de connexion",
			Reset_Password: "Réinitialiser le mot de passe",
			New_Password: "Nouveau mot de passe",
			New_Password_Desc: "Les mots de passe doivent comporter au moins 8 caractères.",
			Confirm_New_Password: "Confirmer le nouveau mot de passe",
			Send_Email_Link: "Nous vous avons envoyé par e-mail le lien de réinitialisation de votre mot de passe !"
		},
		Two_Factor_Auth: {
			Device_Checkpoint: "Point de contrôle du dispositif",
			Recovery_Code: "Code de récupération",
			Authentication_Code: "Code d'authentification",
			Enter_Two_Factor_Desc_1: "Saisissez le jeton à deux facteurs généré par votre appareil.",
			Enter_Two_Factor_Desc_2: "Saisissez l'un des codes de récupération générés lors de la configuration de l'authentification à deux facteurs sur ce compte afin de continuer.",
			Lost_Device: "J'ai perdu mon appareil",
			Have_Device: "J'ai mon appareil",
			Continue: "Continuer"
		},
		Account_Overview: {
			Two_Factor_Activate_Desc_1: "Vous devez fournir un code d'authentification pour continuer.",
			Two_Factor_Activate_Desc_2: "L'authentification à deux facteurs est actuellement activée sur votre compte.",
			Two_Factor_Activate_Desc_3: "Le code d'authentification doit être composé de 6 chiffres.",
			Two_Factor_Active_Title: "Authentification à deux facteurs activée",
			Two_Factor_Active_Desc_2: "Ces codes ne seront plus affichés à nouveau.",
			Two_Factor_Active_Desc_3: "Veuillez les copier en les stockant dans un référentiel sécurisé tel qu'un gestionnaire de mots de passe.",
			Two_Factor_Active_Desc_1: "L'authentification à deux facteurs a été activée sur votre compte.Si vous perdez l'accès à votre périphérique d'authentification, vous devez utiliser l'un des codes ci-dessous afin d'accéder à votre compte.",
			Two_Factor_Active_Button: "Fermer",
			Two_Factor_Disabled_Desc: "Vous n'avez actuellement pas d'authentification à deux facteurs activée sur votre compte. Cliquez sur le bouton ci-dessous pour commencer à la configurer.",
			Two_Factor_Disable_Desc_1: "Vous devez fournir votre mot de passe actuel afin de continuer.",
			Two_Factor_Disable_Desc_2: "Afin de désactiver l'authentification à deux facteurs, vous devrez fournir un mot de passe de compte.",
			Two_Factor_Disable_Title: "Mot de passe actuel",
			Two_Factor_Disable_Button: "Désactiver l'authentification à deux facteurs",
			Two_Factor_Setup_Desc_1: "Entrez le code à partir de votre périphérique après le scan du QR code.",
			Two_Factor_Setup_Desc_2: "Alternativement, entrez le jeton suivant dans votre application d'authentification:",
			Two_Factor_Setup_Button: "Installer",
			Two_Factor_Incorrect_Password: "Le mot de passe fourni n'est pas valide.",
			Button_Disable: "Désactiver",
			Button_Enable: "Activer",
			Create_Api_Desc_Title: "Description",
			Create_Api_Desc: "Renseignez une description de cette API.",
			Create_Api_Ips_Title: "IPs Autorisés",
			Create_Api_Ips_Desc: "Laisser vide pour permettre à n'importe quelle adresse IP d'utiliser cette clé API, sinon fournissez chaque adresse IP sur une nouvelle ligne.",
			Create_Api_Button: "Créer",
			Update_Email_Desc_1: "Vous devez fournir votre mot de passe de compte actuel.",
			Update_Email_Required: "Le courrier électronique est un champ obligatoire",
			Update_Email_Success_Title: "Succès",
			Update_Email_Success: "Votre e-mail principal a été mis à jour.",
			Update_Email_Error_Title: "Erreur",
			Update_Email_Button: "Mettre à jour votre e-mail",
			Update_Password_Title: "nouveau mot de passe",
			Update_Password_Desc_1: "Vous devez fournir votre mot de passe actuel.",
			Update_Password_Desc_2: "La confirmation de mot de passe ne correspond pas au mot de passe que vous avez entré.",
			Update_Password_Desc_3: "Votre nouveau mot de passe doit comporter au moins 8 caractères de longueur et unique sur ce site Web.",
			Update_Password_Required: "Mot de passe est un champ obligatoire",
			Update_Password_Button: "Mettre à jour le mot de passe",
			Update_Password_Error: "Le mot de passe fourni était invalide pour ce compte.",
			Update_Password_Min: "Le mot de passe doit comporter au moins 8 caractères.",
			Confirm_Password: "Confirmez le mot de passe",
			Account_Page_Title: "Aperçu du compte",
			Account_Two_Factor_Required_Title: "2 facteur requis",
			Account_Two_Factor_Required_Desc: "Votre compte doit avoir une authentification à deux facteurs activée afin de continuer.",
			Account_Update_Email_Title: "Mettre a jour l'adresse e-mail",
			Account_Setup_Two_Factor_Title: "Configurer la double authentification",
			Api_Page_Title: "API de compte",
			Api_Create_Title: "Créer une clé API",
			Api_List_Title: "Clé API",
			Api_List_Loading: "Chargement...",
			Api_List_Empty: "Aucune clés API n'existe pour ce compte.",
			Api_List_Used_1: "Dernière utilisation:",
			Api_List_Used_2: "Jamais",
			Api_Delete_Title: "Confirmer la suppression de la clé",
			Api_Delete_Button: "Oui, supprimer la clé",
			Api_Delete_Desc: "Êtes-vous sûr de vouloir supprimer cette clé API ? Toutes les demandes en utilisant cela seront immédiatement invalidées et échoueront.",
			Api_Setup_Title: "Votre clé API",
			Api_Setup_Desc: "La clé API que vous avez demandée est affichée ci-dessous. Veuillez stocker celle-ci dans un endroit sûr, elle ne sera pas affichée à nouveau.",
			Api_Min_Characters: "La description doit comporter au moins 4 caractères",
			Api_Setup_Button: "Fermer",
			Api_Ip_Incorrect_1: "Adresse IP 1 doit être une adresse IP valide.",
			Api_Ip_Incorrect_2: "Adresse IP 2 doit être une adresse IP valide.",
			Api_Ip_Incorrect_3: "Adresse IP 3 doit être une adresse IP valide."
		},
		Search: {
			Search_Title: "Terme de recherche",
			Search_Desc_1: "Veuillez entrer au moins trois caractères pour commencer la recherche.",
			Search_Desc_2: "Entrez un nom de serveur, UUID ou une allocation pour commencer la recherche."
		},
		Dashboard: {
			Dash_Page_Title: "Tableau de bord",
			Dash_Show_Server_1: "Afficher tous les serveurs",
			Dash_Show_Server_2: "Afficher vos serveurs",
			Dash_Show_Server_3: "Il n'y a pas d'autres serveurs à afficher.",
			Dash_Show_Server_4: "Il n'y a pas de serveurs associés à votre compte."
		},
		Server_Row: {
			Server_Unlimited: "Illimité",
			Server_Suspended: "Suspendue",
			Server_Connect_Error: "Erreur de connexion",
			Server_Transferring: "Transfert",
			Server_Installing: "Installation",
			Server_Restoring_Backup: "Restauration de la sauvegarde",
			Server_Unavailable: "Indisponible",
			Server_Of: "de"
		},
		Elements: {
			Elements_Cancel_Button: "Annuler",
			Elements_Copy_Text: "Copié dans le presse-papier.",
			Elements_Error: "Une erreur a été rencontrée par l'application. Essayez de rafraîchir la page."
		},
		Server: {
			Server_Page_Title: "console",
			Server_Transfer_Console: "Le transfert a échoué.",
			Server_Archived_Console: "Le serveur a été archivé avec succès, tentative de connexion au nœud cible ..",
			Server_Send_Command: "Saisir une commande...",
			Server_State_Console: "Serveur marqué comme ",
			Server_State_Starting: "Démarrage en cours",
			Server_State_Offline: "hors ligne",
			Server_State_Stopping: "Arrêt en cours",
			Server_State_Running: "fonctionnement",
			Server_State_Connect: "De liaison...",
			Server_State_Install: "Ce serveur est actuellement en cours d'installation, la plupart des actions sont indisponibles.",
			Server_State_Transfer: "Ce serveur est en cours de transfert sur un autre nœud et toutes les actions sont indisponibles.",
			Server_Button_Start: "Début",
			Server_Button_Restart: "Redémarrage",
			Server_Button_Kill: "Arrêt forcé",
			Server_Button_Stop: "Arrêter",
			Server_Memory_Graph_Title: "Utilisation de la mémoire",
			Server_Cpu_Graph_Title: "Utilisation du processeur",
			Server_Graph_Desc: "Le serveur est hors ligne.",
			Server_Websocket_Error: "Une erreur s'est produite lors de la validation des informations d'identification fournies pour la bande WebSocket. Veuillez actualiser la page.",
			Server_Connect_Server: "Nous avons des problèmes de connexion à votre serveur, veuillez patienter..."
		},
		Server_Backup: {
			Backup_Page_Title: "Sauvegarde",
			Backup_Empty_1: "Vous ne possédez actuellement pas de sauvegardes",
			Backup_Empty_2: "On dirait qu'il n'y a actuellement aucune sauvegarde stockée pour ce serveur.",
			Backup_Forbidden: "Les sauvegardes ne peuvent pas être créées pour ce serveur car la limite de sauvegarde est définie sur 0.",
			Backup_Information: "Les sauvegardes ont été créées pour ce serveur.",
			Backup_Create_Title_1: "Créer une sauvegarde du serveur",
			Backup_Create_Title_2: "Nom de sauvegarde",
			Backup_Create_Title_3: "Fichiers et annuaires ignorés",
			Backup_Create_Title_4: "Verouiller",
			Backup_Create_Desc_1: "Si cela est fourni, le nom qui doit être utilisé pour référencer cette sauvegarde.",
			Backup_Create_Desc_2: "Entrez les fichiers ou les dossiers à ignorer lors de la sauvegarde. Laissez vide pour sauvegarder l'ensemble.",
			Backup_Create_Desc_3: "Empêche cette sauvegarde d'être supprimée jusqu'à ce qu'il soit explicitement déverrouillé.",
			Backup_Create_Start_Button: "Démarrer la sauvegarde",
			Backup_Create_Button: "Créer une sauvegarde",
			Backup_Created_Title: "Déverrouillez cette sauvegarde ?",
			Backup_Created_Desc_1: "Êtes-vous sûr de vouloir déverrouiller cette sauvegarde ? Celle-ci ne sera plus protégée des suppressions automatisées ou accidentelles.",
			Backup_Created_Button: "Oui, déverrouiller",
			Backup_Restore_Title: "Restaurer cette sauvegarde ?",
			Backup_Restore_Desc_1: "Ce serveur sera arrêté afin de restaurer la sauvegarde. Une fois que la sauvegarde a commencé, vous ne pourrez pas contrôler l'état d'alimentation du serveur, accéder au gestionnaire de fichiers ou créer des sauvegardes supplémentaires jusqu'à ce qu'elle soit terminée.",
			Backup_Restore_Desc_2: "Es-tu sûr de vouloir continuer ?",
			Backup_Restore_Desc_3: "Supprimez tous les fichiers et les dossiers avant de restaurer cette sauvegarde.",
			Backup_Restore_Button: "Restaurer la sauvegarde",
			Backup_Delete_Title: "Supprimer cette sauvegarde?",
			Backup_Delete_Desc_1: "Êtes-vous sûr de vouloir supprimer cette sauvegarde ? Il s'agit d'une opération permanente et la sauvegarde ne peut pas être récupérée une fois supprimée.",
			Backup_Delete_Button: "Oui, supprimer la sauvegarde",
			Backup_SubMenu_Download: "Télécharger",
			Backup_SubMenu_Restore: "Restaurer",
			Backup_SubMenu_Unlock: "Ouvrir",
			Backup_SubMenu_Lock: "Verouiller",
			Backup_SubMenu_Delete: "Effacer"
		},
		Server_Databases: {
			Database_Page_Title: "Bases de données",
			Database_Show_Empty: "On dirait que vous n'avez pas de bases de données.",
			Database_Show_Forbidden: "Les bases de données ne peuvent pas être créées pour ce serveur.",
			Database_Limit_Desc: "Des bases de données ont été allouées à ce serveur.",
			Database_Create_Title_1: "Créer une nouvelle base de données",
			Database_Create_Title_2: "Nom de la base de données",
			Database_Create_Title_3: "Connexions de",
			Database_Create_Desc_1: "Un nom descriptif de votre instance de base de données.",
			Database_Create_Desc_2: "Où les connexions doivent être autorisées. Utilisez % pour caractères génériques.",
			Database_Create_Button_1: "Créer une base de données",
			Database_Create_Button_2: "Nouvelle base de données",
			Database_Create_Error_1: "Une erreur inattendue a été rencontrée lors du traitement de cette demande, veuillez réessayer.",
			Database_Create_Error_2: "Un nom de base de données doit être fourni.",
			Database_Create_Error_3: "Le nom de la base de données doit comporter au moins 3 caractères.",
			Database_Create_Error_4: "Le nom de la base de données ne doit pas dépasser 48 caractères.",
			Database_Create_Error_5: "Le nom de la base de données ne doit contenir que des caractères alphanumériques, des traits de soulignement, des tirets et/ou des périodes.",
			Database_Create_Error_6: "Une valeur de connexion doit être fournie.",
			Database_Create_Error_7: "Une adresse de connexion valide doit être fournie.",
			Database_Delete_Title_1: "Confirmer la suppression de la base de données",
			Database_Delete_Title_2: "Confirmer le nom de la base de données",
			Database_Delete_Title_3: "Détails de la connexion de la base de données",
			Database_Delete_Title_4: "Point de terminaison",
			Database_Delete_Title_5: "Connexions de",
			Database_Delete_Title_6: "Nom d'utilisateur",
			Database_Delete_Title_7: "Mot de passe",
			Database_Delete_Title_8: "jdbcConnectionString",
			Database_Rotate_Button: "Rotate Password",
			Database_Delete_Desc_1: "La suppression d'une base de données est une action permanente, elle ne peut pas être annulée. Cela supprimera définitivement la base de données " {
				{
					database
				}
			}
			" et supprimera toutes les données associées.",
			Database_Create_Desc_2: "Entrez le nom de la base de données pour confirmer la suppression.",
			Database_Delete_Button: "Supprimer la base de données",
			Database_Delete_Error_1: "Le nom de la base de données doit être fourni.",
			Database_Delete_Error_2: "Aucun hôte de base de données n'a été trouvé qui répond aux exigences de ce serveur."
		},
		Server_Files: {
			Files_Page_Title: "Gestionnaire de fichiers",
			Files_Create_Button: "Nouveau fichier",
			Files_Directory_Empty: "Ce répertoire semble être vide.",
			Files_Show_Files_Max: "Ce répertoire est trop volumineux pour afficher dans le navigateur, limitant la sortie aux 250 premiers fichiers.",
			Files_Chmod_Title: "Mode de fichier",
			Files_Chmod_Button: "Mettre à jour",
			Files_Delete_File_Or_Directory_Title: "Supprimer la sélection",
			Files_Delete_File_Or_Directory_Button: "Oui, supprimer",
			Files_Delete_File_Or_Directory_Desc: "La suppression des fichiers est une opération permanente, vous ne pouvez pas annuler cette action.",
			Files_Delete_File: "Déposer",
			Files_Delete_Directory: "Annuaire",
			Files_Delete_Title: "Supprimer ces fichiers ?",
			Files_Delete_Desc_1: "Êtes-vous sûr de vouloir supprimer {{selected}} fichier(s) ?",
			Files_Delete_Desc_2: "La suppression du ou des fichiers listés ci-dessous est une opération permanente, vous ne pouvez pas annuler cette action.",
			Files_Delete_Desc_3: "autres",
			Files_Delete_Button: "Oui, supprimez les fichiers",
			Files_SubMenu_Rename: "renommer",
			Files_SubMenu_Move: "Se déplacer",
			Files_SubMenu_Permissions: "Autorisation",
			Files_SubMenu_Copy: "Copie",
			Files_SubMenu_Archive: "Archiver",
			Files_SubMenu_Unarchive: "Extraire",
			Files_SubMenu_Download: "Télécharger",
			Files_SubMenu_Delete: "Effacer",
			Files_Edit_Ptero_Ignore_1: "Vous éditer un",
			Files_Edit_Ptero_Ignore_2: "Déposer. Tous les fichiers ou répertoires répertoriés ici seront exclus des sauvegardes. Les caractères génériques sont supportés par l'utilisation d'un astérisque",
			Files_Edit_Ptero_Ignore_3: "Vous pouvez annuler une règle préalable en prépage un point d'exclamation",
			Files_Edit_Save_Button: "Conserver le contenu",
			Files_Create_Title: "Nom de fichier",
			Files_Create_Desc: "Entrez le nom que ce fichier doit être enregistré en tant que.",
			Files_Create_Error: "Le nom de fichier est un champ obligatoire",
			Files_Create_Button: "Créer un fichier",
			Files_Message_Archiving: "Archivage des fichiers...",
			Files_Message_Deleting: "Suppression de fichiers...",
			Files_Create_Directory_Title: "Nom de répertoire",
			Files_Create_Directory_Desc_1: "Un nom de répertoire valide doit être fourni.",
			Files_Create_Directory_Desc_2: "Ce répertoire sera créé comme",
			Files_Create_Directory_Button: "Créer le répertoire",
			Files_Move_Desc_1: "Entrez le nouveau nom et répertoire de ce fichier ou de ce dossier, relatif au répertoire actuel.",
			Files_Move_Desc_2: "Nouvel emplacement:",
			Files_Drag_Desc: "Faites glisser et déposez des fichiers pour télécharger.",
			Files_Drag_Button: "Télécharger",
			Files_Error_1: "Un nom pour le fichier est requis.",
			Files_Error_2: "Une erreur s'est produite sur l'hôte distant: impossible de déplacer ou de renommer le fichier, la destination existe déjà .."
		},
		Server_Users: {
			User_Page_Title: "Utilisateurs",
			User_Sub_Users_Empty: "On dirait que vous n'avez pas d'autres utilisateurs'.",
			User_Create_Title_1: "Créer un nouvel utilisateur",
			User_Create_Title_2: "Email utilisateur",
			User_Create_Sub_User_Desc_1: "Entrez l'adresse e-mail de l'utilisateur que vous souhaitez inviter pour ce serveur.",
			User_Create_Sub_User_Desc_2: "Les adresses électroniques ne doivent pas dépasser 191 caractères.",
			User_Create_Sub_User_Desc_3: "Une adresse électronique valide doit être fournie.",
			User_Modify_Or_View_Email_Title: "Autorisations pour {{subuser}}",
			User_Modify_Title: "Modifier",
			User_View_Title: "Vue",
			User_Modify_Button: "sauvegarder",
			User_Create_Button_1: "Inviter l'utilisateur",
			User_Create_Button_2: "Nouvel utilisateur",
			User_Create_Sub_User_Desc: "Seules les autorisations que votre compte soit actuellement affecté peuvent être sélectionnées lors de la création ou de la modification d'autres utilisateurs.",
			User_Delete_Title: "Supprimer cet utilisateur ?",
			User_Delete_Desc_1: "Êtes-vous sûr de vouloir supprimer cet utilisateur ? Il perdra tout accès à ce serveur.",
			User_Delete_Button: "Oui, révoquer l'utilisateur",
			User_Show_2FA: "2FA activé",
			User_Show_Permissions: "Autorisation",
			User_Create_Sub_Title_1: "Contrôler",
			User_Create_Sub_Title_2: "Utilisateur",
			User_Create_Sub_Title_3: "Déposer",
			User_Create_Sub_Title_4: "Sauvegarde",
			User_Create_Sub_Title_5: "allocation",
			User_Create_Sub_Title_6: "Commencez",
			User_Create_Sub_Title_7: "Base de données",
			User_Create_Sub_Title_8: "Calendrier",
			User_Create_Sub_Title_9: "Paramètres",
			User_Create_Desc_1: "Autorisations qui contrôlent la capacité des utilisateurs à contrôler l'état d'alimentation d'un serveur ou d'envoyer des commandes.",
			User_Create_Desc_2: "Autorisations permettant à un utilisateur de gérer d'autres utilisateurs sur un serveur. Ils ne seront jamais en mesure de modifier leur propre compte ou d'attribuer des autorisations qu'ils n'ont pas eux-mêmes.",
			User_Create_Desc_3: "Autorisations qui contrôlent la capacité d'un utilisateur à modifier le système de fichiers de ce serveur.",
			User_Create_Desc_4: "Autorisations qui contrôlent la capacité d'un utilisateur à générer et à gérer des sauvegardes de serveur.",
			User_Create_Desc_5: "Autorisations qui contrôlent la capacité d'un utilisateur à modifier les allocations de ports de ce serveur.",
			User_Create_Desc_6: "Autorisations qui contrôlent la capacité d'un utilisateur à afficher les paramètres de démarrage de ce serveur.",
			User_Create_Desc_7: "Autorisations qui contrôlent l'accès d'un utilisateur à la gestion de la base de données pour ce serveur.",
			User_Create_Desc_8: "Autorisations qui contrôlent l'accès d'un utilisateur à la gestion de la planification de ce serveur.",
			User_Create_Desc_9: "Autorisations qui contrôlent l'accès d'un utilisateur aux paramètres de ce serveur.",
			User_Create_Option_Desc_1: "Console",
			User_Create_Option_Desc_2: "Début",
			User_Create_Option_Desc_3: "Arrêter",
			User_Create_Option_Desc_4: "Redémarrage",
			User_Create_Option_Desc_5: "Créer",
			User_Create_Option_Desc_6: "Lire",
			User_Create_Option_Desc_7: "Mettre à jour",
			User_Create_Option_Desc_8: "Effacer",
			User_Create_Option_Desc_9: "En lecture",
			User_Create_Option_Desc_10: "Archiver",
			User_Create_Option_Desc_11: "SFTP",
			User_Create_Option_Desc_12: "Télécharger",
			User_Create_Option_Desc_13: "Restaurer",
			User_Create_Option_Desc_14: "docker-Image",
			User_Create_Option_Desc_15: "voir LeMot DePasse",
			User_Create_Option_Desc_16: "Renommer",
			User_Create_Option_Desc_17: "Réinstaller",
			User_Create_Option_Description_1: "Permet à un utilisateur d'envoyer des commandes à l'instance de serveur via la console.",
			User_Create_Option_Description_2: "Permet à un utilisateur de démarrer le serveur s'il est arrêté.",
			User_Create_Option_Description_3: "Permet à un utilisateur d'arrêter un serveur s'il est en cours d'exécution.",
			User_Create_Option_Description_4: "Permet à un utilisateur d'effectuer un redémarrage du serveur.Cela leur permet de démarrer le serveur s'il est hors ligne, mais ne mettez pas le serveur dans un état complètement arrêté.",
			User_Create_Option_Description_5: "Permets à un utilisateur de créer de nouveaux sous-consommateurs pour le serveur.",
			User_Create_Option_Description_6: "Permets à l'utilisateur d'afficher les sous-armes et leurs autorisations pour le serveur.",
			User_Create_Option_Description_7: "Permets à un utilisateur de modifier d'autres sous-consommateurs.",
			User_Create_Option_Description_8: "Permets à un utilisateur de supprimer un sous-câble du serveur.",
			User_Create_Option_Description_9: "Permets à un utilisateur de créer des fichiers et des dossiers supplémentaires via le panneau ou le téléchargement direct.",
			User_Create_Option_Description_10: "Permets à un utilisateur de visualiser le contenu d'un répertoire, mais de ne pas afficher le contenu ou les fichiers de téléchargement.",
			User_Create_Option_Description_11: "Permets à un utilisateur de visualiser le contenu d'un fichier donné.Cela permettra également à l'utilisateur de télécharger des fichiers.",
			User_Create_Option_Description_12: "Permets à un utilisateur de mettre à jour le contenu d'un fichier ou d'un répertoire existant.",
			User_Create_Option_Description_13: "Permets à un utilisateur de supprimer des fichiers ou des répertoires.",
			User_Create_Option_Description_14: "Permets à un utilisateur d'archiver le contenu d'un répertoire et de décompresser des archives existantes sur le système.",
			User_Create_Option_Description_15: "Permets à un utilisateur de se connecter à SFTP et de gérer les fichiers du serveur à l'aide des autres autorisations de fichier attribuées.",
			User_Create_Option_Description_16: "Permets à un utilisateur de créer de nouvelles sauvegardes pour ce serveur.",
			User_Create_Option_Description_17: "Permets à un utilisateur de voir toutes les sauvegardes existantes pour ce serveur.",
			User_Create_Option_Description_18: "Permets à un utilisateur de supprimer des sauvegardes du système.",
			User_Create_Option_Description_19: "Permets à un utilisateur de télécharger une sauvegarde pour le serveur. DANGER: Cela permet à un utilisateur d'accéder à tous les fichiers du serveur dans la sauvegarde.",
			User_Create_Option_Description_20: "Permets à un utilisateur de restaurer une sauvegarde pour le serveur. DANGER: Cela permet à l'utilisateur de supprimer tous les fichiers du serveur dans le processus.",
			User_Create_Option_Description_21: "Permets à un utilisateur de voir toutes les allocations actuellement affectées à ce serveur.Les utilisateurs ayant un niveau d'accès à ce serveur peuvent toujours afficher l'allocation primaire.",
			User_Create_Option_Description_22: "Permets à un utilisateur d'attribuer des allocations supplémentaires au serveur.",
			User_Create_Option_Description_23: "Permets à un utilisateur de modifier l'allocation de serveur principale et de joindre des notes à chaque allocation.",
			User_Create_Option_Description_24: "Permets à un utilisateur de supprimer une allocation à partir du serveur.",
			User_Create_Option_Description_25: "Permets à un utilisateur de visualiser les variables de démarrage pour un serveur.",
			User_Create_Option_Description_26: "Permets à un utilisateur de modifier les variables de démarrage du serveur.",
			User_Create_Option_Description_27: "Permets à un utilisateur de modifier l'image de Docker utilisée lors de l'exécution du serveur.",
			User_Create_Option_Description_28: "Permets à un utilisateur de créer une nouvelle base de données pour ce serveur.",
			User_Create_Option_Description_29: "Permets à un utilisateur de voir la base de données associée à ce serveur.",
			User_Create_Option_Description_30: "Permets à un utilisateur de faire pivoter le mot de passe sur une instance de base de données.Si l'utilisateur n'a pas la permission de View_Password, ils ne verront pas le mot de passe mis à jour.",
			User_Create_Option_Description_31: "Permets à un utilisateur de supprimer une instance de base de données de ce serveur.",
			User_Create_Option_Description_32: "Permets à un utilisateur d'afficher le mot de passe associé à une instance de base de données pour ce serveur.",
			User_Create_Option_Description_33: "Permets à un utilisateur de créer de nouvelles planifications pour ce serveur.",
			User_Create_Option_Description_34: "Permets à un utilisateur de voir les horaires et les tâches associées à eux pour ce serveur.",
			User_Create_Option_Description_35: "Permets à un utilisateur de mettre à jour, les horaires et les tâches de planification de ce serveur.",
			User_Create_Option_Description_36: "Permets à un utilisateur de supprimer les horaires de ce serveur.",
			User_Create_Option_Description_37: "Permets à un utilisateur de renommer ce serveur.",
			User_Create_Option_Description_38: "Permets à un utilisateur de déclencher une réinstallation de ce serveur."
		},
		Server_Network: {
			Network_Page_Title: "Réseau",
			Network_Alocations_Desc_1: "Vous utilisez actuellement {{data}} de {{limit}} allocations autorisées pour ce serveur.",
			Network_Create_Alocation_Button: "Créer une allocation",
			Network_Hostname: "Nom d'hôte",
			Network_IP_Address: "Adresse IP",
			Network_Port: "port",
			Network_Notes: "Remarques",
			Network_Primary: "Primaire",
			Network_Primary_Button: "Primaire",
			Network_Delete_Title: "Supprimer cette allocation?",
			Network_Delete_Button: "Effacer",
			Network_Delete_Desc_1: "Cette allocation sera immédiatement supprimée de ton serveur. Es-tu sur de vouloir continuer ? ",
			Network_Error_1: "L'allocation automatique du serveur n'est pas activée pour cette instance.",
		},
		Server_Schedules: {
			Task_Page_Title: "Planification",
			Task_Empty_Message: "Il n'y a pas de planifications configurées pour ce serveur.",
			Task_Create_Button: "Créer une planification",
			Task_Edit_Button: "Sauvegarder les modifications",
			Task_Delete_Title: "Supprimer la planification ?",
			Task_Delete_Button_1: "Oui, supprimer la planification",
			Task_Delete_Desc: "Êtes-vous sûr de vouloir supprimer cette planification ? Toutes les tâches seront supprimées et tout processus de fonctionnement sera résilié.",
			Task_Delete_Button_2: "Effacer",
			Task_Create_Title: "Créer un nouvel horaire",
			Task_Edit_Title: "Édition du calendrier",
			Task_Create_Or_Edit_Title_1: "Nom de l'horaire",
			Task_Create_Or_Edit_Title_2: "Seulement lorsque le serveur est en ligne",
			Task_Create_Or_Edit_Title_3: "Calendrier activé",
			Task_Create_Or_Edit_Desc_1: "Un identifiant lisible humain pour ce calendrier.",
			Task_Create_Or_Edit_Desc_2: "Le système d'horaire prend en charge l'utilisation de la syntaxe Cronjob lors de la définition lorsque des tâches devraient commencer à fonctionner.Utilisez les champs ci-dessus pour spécifier lorsque ces tâches devraient commencer à exécuter.",
			Task_Create_Or_Edit_Desc_3: "Seulement exécuter ce calendrier lorsque le serveur est dans un état d'exécution.",
			Task_Create_Or_Edit_Desc_4: "Cet horaire sera exécuté automatiquement s'il est activé.",
			Task_Create_Or_Edit_Minute: "minute",
			Task_Create_Or_Edit_Hour: "Heure",
			Task_Create_Or_Edit_Day_Of_Month: "Jour du mois",
			Task_Create_Or_Edit_Month: "Mois",
			Task_Create_Or_Edit_Day_Of_Week: "Jour de la semaine",
			Task_New_Task_Button: "Nouvelle tâche",
			Task_Run_Task_Button: "Cours maintenant",
			Task_Cron_Row_Minute: "minute",
			Task_Cron_Row_Hour: "Heure",
			Task_Cron_Row_Day_Month: "Jour mois)",
			Task_Cron_Row_Month: "Mois",
			Task_Cron_Row_Day_Week: "Jour de semaine)",
			Task_Task_Page_Title: "Tâches",
			Task_Task_Processing: "Traitement",
			Task_Task_Last_Run: "Dernière course à:",
			Task_Task_Next_Run: "Prochaine course à:",
			Task_Task_Never: "Jamais",
			Task_Task_NA: "n/a",
			Task_Task_Edit_Button: "Éditer",
			Task_Task_Active: "active",
			Task_Task_Inactive: "inactive",
			Task_Task_Delete_Title: "Confirmer la suppression de la tâche",
			Task_Task_Delete_Button: "Supprimer la tâche",
			Task_Task_Delete_Desc: "Êtes-vous sûr de vouloir supprimer cette tâche?Cette action ne peut pas être annulée.",
			Task_Task_Files_And_Folders_Message: "Ignorer les fichiers et les dossiers:",
			Task_Task_Continue_Message: "Continue sur l'échec",
			Task_Task_Time_Message: "{{time}}s ultérieurement",
			Task_Task_Edit_Title: "Tâche d'édition",
			Task_Task_Create_Title: "Créer une tâche",
			Task_Task_Create_Or_Edit_Command: "Commandement",
			Task_Task_Create_Or_Edit_Power: "Envoyer une action puissante",
			Task_Task_Create_Or_Edit_Backup: "Créer une sauvegarde",
			Task_Task_Create_Or_Edit_Title_1: "Délai de compensation (en secondes)",
			Task_Task_Create_Or_Edit_Title_2: "Charge utile",
			Task_Task_Create_Or_Edit_Title_3: "Fichiers ignorés",
			Task_Task_Create_Or_Edit_Title_4: "Continuer sur l'échec",
			Task_Task_Create_Or_Edit_Title_5: "action",
			Task_Task_Create_Or_Edit_Desc_1: "La durée d'attente après la tâche précédente exécute avant d'exécuter celui-ci.S'il s'agit de la première tâche sur une planification, cela ne sera pas appliqué.",
			Task_Task_Create_Or_Edit_Desc_2: "Optionnel.Inclure les fichiers et les dossiers à exclure dans cette sauvegarde.Par défaut, le contenu de votre fichier .pterOignore sera utilisé.Si vous avez atteint votre limite de sauvegarde, la sauvegarde la plus ancienne sera tournée.",
			Task_Task_Create_Or_Edit_Desc_3: "Les tâches futures seront exécutées lorsque cette tâche échoue.",
			Task_Task_Create_Or_Edit_Option_1: "Démarrer le serveur",
			Task_Task_Create_Or_Edit_Option_2: "Redémarrez le serveur",
			Task_Task_Create_Or_Edit_Option_3: "Arrêter le serveur",
			Task_Task_Create_Or_Edit_Option_4: "Terminer le serveur",
			Task_Task_Create_Or_Edit_Error_1: "Une charge utile de tâche doit être fournie.",
			Task_Task_Create_Or_Edit_Error_2: "Le décalage de temps doit être un nombre valide entre 0 et 900.",
			Task_Task_Create_Or_Edit_Error_3: "Une valeur de compensation de temps doit être fournie.",
			Task_Task_Create_Or_Edit_Error_4: "Le décalage de temps doit être au moins 0 seconde.",
			Task_Task_Create_Or_Edit_Error_5: "Le décalage de temps doit être inférieur à 900 secondes.",
			Task_Task_Create_Or_Edit_Error_6: "Une tâche de sauvegarde ne peut pas être créée lorsque la limite de sauvegarde du serveur est définie sur 0."
		},
		Server_Settings: {
			Settings_Page_Title: "Paramètres",
			Settings_SFTP_Title_1: "Détails SFTP",
			Settings_SFTP_Title_2: "Adresse du serveur",
			Settings_SFTP_Title_3: "Nom d'utilisateur",
			Settings_SFTP_Desc_1: "Votre mot de passe SFTP est identique au mot de passe de votre compte.",
			Settings_SFTP_Button: "Lancer la connexion SFTP",
			Settings_Debug_Title_1: "Informations de débogage",
			Settings_Debug_Title_2: "Nœud",
			Settings_Debug_Title_3: "ID de serveur",
			Settings_Reinstall_Title_1: "Réinstaller le serveur",
			Settings_Reinstall_Title_2: "Confirmer la réinstallation du serveur",
			Settings_Reinstall_Button: "Oui, réinstaller le serveur",
			Settings_Reinstall_Desc_1: "Votre serveur sera arrêté et certains fichiers peuvent être supprimés ou modifiés au cours de ce processus, êtes-vous sûr que vous souhaitez continuer ?",
			Settings_Reinstall_Desc_2: "La réinstallation arrêtera votre serveur, puis le script d'installation sera exécuté.",
			Settings_Reinstall_Desc_3: "Certains fichiers peuvent être supprimés ou modifiés au cours de ce processus, veuillez sauvegarder vos données avant de continuer.",
			Settings_Reinstall_Success: "Votre serveur a commencé le processus de réinstallation.",
			Settings_Reinstall_Error: "Impossible d'établir une connexion à la machine exécutant ce serveur. Veuillez réessayer.",
			Settings_Rename_Server_Title_1: "Changer le nom du serveur",
			Settings_Rename_Server_Title_2: "Nom du serveur",
			Settings_Rename_Server_Button: "sauvegarder",
			Settings_Rename_Required: "Le nom est un champ obligatoire"
		},
		Server_Startup: {
			Startup_Page_Title: "Paramètres de démarrage",
			Startup_Command_Title_1: "Commande de démarrage",
			Startup_Docker_Title: "Docker image",
			Startup_Docker_Desc: "Il s'agit d'une fonctionnalité avancée vous permettant de sélectionner une image Docker à utiliser lors de l'exécution de cette instance de serveur.",
			Startup_Docker_Error: "L'image Docker de cette serveur a été définie manuellement par un administrateur et ne peut pas être modifiée par l'intermédiaire de cette interface utilisateur.",
			Startup_Variables_Title: "variables",
			Startup_Variables_Read: "Lecture seulement",
			Startup_Server_Error_Title: "Oups!",
		},
		Server_Features: {
			Features_Invalid_Java_Title_1: "Version Java non valide, mise à jour de l'image Docker?",
			Features_Invalid_Java_Desc_1: "Ce serveur est incapable de démarrer en raison de la version Java requise.",
			Features_Invalid_Java_Desc_2: "En appuyant sur 'Mettre à jour l'image Docker' ci-dessous, vous reconnaissez que l'image Docker utilisée sur ce serveur sera remplacé avec une nouvelle version de Java",
			Features_Invalid_Java_Desc_3: "Veuillez sélectionner une version de Java dans la liste ci-dessous.",
			Features_Invalid_Java_Button_1: "Mise à jour de l'image Docker",
			Features_Invalid_Java_Button_2: "Annuler",
			Features_Accept_Eula_Title: "Accepter Minecraft® CLUF",
			Features_Accept_Eula_Desc_1: "En appuyant sur 'J'accepte' ci-dessous, vous indiquez votre accord à la",
			Features_Accept_Eula_Desc_2: "Minecraft® CLUF",
			Features_Accept_Eula_Button_1: "J'accepte",
			Features_Accept_Eula_Button_2: "Annuler",
			Features_Invalid_GSL_Title: "Jeton GSL invalide!",
			Features_Invalid_GSL_Desc_1: "Il semble que votre jeton de connexion au serveur de jeux (jeton GSL) ne soit pas valide ou ait expiré.",
			Features_Invalid_GSL_Desc_2: "Vous pouvez soit en générer un nouveau et le saisir ci-dessous, soit laisser le champ vide pour le supprimer complètement.",
			Features_Invalid_GSL_Desc_3: "Jeton GSL",
			Features_Invalid_GSL_Desc_4: "Visitez https://steamcommunity.com/dev/managegameservers pour générer un jeton.",
			Features_Invalid_GSL_Button: "Mettre à jour le jeton GSL",
			Features_Invalid_PID_Title_1: "Limite de mémoire ou de processus atteinte...",
			Features_Invalid_PID_Title_2: "Limite de ressources possible atteinte...",
			Features_Invalid_PID_Desc_1: "Ce serveur a atteint la limite maximale de processus ou de mémoire.",
			Features_Invalid_PID_Desc_2: "Augmentation de",
			Features_Invalid_PID_Desc_3: "dans la configuration des ailes,",
			Features_Invalid_PID_Desc_4: ", pourrait aider à résoudre ce problème.",
			Features_Invalid_PID_Desc_5: "Note : Wings doit être redémarré pour que les modifications du fichier de configuration prennent effet.",
			Features_Invalid_PID_Desc_6: "Ce serveur tente d'utiliser plus de ressources que celles qui lui sont allouées. Veuillez contacter l'administrateur et lui communiquer l'erreur ci-dessous.",
			Features_Invalid_PID_Desc_7: "pthread_create a échoué, probablement en raison d'un manque de mémoire ou de limites de processus/ressources atteintes.",
			Features_Invalid_Disk_Title: "Plus d'espace disque disponible...",
			Features_Invalid_Disk_Desc_1: "Ce serveur a épuisé l'espace disque disponible et ne peut pas terminer le processus d'installation ou de mise à jour.",
			Features_Invalid_Disk_Desc_2: "Assurez-vous que la machine dispose de suffisamment d'espace disque en tapant",
			Features_Invalid_Disk_Desc_3: "sur la machine qui héberge ce serveur. Supprimez des fichiers ou augmentez l'espace disque disponible pour résoudre le problème.",
			Features_Invalid_Disk_Desc_4: "Ce serveur a épuisé l'espace disque disponible et ne peut pas terminer le processus d'installation ou de mise à jour. Veuillez prendre contact avec le ou les administrateurs et les informer des problèmes d'espace disque.",
		},
		Server_States: {
			Server_Installing_Title: "Exécution d'installateur",
			Server_Installing_Desc: "Votre serveur doit être prêt bientôt, veuillez réessayer dans quelques minutes.",
			Server_Suspended_Title: "Server suspendu",
			Server_Suspended_Desc: "Ce serveur est suspendu et n'est pas accessible.",
			Server_Transferring_Title: "Transfert",
			Server_Transferring_Desc: "Votre serveur est transféré sur un nouveau nœud, veuillez vérifier plus tard.",
			Server_Restoring_Title: "Restauration de la sauvegarde",
			Server_Restoring_Desc: "Votre serveur est actuellement restauré à partir d'une sauvegarde, veuillez vérifier dans quelques minutes."
		},
		Page_Titles: {
			Title_Console: "console",
			Title_File_Manager: "Gestionnaire de fichiers",
			Title_Databases: "Bases de données",
			Title_Schedules: "Des horaires",
			Title_Users: "Utilisatrices",
			Title_Backups: "Sauvegarde",
			Title_Network: "Réseau",
			Title_Startup: "Commencez",
			Title_Settings: "Paramètres",
			Title_API_Credentials: "CIDÉRALES API"
		},
		Errors: {
			Error_Key_Undefined: "Erreur interne: la clé de ce message n'a pas été définie, contactez l'auteur: Ferks#7575",
			Error_Server_Title: "Quelque chose a mal tourné",
			Error_Server_Desc: "La ressource demandée n'a pas été trouvée.",
			Error_Connection: "Une erreur s'est produite lors de la communication avec la machine qui exécute ce serveur. Cette erreur a été enregistrée, veuillez réessayer.",
			Error_Network: "Erreur de réseau",
			Error_Permission_Title: "Accès refusé",
			Error_Permission_Desc: "Vous n'avez pas la permission d'accéder à cette page.",
			Error_Variables_1: "Le champ de valeur est requis.",
			Error_Variables_2: "La valeur doit être 1 chiffre.",
			Error_Variables_3: "Cette valeur n'est pas valide.",
			Error_Variables_4: "La valeur doit être d'au moins 1.",
			Error_Variables_5: "Cette valeur est supérieure à la limite.",
			Error_Variables_6: "Le format de valeur n'est pas valide.",
			Error_Variables_7: "La valeur ne peut contenir que des lettres, des chiffres et des tirets."
		},
		System_Translation: {
			System_Change_Language_Title: "Configurer la Langue",
			System_Change_Language_Desc: "Sélectionner la langue d'affichage de votre compte"
		}
	}
}
