export default {
    translation: {
      Login: {
        Title: "Anmelden um fortzufahren",
        Username_or_Email: "Benutzname oder Passwort",
        Password: "Passwort",
        Login_Button: "Login",
        Forgot_Password: "Passwort vergessen?",
        Username_or_Email_Desc: "Es muss ein Benutzername oder eine E-Mail angegeben werden.",
        Account_Password_Desc: "Bitte geben Sie Ihr Account-Passwort ein.",
        Account_Incorrect: "Es konnte kein Konto gefunden werden, das diesen Anmeldedaten entspricht.",
        Many_Attempts: "Es wurden zu viele Anmeldeversuche unternommen. Bitte versuchen Sie es später erneut.",
        Recaptcha_Error: "Die reCAPTCHA-Daten konnten nicht validiert werden.",
        Request_Failed: "Anfrage fehlgeschlagen mit Statuscode 404",
        CSRF_Token: "CSRF-Token stimmt nicht überein."
      },
    Reset_Password: {
       Password_Reset: "Passwort-Reset anfordern",
        Email: "Email",
        New_Password_Required: "Ein neues Passwort ist erforderlich.",
        Password_Characters_Min: "Ihr neues Passwort sollte mindestens 8 Zeichen lang sein.",
        Password_Not_Match: "Ihr neues Passwort stimmt nicht überein.",
        Account_Email: "Geben Sie Ihre Konto-E-Mail-Adresse ein, um Anweisungen zum Zurücksetzen Ihres Passworts zu erhalten.",
        Valid_Email: "Eine gültige E-Mail-Adresse muss angegeben werden, um fortzufahren.",
        Send_Email: "E-Mail senden",
        Return_to_Login: "Zurück zum Login",
        Reset_Password: "Passwort zurücksetzen",
        New_Password: "Neues Passwort",
        New_Password_Desc: "Passwörter müssen mindestens 8 Zeichen lang sein.",
        Confirm_New_Password: "Neues Passwort bestätigen",
        Send_Email_Link: "Wir haben Ihren Link zum Zurücksetzen Ihres Passworts per E-Mail gesendet!"
    },
     Two_Factor_Auth: {
        Device_Checkpoint: "Geräteprüfpunkt",
        Recovery_Code: "Wiederherstellungscode",
        Authentication_Code: "Authentifizierungscode",
        Enter_Two_Factor_Desc_1: "Geben Sie den von Ihrem Gerät generierten Zwei-Faktor-Token ein.",
        Enter_Two_Factor_Desc_2: "Geben Sie einen der Wiederherstellungscodes ein, die beim Einrichten der 2-Faktor-Authentifizierung für dieses Konto generiert wurden, um fortzufahren.",
        Lost_Device: "Ich habe mein Gerät verloren",
        Have_Device: "Ich habe mein Gerät",
        Continue: "Weiter"
      },
      Account_Overview: {
        Two_Factor_Activate_Desc_1: "Sie müssen einen Authentifizierungscode angeben, um fortzufahren.",
        Two_Factor_Activate_Desc_2: "Die Zwei-Faktor-Authentifizierung ist derzeit für Ihr Konto aktiviert.",
        Two_Factor_Activate_Desc_3: "Authentifizierungscode muss 6-stellig sein.",
        Two_Factor_Active_Title: "Zwei-Faktor-Authentifizierung aktiviert",
        Two_Factor_Active_Desc_1: "Die Zwei-Faktor-Authentifizierung wurde für Ihr Konto aktiviert. Sollten Sie den Zugriff auf Ihr Authentifizierungsgerät verlieren, müssen Sie einen der unten angezeigten Codes verwenden, um auf Ihr Konto zuzugreifen.",
        Two_Factor_Active_Desc_2: "Diese Codes werden nicht mehr angezeigt.",
        Two_Factor_Active_Desc_3: "Bitte notieren Sie sie jetzt, indem Sie sie in einem sicheren Repository wie einem Passwort-Manager speichern.",
        Two_Factor_Active_Button: "Schließen",
        Two_Factor_Disabled_Desc: "Sie haben derzeit keine Zwei-Faktor-Authentifizierung für Ihr Konto aktiviert. Klicken Sie auf die Schaltfläche unten, um mit der Konfiguration zu beginnen.",
        Two_Factor_Disable_Desc_1: "Sie müssen Ihr aktuelles Passwort angeben, um fortzufahren.",
        Two_Factor_Disable_Desc_2: "Um die Zwei-Faktor-Authentifizierung zu deaktivieren, müssen Sie Ihr Kontopasswort angeben.",
        Two_Factor_Disable_Title: "Aktuelles Passwort",
        Two_Factor_Disable_Button: "Zwei-Faktor deaktivieren",
        Two_Factor_Setup_Desc_1: "Geben Sie den Code von Ihrem Authentifizierungsgerät ein, nachdem Sie das QR-Bild gescannt haben.",
        Two_Factor_Setup_Desc_2: "Alternativ geben Sie den folgenden Token in Ihre Authenticator-Anwendung ein:",
        Two_Factor_Setup_Button: "Setup",
        Two_Factor_Incorrect_Password: "Das angegebene Passwort war ungültig.",
        Button_Disable: "Deaktivieren",
        Button_Enable: "Aktivieren",
        Create_Api_Desc_Title: "Beschreibung",
        Create_Api_Desc: "Eine Beschreibung dieses API-Schlüssels.",
        Create_Api_Ips_Title: "Erlaubte IPs",
        Create_Api_Ips_Desc: "Leer lassen, damit jede IP-Adresse diesen API-Schlüssel verwenden kann, andernfalls geben Sie jede IP-Adresse in einer neuen Zeile an.",
        Create_Api_Button: "Erstellen",
        Update_Email_Desc_1: "Sie müssen Ihr aktuelles Kontopasswort angeben.",
        Update_Email_Required: "E-Mail ist ein Pflichtfeld",
        Update_Email_Success_Title: "Erfolg",
        Update_Email_Success: "Ihre primäre E-Mail-Adresse wurde aktualisiert.",
        Update_Email_Error_Title: "Fehler",
        Update_Email_Button: "E-Mail aktualisieren",
        Update_Password_Title: "Neues Passwort",
        Update_Password_Desc_1: "Sie müssen Ihr aktuelles Passwort angeben.",
        Update_Password_Desc_2: "Die Passwortbestätigung stimmt nicht mit dem von Ihnen eingegebenen Passwort überein.",
        Update_Password_Desc_3: "Ihr neues Passwort sollte mindestens 8 Zeichen lang und für diese Website eindeutig sein.",
        Update_Password_Required: "Passwort ist ein Pflichtfeld",
        Update_Password_Button: "Passwort aktualisieren",
        Update_Password_Error: "Das angegebene Passwort war für dieses Konto ungültig.",
        Update_Password_Min: "Das Passwort muss mindestens 8 Zeichen lang sein",
        Confirm_Password: "Passwort bestätigen",
        Account_Page_Title: "Kontoübersicht",
        Account_Two_Factor_Required_Title: "2-Faktor erforderlich",
        Account_Two_Factor_Required_Desc: "Ihr Konto muss die Zwei-Faktor-Authentifizierung aktiviert haben, um fortzufahren.",
        Account_Update_Email_Title: "E-Mail-Adresse aktualisieren",
        Account_Setup_Two_Factor_Title: "Zwei Faktor konfigurieren",
        Api_Page_Title: "Konto-API",
        Api_Create_Title: "API-Schlüssel erstellen",
        Api_List_Title: "API-Schlüssel",
        Api_List_Loading: "Wird geladen...",
        Api_List_Empty: "Für dieses Konto existieren keine API-Schlüssel.",
        Api_List_Used_1: "Zuletzt verwendet: ",
        Api_List_Used_2: "Nie",
        Api_Delete_Title: "Schlüssellöschung bestätigen",
        Api_Delete_Button: "Ja, Schlüssel löschen",
        Api_Delete_Desc: "Möchten Sie diesen API-Schlüssel wirklich löschen? Alle Anfragen, die ihn verwenden, werden sofort ungültig und schlagen fehl.",
        Api_Setup_Title: "Ihr API-Schlüssel",
        Api_Setup_Desc: "Der angeforderte API-Schlüssel wird unten angezeigt. Bitte bewahren Sie diesen an einem sicheren Ort auf, er wird nicht mehr angezeigt.",
        Api_Min_Characters: "Beschreibung muss mindestens 4 Zeichen lang sein",
        Api_Setup_Button: "Schließen",
        Api_Ip_Incorrect_1: "IP-Adresse 1 muss eine gültige IP-Adresse sein.",
        Api_Ip_Incorrect_2: "IP-Adresse 2 muss eine gültige IP-Adresse sein.",
        Api_Ip_Incorrect_3: "IP-Adresse 3 muss eine gültige IP-Adresse sein."
      },
      Search: {
        Search_Title: "Suchbegriff",
        Search_Desc_1: "Bitte geben Sie mindestens drei Zeichen ein, um mit der Suche zu beginnen.",
        Search_Desc_2: "Geben Sie einen Servernamen, eine UUID oder eine Zuweisung ein, um mit der Suche zu beginnen."
      },
      Dashboard: {
        Dash_Page_Title: "Dashboard",
        Dash_Show_Server_1: "Server anderer anzeigen",
        Dash_Show_Server_2: "Zeige deine Server an",
        Dash_Show_Server_3: "Es sind keine anderen Server zum Anzeigen vorhanden.",
        Dash_Show_Server_4: "Ihrem Konto sind keine Server zugeordnet."
      },
      Server_Row: {
        Server_Unlimited: "Unbegrenzt",
        Server_Suspended: "Suspendiert",
        Server_Connect_Error: "Verbindungsfehler",
        Server_Transferring: "Übertragen",
        Server_Installing: "Installieren",
        Server_Restoring_Backup: "Backup wiederherstellen",
        Server_Unavailable: "Nicht verfügbar",
        Server_Of: "von"
      },
      Elemente: {
        Elements_Cancel_Button: "Abbrechen",
        Elements_Copy_Text: "In Zwischenablage kopiert.",
        Elements_Error: "Die Anwendung hat beim Rendern dieser Ansicht einen Fehler festgestellt. Versuchen Sie, die Seite zu aktualisieren."
      },
      Server: {
        Server_Page_Title: "Konsole",
        Server_Transfer_Console: "Übertragung ist fehlgeschlagen.",
        Server_Archived_Console: "Server wurde erfolgreich archiviert und versucht, eine Verbindung zum Zielknoten herzustellen..",
        Server_Send_Command: "Geben Sie einen Befehl ein...",
        Server_State_Console: "Server markiert als ",
        Server_State_Starting: "Starten",
        Server_State_Offline: "Offline",
        Server_State_Stopping: "Stoppen",
        Server_State_Running: "Aktiv",
        Server_State_Connect: "Verbindung wird hergestellt...",
        Server_State_Install: "Dieser Server führt derzeit seinen Installationsprozess aus und die meisten Aktionen sind nicht verfügbar.",
        Server_State_Transfer: "Dieser Server wird gerade auf einen anderen Knoten übertragen und alle Aktionen sind nicht verfügbar.",
        Server_Button_Start: "Start",
        Server_Button_Restart: "Neustart",
        Server_Button_Kill: "Hard-Stopp",
        Server_Button_Stop: "Stopp",
        Server_Memory_Graph_Title: "Speichernutzung",
        Server_Cpu_Graph_Title: "CPU-Auslastung",
        Server_Graph_Desc: "Server ist offline.",
        Server_Websocket_Error: "Beim Validieren der für den Websocket bereitgestellten Anmeldeinformationen ist ein Fehler aufgetreten. Bitte aktualisieren Sie die Seite.",
        Server_Connect_Server: "Wir haben Probleme mit der Verbindung zu Ihrem Server, bitte warten Sie..."
      },
      Server_Backup: {
        Backup_Page_Title: "Backups",
        Backup_Empty_1: "Sieht so aus, als hätten wir keine Backups mehr, die du dir zeigen kannst, versuche eine Seite zurückzugehen.",
        Backup_Empty_2: "Es sieht so aus, als ob derzeit keine Backups für diesen Server gespeichert sind.",
        Backup_Forbidden: "Für diesen Server können keine Backups erstellt werden, da das Backup-Limit auf 0 gesetzt ist.",
        Backup_Information: "Für diesen Server wurden Backups erstellt.",
        Backup_Create_Title_1: "Server-Backup erstellen",
        Backup_Create_Title_2: "Backup-Name",
        Backup_Create_Title_3: "Ignorierte Dateien & Verzeichnisse",
        Backup_Create_Title_4: "Gesperrt",
        Backup_Create_Desc_1: "Wenn angegeben, der Name, der verwendet werden soll, um auf dieses Backup zu verweisen.",
        Backup_Create_Desc_2: "Geben Sie die Dateien oder Ordner ein, die beim Erstellen dieses Backups ignoriert werden sollen. Lassen Sie das Feld leer, um den Inhalt der .pteroignore-Datei im Stammverzeichnis des Serververzeichnisses zu verwenden, falls vorhanden. Wildcard-Abgleich von Dateien und Ordnern wird zusätzlich zum Negieren einer Regel unterstützt indem Sie dem Pfad ein Ausrufezeichen voranstellen.",
        Backup_Create_Desc_3: "Verhindert, dass dieses Backup gelöscht wird, bis es explizit entsperrt wird.",
        Backup_Create_Start_Button: "Backup starten",
        Backup_Create_Button: "Backup erstellen",
        Backup_Created_Title: "Dieses Backup entsperren?",
        Backup_Created_Desc_1: "Möchten Sie dieses Backup wirklich entsperren? Es wird nicht mehr vor automatisiertem oder versehentlichem Löschen geschützt.",
        Backup_Created_Button: "Ja, entsperren",
        Backup_Restore_Title: "Dieses Backup wiederherstellen?",
        Backup_Restore_Desc_1: "Dieser Server wird gestoppt, um das Backup wiederherzustellen. Sobald das Backup gestartet wurde, können Sie den Energiestatus des Servers nicht steuern, auf den Dateimanager zugreifen oder zusätzliche Backups erstellen, bis es abgeschlossen ist.",
        Backup_Restore_Desc_2: "Möchten Sie wirklich fortfahren?",
        Backup_Restore_Desc_3: "Entfernen Sie alle Dateien und Ordner, bevor Sie dieses Backup wiederherstellen.",
        Backup_Restore_Button: "Backup wiederherstellen",
        Backup_Delete_Title: "Dieses Backup löschen?",
        Backup_Delete_Desc_1: "Möchten Sie dieses Backup wirklich löschen? Dies ist ein permanenter Vorgang und das Backup kann nach dem Löschen nicht wiederhergestellt werden.",
        Backup_Delete_Button: "Ja, Backup löschen",
        Backup_SubMenu_Download: "Herunterladen",
        Backup_SubMenu_Restore: "Wiederherstellen",
        Backup_SubMenu_Unlock: "Entsperren",
        Backup_SubMenu_Lock: "Sperren",
        Backup_SubMenu_Delete: "Löschen"
      },
      Server_Databases: {
        Database_Page_Title: "Datenbanken",
        Database_Show_Empty: "Anscheinend haben Sie keine Datenbanken.",
        Database_Show_Forbidden: "Für diesen Server können keine Datenbanken erstellt werden.",
        Database_Limit_Desc: "Diesem Server wurden Datenbanken zugewiesen.",
        Database_Create_Title_1: "Neue Datenbank erstellen",
        Database_Create_Title_2: "Datenbankname",
        Database_Create_Title_3: "Verbindungen von",
        Database_Create_Desc_1: "Ein beschreibender Name für Ihre Datenbankinstanz.",
        Database_Create_Desc_2: "Wo Verbindungen erlaubt sein sollen. Verwenden Sie % für Wildcards.",
        Database_Create_Button_1: "Datenbank erstellen",
        Database_Create_Button_2: "Neue Datenbank",
        Database_Create_Error_1: "Bei der Verarbeitung dieser Anfrage ist ein unerwarteter Fehler aufgetreten. Bitte versuchen Sie es erneut.",
        Database_Create_Error_2: "Ein Datenbankname muss angegeben werden.",
        Database_Create_Error_3: "Datenbankname muss mindestens 3 Zeichen lang sein.",
        Database_Create_Error_4: "Datenbankname darf 48 Zeichen nicht überschreiten.",
        Database_Create_Error_5: "Datenbankname sollte nur alphanumerische Zeichen, Unterstriche, Bindestriche und/oder Punkte enthalten.",
        Database_Create_Error_6: "Ein Verbindungswert muss angegeben werden.",
        Database_Create_Error_7: "Eine gültige Verbindungsadresse muss angegeben werden.",
        Database_Delete_Title_1: "Datenbanklöschung bestätigen",
        Database_Delete_Title_2: "Datenbanknamen bestätigen",
        Database_Delete_Title_3: "Details zur Datenbankverbindung",
        Database_Delete_Title_4: "Endpunkt",
        Database_Delete_Title_5: "Verbindungen von",
        Database_Delete_Title_6: "Benutzername",
        Database_Delete_Title_7: "Passwort",
        Database_Delete_Title_8: "JDBC-Verbindungszeichenfolge",
        Database_Rotate_Button: "Passwort rotieren",
        Database_Delete_Desc_1: `Das Löschen einer Datenbank ist eine permanente Aktion und kann nicht rückgängig gemacht werden. Dadurch wird die Datenbank "{{database}}" dauerhaft gelöscht und alle zugehörigen Daten entfernt.`,
        Database_Create_Desc_2: "Geben Sie den Datenbanknamen ein, um das Löschen zu bestätigen.",
        Database_Delete_Button: "Datenbank löschen",
        Database_Delete_Error_1: "Der Datenbankname muss angegeben werden.",
        Database_Delete_Error_2: "Es wurde kein Datenbankhost gefunden, der die Anforderungen für diesen Server erfüllt."
      },
      Server_Files: {
        Files_Page_Title: "Dateimanager",
        Files_Create_Button: "Neue Datei",
        Files_Directory_Empty: "Dieses Verzeichnis scheint leer zu sein.",
        Files_Show_Files_Max: "Dieses Verzeichnis ist zu groß, um im Browser angezeigt zu werden, wodurch die Ausgabe auf die ersten 250 Dateien beschränkt wird.",
        Files_Chmod_Title: "Dateimodus",
        Files_Chmod_Button: "Aktualisieren",
        Files_Delete_File_Or_Directory_Title: "Löschen",
        Files_Delete_File_Or_Directory_Button: "Ja, löschen",
        Files_Delete_File_Or_Directory_Desc: "Das Löschen von Dateien ist ein permanenter Vorgang, Sie können diese Aktion nicht rückgängig machen.",
        Files_Delete_File: "Datei",
        Files_Delete_Directory: "Verzeichnis",
        Files_Delete_Title: "Diese Dateien löschen?",
        Files_Delete_Desc_1: "Möchten Sie {{selected}} Datei(en) wirklich löschen?",
        Files_Delete_Desc_2: "Das Löschen der unten aufgeführten Datei(en) ist ein permanenter Vorgang. Sie können diese Aktion nicht rückgängig machen.",
        Files_Delete_Desc_3: "andere(n)",
        Files_Delete_Button: "Ja, Dateien löschen",
        Files_SubMenu_Rename: "Umbenennen",
        Files_SubMenu_Move: "Verschieben",
        Files_SubMenu_Permissions: "Berechtigungen",
        Files_SubMenu_Copy: "Kopieren",
        Files_SubMenu_Archive: "Archiv",
        Files_SubMenu_Unarchive: "Unarchivieren",
        Files_SubMenu_Download: "Herunterladen",
        Files_SubMenu_Delete: "Löschen",
        Files_Edit_Ptero_Ignore_1: "Du bearbeitest ein",
        Files_Edit_Ptero_Ignore_2: "Datei. Alle hier aufgeführten Dateien oder Verzeichnisse werden von Backups ausgeschlossen. Platzhalter werden durch die Verwendung eines Sternchens unterstützt",
        Files_Edit_Ptero_Ignore_3: "Sie können eine vorherige Regel negieren, indem Sie ein Ausrufezeichen voranstellen",
        Files_Edit_Save_Button: "Inhalt speichern",
        Files_Create_Title: "Dateiname",
        Files_Create_Desc: "Geben Sie den Namen ein, unter dem diese Datei gespeichert werden soll.",
        Files_Create_Error: "Dateiname ist ein Pflichtfeld",
        Files_Create_Button: "Datei erstellen",
        Files_Date_Format: "MMM tun, yyyy h:mma",
        Files_Message_Archiving: "Dateien archivieren...",
        Files_Message_Deleting: "Dateien werden gelöscht...",
        Files_Create_Directory_Title: "Verzeichnisname",
        Files_Create_Directory_Desc_1: "Ein gültiger Verzeichnisname muss angegeben werden.",
        Files_Create_Directory_Desc_2: "Dieses Verzeichnis wird erstellt als",
        Files_Create_Directory_Button: "Verzeichnis erstellen",
        Files_Move_Desc_1: "Geben Sie den neuen Namen und das Verzeichnis dieser Datei oder dieses Ordners relativ zum aktuellen Verzeichnis ein.",
        Files_Move_Desc_2: "Neuer Speicherort:",
        Files_Drag_Desc: "Drag and drop Dateien zum Hochladen.",
        Files_Drag_Button: "Hochladen",
        Files_Error_1: "Ein Name für die Datei ist erforderlich.",
        Files_Error_2: "Auf dem Remote-Host ist ein Fehler aufgetreten: Datei kann nicht verschoben oder umbenannt werden, Ziel existiert bereits.."
      },
      Server_Users: {
        User_Page_Title: "Benutzer",
        User_Sub_Users_Empty: "Anscheinend haben Sie keine Unterbenutzer.",
        User_Create_Title_1: "Neuen Unterbenutzer erstellen",
        User_Create_Title_2: "Benutzer-E-Mail",
        User_Create_Sub_User_Desc_1: "Geben Sie die E-Mail-Adresse des Benutzers ein, den Sie als Unterbenutzer für diesen Server einladen möchten.",
        User_Create_Sub_User_Desc_2: "E-Mail-Adressen dürfen 191 Zeichen nicht überschreiten.",
        User_Create_Sub_User_Desc_3: "Eine gültige E-Mail-Adresse muss angegeben werden.",
        User_Modify_Or_View_Email_Title: "Berechtigungen für {{subuser}}",
        User_Modify_Title: "Ändern",
        User_View_Title: "Ansicht",
        User_Modify_Button: "Speichern",
        User_Create_Button_1: "Benutzer einladen",
        User_Create_Button_2: "Neuer Benutzer",
        User_Create_Sub_User_Desc: "Beim Anlegen oder Ändern anderer Benutzer dürfen nur die Berechtigungen ausgewählt werden, die Ihrem Konto derzeit zugewiesen sind.",
        User_Delete_Title: "Diesen Unterbenutzer löschen?",
        User_Delete_Desc_1: "Sind Sie sicher, dass Sie diesen Unterbenutzer entfernen möchten? Ihnen wird sofort jeglicher Zugriff auf diesen Server entzogen.",
        User_Delete_Button: "Ja, Unterbenutzer entfernen",
        User_Show_2FA: "2FA aktiviert",
        User_Show_Permissions: "Berechtigungen",
        User_Create_Sub_Title_1: "Kontrolle",
        User_Create_Sub_Title_2: "Benutzer",
        User_Create_Sub_Title_3: "Datei",
        User_Create_Sub_Title_4: "Backup",
        User_Create_Sub_Title_5: "Zuordnung",
        User_Create_Sub_Title_6: "Startup",
        User_Create_Sub_Title_7: "Datenbank",
        User_Create_Sub_Title_8: "Zeitplan",
        User_Create_Sub_Title_9: "Einstellungen",
        User_Create_Desc_1: "Berechtigungen, den Zugriff eines Benutzers steuern, den Energiestatus eines Servers zu steuern oder Befehle zu senden.",
        User_Create_Desc_2: "Berechtigungen, den einem Benutzer ermöglichen, andere Unterbenutzer auf einem Server zu verwalten. Sie können niemals ihr eigenes Konto bearbeiten oder Berechtigungen vergeben, die sie selbst nicht haben.",
        User_Create_Desc_3: "Berechtigungen, den Zugriff eines Benutzers steuern, das Dateisystem für diesen Server zu ändern.",
        User_Create_Desc_4: "Berechtigungen, den Zugriff eines Benutzers steuern, Server-Backups zu erstellen und zu verwalten.",
        User_Create_Desc_5: "Berechtigungen, den Zugriff eines Benutzers steuern, die Portzuweisungen für diesen Server zu ändern.",
        User_Create_Desc_6: "Berechtigungen, den Zugriff eines Benutzers steuern, die Startparameter dieses Servers anzuzeigen.",
        User_Create_Desc_7: "Berechtigungen, den Zugriff eines Benutzers auf die Datenbankverwaltung für diesen Server steuern.",
        User_Create_Desc_8: "Berechtigungen, den den eines Benutzers auf die Zeitplanverwaltung für diesen Server steuern.",
        User_Create_Desc_9: "Berechtigungen, den Zugriff eines Benutzers auf die Einstellungen für diesen Server steuern.",
        User_Create_Option_Desc_1: "Konsole",
        User_Create_Option_Desc_2: "Start",
        User_Create_Option_Desc_3: "Stopp",
        User_Create_Option_Desc_4: "Neustart",
        User_Create_Option_Desc_5: "Erstellen",
        User_Create_Option_Desc_6: "Lesen",
        User_Create_Option_Desc_7: "Aktualisieren",
        User_Create_Option_Desc_8: "Löschen",
        User_Create_Option_Desc_9: "Inhalt lesen",
        User_Create_Option_Desc_10: "Archiv",
        User_Create_Option_Desc_11: "SFTP",
        User_Create_Option_Desc_12: "Herunterladen",
        User_Create_Option_Desc_13: "Wiederherstellen",
        User_Create_Option_Desc_14: "Docker-Image",
        User_Create_Option_Desc_15: "Passwort einsehen",
        User_Create_Option_Desc_16: "Umbenennen",
        User_Create_Option_Desc_17: "Neu installieren",
        User_Create_Option_Description_1: "Erlaubt einem Benutzer, Befehle über die Konsole an die Serverinstanz zu senden.",
        User_Create_Option_Description_2: "Erlaubt einem Benutzer, den Server zu starten, wenn er gestoppt ist.",
        User_Create_Option_Description_3: "Erlaubt einem Benutzer, einen Server zu stoppen, wenn er läuft.",
        User_Create_Option_Description_4: "Erlaubt einem Benutzer, einen Serverneustart durchzuführen. Dadurch kann er den Server starten, wenn er offline ist, aber den Server nicht in einen vollständig gestoppten Zustand versetzen.",
        User_Create_Option_Description_5: "Erlaubt einem Benutzer, neue Unterbenutzer für den Server zu erstellen.",
        User_Create_Option_Description_6: "Erlaubt dem Benutzer, Unterbenutzer und deren Berechtigungen für den Server anzuzeigen.",
        User_Create_Option_Description_7: "Erlaubt einem Benutzer, andere Unterbenutzer zu ändern.",
        User_Create_Option_Description_8: "Erlaubt einem Benutzer, einen Unterbenutzer vom Server zu löschen.",
        User_Create_Option_Description_9: "Erlaubt einem Benutzer, zusätzliche Dateien und Ordner über das Panel oder den direkten Upload zu erstellen.",
        User_Create_Option_Description_10: "Erlaubt einem Benutzer, den Inhalt eines Verzeichnisses anzuzeigen, aber nicht den Inhalt von Dateien anzuzeigen oder Dateien herunterzuladen.",
        User_Create_Option_Description_11: "Erlaubt einem Benutzer, den Inhalt einer bestimmten Datei anzuzeigen. Dadurch kann der Benutzer auch Dateien herunterladen.",
        User_Create_Option_Description_12: "Erlaubt einem Benutzer, den Inhalt einer vorhandenen Datei oder eines Verzeichnisses zu aktualisieren.",
        User_Create_Option_Description_13: "Erlaubt einem Benutzer, Dateien oder Verzeichnisse zu löschen.",
        User_Create_Option_Description_14: "Erlaubt einem Benutzer, den Inhalt eines Verzeichnisses zu archivieren sowie vorhandene Archive auf dem System zu dekomprimieren.",
        User_Create_Option_Description_15: "Erlaubt einem Benutzer, sich mit SFTP zu verbinden und Serverdateien mit den anderen zugewiesenen Dateiberechtigungen zu verwalten.",
        User_Create_Option_Description_16: "Erlaubt einem Benutzer, neue Backups für diesen Server zu erstellen.",
        User_Create_Option_Description_17: "Erlaubt einem Benutzer, alle Backups anzuzeigen, die für diesen Server vorhanden sind.",
        User_Create_Option_Description_18: "Erlaubt einem Benutzer, Backups vom System zu entfernen.",
        User_Create_Option_Description_19: "Erlaubt einem Benutzer, ein Backup für den Server herunterzuladen. Gefahr: Dies ermöglicht einem Benutzer, auf alle Dateien für den Server im Backup zuzugreifen.",
        User_Create_Option_Description_20: "Erlaubt einem Benutzer, ein Backup für den Server wiederherzustellen. Gefahr: Dadurch kann der Benutzer alle Serverdateien während des Prozesses löschen.",
        User_Create_Option_Description_21: "Erlaubt einem Benutzer, alle derzeit diesem Server zugewiesenen Zuweisungen anzuzeigen. Benutzer mit jeder Zugriffsebene auf diesen Server können immer die primäre Zuweisung anzeigen.",
        User_Create_Option_Description_22: "Erlaubt einem Benutzer, dem Server zusätzliche Zuweisungen zuzuweisen.",
        User_Create_Option_Description_23: "Erlaubt einem Benutzer, die primäre Serverzuweisung zu ändern und Notizen an jede Zuweisung anzuhängen.",
        User_Create_Option_Description_24: "Erlaubt einem Benutzer, eine Zuordnung vom Server zu löschen.",
        User_Create_Option_Description_25: "Erlaubt einem Benutzer, die Startvariablen für einen Server anzuzeigen.",
        User_Create_Option_Description_26: "Erlaubt einem Benutzer, die Startvariablen für den Server zu ändern.",
        User_Create_Option_Description_27: "Erlaubt einem Benutzer, das beim Ausführen des Servers verwendete Docker-Image zu ändern.",
        User_Create_Option_Description_28: "Erlaubt einem Benutzer eine neue Datenbank für diesen Server zu erstellen.",
        User_Create_Option_Description_29: "Erlaubt einem Benutzer, die mit diesem Server verknüpfte Datenbank anzuzeigen.",
        User_Create_Option_Description_30: "Erlaubt einem Benutzer, das Passwort auf einer Datenbankinstanz zu rotieren. Wenn der Benutzer nicht die Berechtigung view_password hat, wird ihm das aktualisierte Passwort nicht angezeigt.",
        User_Create_Option_Description_31: "Erlaubt einem Benutzer, eine Datenbankinstanz von diesem Server zu entfernen.",
        User_Create_Option_Description_32: "Erlaubt einem Benutzer, das mit einer Datenbankinstanz für diesen Server verknüpfte Passwort anzuzeigen.",
        User_Create_Option_Description_33: "Erlaubt einem Benutzer, neue Zeitpläne für diesen Server zu erstellen.",
        User_Create_Option_Description_34: "Erlaubt einem Benutzer, Zeitpläne und die damit verbundenen Aufgaben für diesen Server anzuzeigen.",
        User_Create_Option_Description_35: "Erlaubt einem Benutzer, Zeitpläne zu aktualisieren und Aufgaben für diesen Server zu planen.",
        User_Create_Option_Description_36: "Erlaubt einem Benutzer, Zeitpläne für diesen Server zu löschen.",
        User_Create_Option_Description_37: "Erlaubt einem Benutzer, diesen Server umzubenennen.",
        User_Create_Option_Description_38: "Erlaubt einem Benutzer, eine Neuinstallation dieses Servers auszulösen."
      },
      Server_Network: {
        Network_Page_Title: "Netzwerk",
        Network_Alocations_Desc_1: "Sie verwenden derzeit {{data}} von {{limit}} zulässigen Zuweisungen für diesen Server.",
        Network_Create_Alocation_Button: "Zuordnung erstellen",
        Netzwerk_Hostname: "Hostname",
        Network_IP_Address: "IP-Adresse",
        Netzwerk_Port: "Port",
        Network_Notes: "Notizen",
        Network_Primary: "Primär",
        Network_Primary_Button: "Primär machen",
        Network_Delete_Title: "Diese Zuordnung entfernen?",
        Network_Delete_Button: "Löschen",
        Network_Delete_Desc_1: "Diese Zuordnung wird sofort von Ihrem Server entfernt. Möchten Sie wirklich fortfahren?",
        Network_Error_1: "Die automatische Serverzuweisung ist für diese Instanz nicht aktiviert.",
      },
      Server_Schedules: {
        Task_Page_Title: "Zeitpläne",
        Task_Empty_Message: "Für diesen Server sind keine Zeitpläne konfiguriert.",
        Task_Create_Button: "Zeitplan erstellen",
        Task_Edit_Button: "Änderungen speichern",
        Task_Delete_Title: "Zeitplan löschen?",
        Task_Delete_Button_1: "Ja, Zeitplan löschen",
        Task_Delete_Desc: "Möchten Sie diesen Zeitplan wirklich löschen? Alle Aufgaben werden entfernt und alle laufenden Prozesse werden beendet.",
        Task_Delete_Button_2: "Löschen",
        Task_Create_Title: "Neuen Zeitplan erstellen",
        Task_Edit_Title: "Zeitplan bearbeiten",
        Task_Create_Or_Edit_Title_1: "Zeitplanname",
        Task_Create_Or_Edit_Title_2: "Nur wenn Server online ist",
        Task_Create_Or_Edit_Title_3: "Zeitplan aktiviert",
        Task_Create_Or_Edit_Desc_1: "Eine menschenlesbare Kennung für diesen Zeitplan.",
        Task_Create_Or_Edit_Desc_2: "Das Zeitplansystem unterstützt die Verwendung der Cronjob-Syntax bei der Definition, wann Aufgaben ausgeführt werden sollen. Verwenden Sie die Felder oben, um anzugeben, wann diese Aufgaben ausgeführt werden sollen.",
        Task_Create_Or_Edit_Desc_3: "Diesen Zeitplan nur ausführen, wenn sich der Server im laufenden Zustand befindet.",
        Task_Create_Or_Edit_Desc_4: "Dieser Zeitplan wird automatisch ausgeführt, wenn er aktiviert ist.",
        Task_Create_Or_Edit_Minute: "Minute",
        Task_Create_Or_Edit_Hour: "Stunde",
        Task_Create_Or_Edit_Day_Of_Month: "Tag des Monats",
        Task_Create_Or_Edit_Month: "Monat",
        Task_Create_Or_Edit_Day_Of_Week: "Wochentag",
        Task_New_Task_Button: "Neue Aufgabe",
        Task_Run_Task_Button: "Jetzt ausführen",
        Task_Cron_Row_Minute: "Minute",
        Task_Cron_Row_Hour: "Stunde",
        Task_Cron_Row_Day_Month: "Tag (Monat)",
        Task_Cron_Row_Month: "Monat",
        Task_Cron_Row_Day_Week: "Tag (Woche)",
        Task_Task_Page_Title: "Aufgaben",
        Task_Task_Processing: "Bearbeitung",
        Task_Task_Last_Run: "Letzte Ausführung um:",
        Task_Task_Next_Run: "Nächster Lauf um:",
        Task_Task_Never: "Nie",
        Task_Task_Date_Format: "MMM do 'at' h:mma",
        Task_Task_NA: "n/a",
        Task_Task_Edit_Button: "Bearbeiten",
        Task_Task_Active: "Aktiv",
        Task_Task_Inactive: "Inaktiv",
        Task_Task_Delete_Title: "Aufgabenlöschung bestätigen",
        Task_Task_Delete_Button: "Aufgabe löschen",
        Task_Task_Delete_Desc: "Möchten Sie diese Aufgabe wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.",
        Task_Task_Files_And_Folders_Message: "Dateien & Ordner ignorieren:",
        Task_Task_Continue_Message: "Fortsetzung bei Fehler",
        Task_Task_Time_Message: "{{time}}s später",
        Task_Task_Edit_Title: "Aufgabe bearbeiten",
        Task_Task_Create_Title: "Aufgabe erstellen",
        Task_Task_Create_Or_Edit_Command: "Befehl senden",
        Task_Task_Create_Or_Edit_Power: "Energieaktion senden",
        Task_Task_Create_Or_Edit_Backup: "Backup erstellen",
        Task_Task_Create_Or_Edit_Title_1: "Zeitversatz (in Sekunden)",
        Task_Task_Create_Or_Edit_Title_2: "Nutzlast",
        Task_Task_Create_Or_Edit_Title_3: "Ignorierte Dateien",
        Task_Task_Create_Or_Edit_Title_4: "Weiter bei Fehler",
        Task_Task_Create_Or_Edit_Title_5: "Aktion",
        Task_Task_Create_Or_Edit_Desc_1: "Die Wartezeit nach der Ausführung der vorherigen Aufgabe, bevor diese ausgeführt wird. Wenn dies die erste Aufgabe in einem Zeitplan ist, wird diese nicht angewendet.",
        Task_Task_Create_Or_Edit_Desc_2: "Optional. Schließen Sie die auszuschließenden Dateien und Ordner in dieses Backup ein. Standardmäßig wird der Inhalt Ihrer .pteroignore-Datei verwendet. Wenn Sie Ihr Backup-Limit erreicht haben, wird das älteste Backup rotiert.",
        Task_Task_Create_Or_Edit_Desc_3: "Zukünftige Aufgaben werden ausgeführt, wenn diese Aufgabe fehlschlägt.",
        Task_Task_Create_Or_Edit_Option_1: "Starte den Server",
        Task_Task_Create_Or_Edit_Option_2: "Server neu starten",
        Task_Task_Create_Or_Edit_Option_3: "Stopp den Server",
        Task_Task_Create_Or_Edit_Option_4: "Beende den Server",
        Task_Task_Create_Or_Edit_Error_1: "Eine Task-Nutzlast muss bereitgestellt werden.",
        Task_Task_Create_Or_Edit_Error_2: "Der Zeitversatz muss eine gültige Zahl zwischen 0 und 900 sein.",
        Task_Task_Create_Or_Edit_Error_3: "Ein Zeitversatzwert muss angegeben werden.",
        Task_Task_Create_Or_Edit_Error_4: "Der Zeitversatz muss mindestens 0 Sekunden betragen.",
        Task_Task_Create_Or_Edit_Error_5: "Der Zeitversatz muss kleiner als 900 Sekunden sein.",
        Task_Task_Create_Or_Edit_Error_6: "Ein Backup-Task kann nicht erstellt werden, wenn das Backup-Limit des Servers auf 0 gesetzt ist."
      },
      Server_Settings: {
        Settings_Page_Title: "Einstellungen",
        Settings_SFTP_Title_1: "SFTP-Details",
        Settings_SFTP_Title_2: "Serveradresse",
        Settings_SFTP_Title_3: "Benutzername",
        Settings_SFTP_Desc_1: "Ihr SFTP-Passwort ist das gleiche wie das Passwort, das Sie für den Zugriff auf dieses Panel verwenden.",
        Settings_SFTP_Button: "SFTP starten",
        Settings_Debug_Title_1: "Debug-Informationen",
        Settings_Debug_Title_2: "Knoten",
        Settings_Debug_Title_3: "Server-ID",
        Settings_Reinstall_Title_1: "Server neu installieren",
        Settings_Reinstall_Title_2: "Server-Neuinstallation bestätigen",
        Settings_Reinstall_Button: "Server neu installieren",
        Settings_Reinstall_Desc_1: "Ihr Server wird gestoppt und einige Dateien können während dieses Vorgangs gelöscht oder geändert werden. Möchten Sie wirklich fortfahren?",
        Settings_Reinstall_Desc_2: "Eine Neuinstallation Ihres Servers wird ihn stoppen und dann das Installationsskript erneut ausführen, das ihn ursprünglich eingerichtet hat.",
        Settings_Reinstall_Desc_3: "Einige Dateien können während dieses Vorgangs gelöscht oder geändert werden. Bitte sichern Sie Ihre Daten, bevor Sie fortfahren.",
        Settings_Reinstall_Success: "Ihr Server hat mit der Neuinstallation begonnen.",
        Settings_Reinstall_Error: "Es konnte keine Verbindung zu dem Host hergestellt werden, auf dem dieser Server ausgeführt wird. Bitte versuchen Sie es erneut.",
        Settings_Rename_Server_Title_1: "Servernamen ändern",
        Settings_Rename_Server_Title_2: "Servername",
        Settings_Rename_Server_Button: "Speichern",
        Settings_Rename_Required: "Name ist ein Pflichtfeld"
      },
      Server_Startup: {
        Startup_Page_Title: "Starteinstellungen",
        Startup_Command_Title_1: "Startbefehl",
        Startup_Docker_Title: "Docker-Image",
        Startup_Docker_Desc: "Dies ist eine erweiterte Funktion, mit der Sie ein Docker-Image auswählen können, das beim Ausführen dieser Serverinstanz verwendet wird.",
        Startup_Docker_Error: "Das Docker-Image dieses Servers wurde manuell von einem Administrator festgelegt und kann nicht über diese Benutzeroberfläche geändert werden.",
        Startup_Variables_Title: "Variablen",
        Startup_Variables_Read: "Nur Lesen",
        Startup_Server_Error_Title: "Ups!",
      },
      Server_Features: {
        Features_Invalid_Java_Title_1: "Ungültige Java-Version, Docker-Image aktualisieren?",
        Features_Invalid_Java_Desc_1: "Dieser Server kann nicht gestartet werden, da die erforderliche Java-Version nicht erfüllt ist.",
        Features_Invalid_Java_Desc_2: `Indem Sie unten auf "Docker-Image aktualisieren" klicken, bestätigen Sie, dass das Docker-Image, das dieser Server verwendet, in ein untenstehendes Image mit der von Ihnen angeforderten Java-Version geändert wird.`,
        Features_Invalid_Java_Desc_3: "Bitte wählen Sie eine Java-Version aus der Liste unten aus.",
        Features_Invalid_Java_Button_1: "Docker-Image aktualisieren",
        Features_Invalid_Java_Button_2: "Abbrechen",
        Features_Accept_Eula_Title: "Minecraft® EULA akzeptieren",
        Features_Accept_Eula_Desc_1: `Indem Sie unten auf "Ich akzeptiere" drücken, erklären Sie sich damit einverstanden`,
        Features_Accept_Eula_Desc_2: "Minecraft® EULA",
        Features_Accept_Eula_Button_1: "Ich akzeptiere",
        Features_Accept_Eula_Button_2: "Abbrechen",
      },
      Server_States: {
        Server_Installing_Title: "Installation wird ausgeführt. Bitte warten",
        Server_Installing_Desc: "Ihr Server sollte bald bereit sein, bitte versuchen Sie es in ein paar Minuten noch einmal.",
        Server_Suspended_Title: "Server angehalten",
        Server_Suspended_Desc: "Dieser Server ist ausgesetzt und kann nicht aufgerufen werden.",
        Server_Transferring_Title: "Transfer",
        Server_Transferring_Desc: "Ihr Server wird auf einen neuen Knoten transferiert, bitte schauen Sie später noch einmal vorbei.",
        Server_Restoring_Title: "Wiederherstellung aus Backup",
        Server_Restoring_Desc: "Ihr Server wird derzeit aus einem Backup wiederhergestellt, bitte schauen Sie in ein paar Minuten noch einmal vorbei."
      },
      Page_Titles: {
        Title_Console: "Konsole",
        Title_File_Manager: "Dateimanager",
        Title_Databases: "Datenbanken",
        Title_Schedules: "Zeitpläne",
        Title_Users: "Benutzer",
        Title_Backups: "Backups",
        Title_Network: "Netzwerk",
        Title_Startup: "Start",
        Title_Settings: "Einstellungen",
        Title_API_Credentials: "API-Anmeldeinformationen"
      },
      Errors: {
        Error_Key_Undefined: "Interner Fehler: Der Schlüssel für diese Nachricht wurde nicht gesetzt, kontaktieren Sie den Autor: Discord Ferks#7575",
        Error_Server_Title: "Etwas ist schief gelaufen",
        Error_Server_Desc: "Die angeforderte Ressource wurde nicht gefunden.",
        Error_Permission_Title: "Zugriff verweigert",
        Error_Permission_Desc: "Sie haben keine Berechtigung zum Zugriff auf diese Seite.",
        Error_Variables_1: "Das Wertefeld ist erforderlich.",
        Error_Variables_2: "Der Wert muss 1-stellig sein.",
        Error_Variables_3: "Dieser Wert ist ungültig.",
        Error_Variables_4: "Der Wert muss mindestens 1 sein",
        Error_Variables_5: "Dieser Wert ist größer als der Grenzwert.",
        Error_Variables_6: "Das Werteformat ist ungültig.",
        Error_Variables_7: "Der Wert darf nur Buchstaben, Zahlen und Bindestriche enthalten."
      },
    }
  }
