export default {
    translation: {
      Login: {
        Title: "Zaloguj się, by kontynuować",
        Username_or_Email: "Nazwa użytkownika lub e-mail",
        Password: "Hasło",
        Login_Button: "Zaloguj",
        Forgot_Password: "Zapomniałeś hasła?",
        Username_or_Email_Desc: "Należy podać nazwę użytkownika lub adres e-mail.",
        Account_Password_Desc: "Proszę wprowadzić hasło.",
        Account_Incorrect: "Nie znaleziono konta pasującego do tych danych.",
        Many_Attempts: "W ostatnim czasie nastąpiło zbyt wiele prób logowania. Spróbuj ponownie później.",
        Recaptcha_Error: "Błąd uwierzytelniania reCAPTCHA.",
        Request_Failed: "Żądanie nie powiodło się (kod 404)",
        CSRF_Token: "Niedopasowanie tokenu CSRF."
      },
      Reset_Password: {
        Password_Reset: "Zmiana hasła",
        Email: "E-mail",
        New_Password_Required: "Wymagane jest nowe hasło.",
        Password_Characters_Min: "Twoje hasło powinno zawierać powyżej 7 znaków.",
        Password_Not_Match: "Twoje nowe hasło się nie zgadza.",
        Account_Email: "Podaj swój adres e-mail, by otrzymać wskazówki dotyczące resetowania hasła.",
        Valid_Email: "Musisz podać poprawny adres e-mail.",
        Send_Email: "Wyślij wiadomość e-mail",
        Return_to_Login: "Powrót do logowania",
        Reset_Password: "Resetuj hasło",
        New_Password: "Nowe hasło",
        New_Password_Desc: "Twoje hasło powinno zawierać powyżej 7 znaków.",
        Confirm_New_Password: "Powtórz nowe hasło",
        Send_Email_Link: "Wysłaliśmy ci wiadomość e-mail!"
      },
      Two_Factor_Auth: {
        Device_Checkpoint: "Weryfikacja dwuetapowa",
        Recovery_Code: "Kod odzyskiwania hasła",
        Authentication_Code: "Kod weryfikacyjny",
        Enter_Two_Factor_Desc_1: "Wpisz kod weryfikacyjny, wygenerowany przez Twoje urządzenie.",
        Enter_Two_Factor_Desc_2: "Wpisz jeden z kodów odzyskiwania hasła.",
        Lost_Device: "Zgubiłem swoje urządzenie",
        Have_Device: "Posiadam swoje urządzenie",
        Continue: "Kontynuuj"
      },
      Account_Overview: {
        Two_Factor_Activate_Desc_1: "Aby kontynuować, musisz podać kod weryfikacyjny.",
        Two_Factor_Activate_Desc_2: "Weryfikacja dwuetapowa jest obecnie włączona dla Twojego konta.",
        Two_Factor_Activate_Desc_3: "Kod weryfikacyjny musi mieć 6 znaków.",
        Two_Factor_Active_Title: "Weryfikacja dwuetapowa została włączona",
        Two_Factor_Active_Desc_1: "Weryfikacja dwuetapowa została włączona dla Twojego konta. Jeśli zgubisz swoje urządzenie, użyj jednego z poniższych kodów odzyskiwania hasła.",
        Two_Factor_Active_Desc_2: "Te kody nie zostaną już więcej wyświetlone. ",
        Two_Factor_Active_Desc_3: "Zapisz je, by nie mieć w przyszłości nieprzyjemnych sytuacji z utratą konta.",
        Two_Factor_Active_Button: "Zamknij",
        Two_Factor_Disabled_Desc: "Weryfikacja dwuetapowa nie jest włączona dla Twojego konta. Użyj przycisku poniżej, by ją skonfigurować.",
        Two_Factor_Disable_Desc_1: "Musisz podać swoje aktualne hasło, by dezaktywować weryfikację dwuetapową.",
        Two_Factor_Disable_Desc_2: "Aby wyłączyć uwierzytelnianie dwuskładnikowe, musisz podać hasło do konta.",
        Two_Factor_Disable_Title: "Aktualne hasło",
        Two_Factor_Disable_Button: "Wyłącz weryfikację dwuetapową",
        Two_Factor_Setup_Desc_1: "Wprowadź kod z urządzenia po zeskanowaniu kodu QR.",
        Two_Factor_Setup_Desc_2: "Jeśli masz problem z kodem QR, wprowadź następujący token do aplikacji uwierzytelniającej:",
        Two_Factor_Setup_Button: "Ustaw",
        Two_Factor_Incorrect_Password: "Podane hasło jest nieprawidłowe.",
        Button_Disable: "Wyłącz",
        Button_Enable: "Włącz",
        Create_Api_Desc_Title: "Opis",
        Create_Api_Desc: "Opis klucza API.",
        Create_Api_Ips_Title: "Autoryzowane adresy IP",
        Create_Api_Ips_Desc: "Pozostaw puste, aby zezwolić dowolnemu adresowi IP na użycie tego klucza API, w przeciwnym razie podaj każdy adres IP w nowej linijce.",
        Create_Api_Button: "Utwórz",
        Update_Email_Desc_1: "Musisz wprowadzić aktualne hasło do konta.",
        Update_Email_Required: "Adres e-mail jest wymagany",
        Update_Email_Success_Title: "Powodzenie",
        Update_Email_Success: "Twój adres email został zmieniony.",
        Update_Email_Error_Title: "Błąd",
        Update_Email_Button: "Zaktualizuj adres e-mail",
        Update_Password_Title: "Nowe hasło",
        Update_Password_Desc_1: "Musisz podać aktualne hasło do konta.",
        Update_Password_Desc_2: "Nowe hasło nie może być takie samo, jak aktualne.",
        Update_Password_Desc_3: "Twoje hasło powinno mieć więcej, niż 7 znaków.",
        Update_Password_Required: "Musisz podać hasło",
        Update_Password_Button: "Zmień adres e-mail",
        Update_Password_Error: "Nieprawidłowe hasło do konta.",
        Update_Password_Min: "Hasło musi mieć więcej, niż 7 znaków",
        Confirm_Password: "Zatwierdź hasło",
        Account_Page_Title: "Przegląd konta",
        Account_Two_Factor_Required_Title: "Weryfikacja dwuetapowa",
        Account_Two_Factor_Required_Desc: "Your account must have two-factor authentication enabled in order to continue.",
        Account_Update_Email_Title: "Update Email Address",
        Account_Setup_Two_Factor_Title: "Configure Two Factor",
        Api_Page_Title: "Account API",
        Api_Create_Title: "Create API Key",
        Api_List_Title: "API Keys",
        Api_List_Loading: "Loading...",
        Api_List_Empty: "No API keys exist for this account.",
        Api_List_Used_1: "Last used: ",
        Api_List_Used_2: "Never",
        Api_Delete_Title: "Confirm key deletion",
        Api_Delete_Button: "Yes, delete key",
        Api_Delete_Desc: "Are you sure you wish to delete this API key? All requests using it will immediately be invalidated and will fail.",
        Api_Setup_Title: "Your API Key",
        Api_Setup_Desc: "The API key you have requested is shown below. Please store this in a safe location, it will not be shown again.",
        Api_Min_Characters: "Description must be at least 4 characters",
        Api_Setup_Button: "Close",
        Api_Ip_Incorrect_1: "IP address 1 must be a valid IP address.",
        Api_Ip_Incorrect_2: "IP address 2 must be a valid IP address.",
        Api_Ip_Incorrect_3: "IP address 3 must be a valid IP address."
      },
      Search: {
        Search_Title: "Pole wyszukiwania",
        Search_Desc_1: "Proszę wpisać min. 3 znaki, by rozpocząć wyszukiwanie.",
        Search_Desc_2: "Wpisz nazwę serwera, uuid lub allokację, by rozpocząć wyszukiwanie."
      },
      Dashboard: {
        Dash_Page_Title: "Panel",
        Dash_Show_Server_1: "Wyświetlanie serwerów innych użytkowników",
        Dash_Show_Server_2: "Wyświetlanie swoich serwerów",
        Dash_Show_Server_3: "Brak serwerów innych użytkowników do wyświetlenia.",
        Dash_Show_Server_4: "Nie zakupiłeś jeszcze żadnego serwera."
      },
      Server_Row: {
        Server_Unlimited: "Nielimitowane",
        Server_Suspended: "Przedawniony",
        Server_Connect_Error: "Błąd połączenia",
        Server_Transferring: "Transferowanie",
        Server_Installing: "Instalacja",
        Server_Restoring_Backup: "Przywracanie kopii zapasowej",
        Server_Unavailable: "Niedostępne",
        Server_Of: "z"
      },
      Elements: {
        Elements_Cancel_Button: "Anuluj",
        Elements_Copy_Text: "Skopiowano do schowka.",
        Elements_Error: "Aplikacja napotkała błąd podczas renderowania tego widoku. Spróbuj odświeżyć stronę."
      },
      Server: {
        Server_Page_Title: "Konsola",
        Server_Transfer_Console: "Transfer nie powiódł się.",
        Server_Archived_Console: "Serwer został poprawnie zarchiwizowany, próba połączenia z węzłem docelowym..",
        Server_Send_Command: "Wpisz komendę...",
        Server_State_Console: "Serwer oznaczony jako ",
        Server_State_Starting: "uruchamiany",
        Server_State_Offline: "wyłączony",
        Server_State_Stopping: "zatrzymywany",
        Server_State_Running: "uruchomiony",
        Server_State_Connect: "Łączenie...",
        Server_State_Install: "Trwa proces instalacji. Może to potrwać kilka minut.",
        Server_State_Transfer: "Trwa proces transferowania. Może to potrwać kilka minut.",
        Server_Button_Start: "Start",
        Server_Button_Restart: "Restart",
        Server_Button_Kill: "Awaria",
        Server_Button_Stop: "Stop",
        Server_Memory_Graph_Title: "Użycie RAM",
        Server_Cpu_Graph_Title: "Użycie CPU",
        Server_Graph_Desc: "Serwer jest wyłączony.",
        Server_Websocket_Error: "Wystąpił błąd podczas sprawdzania poświadczeń podanych dla gniazda sieciowego. Spróbuj odświeżyć stronę.",
        Server_Connect_Server: "Mamy problemy z połączeniem z Twoim serwerem, proszę czekać..."
      },
      Server_Backup: {
        Backup_Page_Title: "Kopie zapasowe",
        Backup_Empty_1: "Wygląda na to, że zabrakło nam kopii zapasowych, aby to pokazać, spróbuj cofnąć się o stronę.",
        Backup_Empty_2: "Wygląda na to, że nie posiadasz żadnej kopii zapasowej.",
        Backup_Forbidden: "Nie zakupiłeś opcji tworzenia kopii zapasowych.",
        Backup_Information: "kopii zostało utworzonych dla tego serwera.",
        Backup_Create_Title_1: "Utwórz kopię zapasową",
        Backup_Create_Title_2: "Nazwa kopii zapasowej",
        Backup_Create_Title_3: "Ignorowane pliki i foldery",
        Backup_Create_Title_4: "Zablokowane",
        Backup_Create_Desc_1: "Jeśli nazwa kopii została podana, serwer będzie z niej korzystał.",
        Backup_Create_Desc_2: "Wprowadź pliki lub foldery, które chcesz zignorować podczas generowania tej kopii zapasowej. Pozostaw puste, aby użyć zawartości pliku .pteroignore w katalogu głównym katalogu serwera, jeśli jest obecny. Dopasowywanie plików i folderów z symbolami wieloznacznymi jest obsługiwane oprócz negowania reguły przez poprzedzenie ścieżki wykrzyknikiem.",
        Backup_Create_Desc_3: "Uniemożliwia usunięcie tej kopii zapasowej, dopóki nie zostanie odblokowana.",
        Backup_Create_Start_Button: "Rozpocznij przywracanie",
        Backup_Create_Button: "Utwórz kopię",
        Backup_Created_Title: "Odblokować tę kopię?",
        Backup_Created_Desc_1: "Jesteś pewien, że chcesz odblokować tę kopię zapasową? Nie będzie ona dłużej chroniona.",
        Backup_Created_Button: "Tak, odblokuj",
        Backup_Restore_Title: "Przywrócić kopię zapasową?",
        Backup_Restore_Desc_1: "Serwer zostanie wyłączony, a pliki zostaną przywrócone.",
        Backup_Restore_Desc_2: "Jesteś pewien, że chcesz kontynuować?",
        Backup_Restore_Desc_3: "Usuń wszystkie pliki i foldery przed przywróceniem tej kopii zapasowej.",
        Backup_Restore_Button: "Przywróć kopię",
        Backup_Delete_Title: "Usunąć tę kopię zapasową?",
        Backup_Delete_Desc_1: "Usuniętej kopii zapasowej nie można przywrócić.",
        Backup_Delete_Button: "Tak, usuń kopię",
        Backup_SubMenu_Download: "Pobierz",
        Backup_SubMenu_Restore: "Przywróć",
        Backup_SubMenu_Unlock: "Odblokuj",
        Backup_SubMenu_Lock: "Zablokuj",
        Backup_SubMenu_Delete: "Usuń"
      },
      Server_Databases: {
        Database_Page_Title: "Baza danych",
        Database_Show_Empty: "Wygląda na to, że nie masz żadnej bazy danych.",
        Database_Show_Forbidden: "Baza danych nie może zostać utworzona dla tego serwera.",
        Database_Limit_Desc: "baz danych zostało przydzielone do tego serwera.",
        Database_Create_Title_1: "Utwórz bazę danych",
        Database_Create_Title_2: "Nazwa bazy danych",
        Database_Create_Title_3: "Połączenia z",
        Database_Create_Desc_1: "Opisowa nazwa bazy danych Twojego serwera.",
        Database_Create_Desc_2: "Skąd powinny być dozwolone połączenia? Użyj % dla symboli wieloznacznych.",
        Database_Create_Button_1: "Utwórz bazę danych",
        Database_Create_Button_2: "Nowa baza danych",
        Database_Create_Error_1: "Podczas przetwarzania tego żądania wystąpił nieoczekiwany błąd, spróbuj ponownie.",
        Database_Create_Error_2: "Musisz podać nazwę bazy danych.",
        Database_Create_Error_3: "Nazwa bazy danych musi mieć co najmniej 3 znaki .",
        Database_Create_Error_4: "Nazwa bazy danych może mieć maksymalnie 48 znaków.",
        Database_Create_Error_5: "Nazwa bazy danych powinna zawierać tylko znaki alfanumeryczne, podkreślenia, myślniki i kropki.",
        Database_Create_Error_6: "Musisz podać wartość połączeń z bazą danych.",
        Database_Create_Error_7: "Musisz podać prawidłową wartość połączeń z bazą danych.",
        Database_Delete_Title_1: "Potwierdź usunięcie bazy danych",
        Database_Delete_Title_2: "Potwierdź nazwę bazy danych",
        Database_Delete_Title_3: "Szczegóły połączenia z bazą danych",
        Database_Delete_Title_4: "Punkt końcowy",
        Database_Delete_Title_5: "Połączenia z",
        Database_Delete_Title_6: "Nazwa użytkownika",
        Database_Delete_Title_7: "Hasło",
        Database_Delete_Title_8: "Ciąg połączenia JDBC",
        Database_Rotate_Button: "Zmień hasło",
        Database_Delete_Desc_1: `Usuniętej bazy danych nie można przywrócić. Permanentnie usuniesz "{{database}}" i wszystkie powiązane z nią dane.`,
        Database_Create_Desc_2: "Wpisz nazwę bazy danych, by potwierdzić jej usunięcie.",
        Database_Delete_Button: "Usuń bazę danych",
        Database_Delete_Error_1: "Musisz podać nazwę bazy danych.",
        Database_Delete_Error_2: "Nie znaleziono hosta bazy danych spełniającego wymagania dla tego serwera."
      },
      Server_Files: {
        Files_Page_Title: "Menedżer plików",
        Files_Create_Button: "Utwórz plik",
        Files_Directory_Empty: "Wygląda na to, że ten folder jest pusty.",
        Files_Show_Files_Max: "Ten folder jest na tyle duży, że spowodowałby wysypanie się przeglądarki, dlatego wyświetlonych zostaje jedynie 250 pierwszych plików.",
        Files_Chmod_Title: "Tryb pliku",
        Files_Chmod_Button: "Zaktualizuj",
        Files_Delete_File_Or_Directory_Title: "Usuń",
        Files_Delete_File_Or_Directory_Button: "Tak, usuń",
        Files_Delete_File_Or_Directory_Desc: "Usuniętych plików nie można przywrócić.",
        Files_Delete_File: "Plik",
        Files_Delete_Directory: "Folder",
        Files_Delete_Title: "Usunąć te pliki?",
        Files_Delete_Desc_1: "Jesteś pewien, że chcesz usunąć {{selected}} plików?",
        Files_Delete_Desc_2: "Usuniętych plików nie można przywrócić.",
        Files_Delete_Desc_3: "Inne",
        Files_Delete_Button: "Tak, usuń",
        Files_SubMenu_Rename: "Zmień nazwę",
        Files_SubMenu_Move: "Przenieś",
        Files_SubMenu_Permissions: "Uprawnienia",
        Files_SubMenu_Copy: "Kopiuj",
        Files_SubMenu_Archive: "Archiwizuj",
        Files_SubMenu_Unarchive: "Dezarchiwizuj",
        Files_SubMenu_Download: "Pobierz",
        Files_SubMenu_Delete: "Usuń",
        Files_Edit_Ptero_Ignore_1: "Edytujesz ",
        Files_Edit_Ptero_Ignore_2: "plik. Wszystkie wymienione tutaj pliki lub katalogi zostaną wykluczone z kopii zapasowych. Symbole wieloznaczne są obsługiwane za pomocą *",
        Files_Edit_Ptero_Ignore_3: "Możesz zanegować wcześniejszą regułę, dodając wykrzyknik",
        Files_Edit_Save_Button: "Zapisz plik",
        Files_Create_Title: "Nazwa pliku",
        Files_Create_Desc: "Ustaw nazwę, w jakiej plik ma zostać zapisany.",
        Files_Create_Error: "Musisz podać nazwę pliku",
        Files_Create_Button: "Utwórz plik",
        Files_Message_Archiving: "Archiwizacja plików...",
        Files_Message_Deleting: "Usuwanie plików...",
        Files_Create_Directory_Title: "Nazwa folderu",
        Files_Create_Directory_Desc_1: "Musisz podać prawidłową nazwę folderu.",
        Files_Create_Directory_Desc_2: "Ten folder zostanie utworzony jako",
        Files_Create_Directory_Button: "Utwórz folder",
        Files_Move_Desc_1: "Wpisz nową nazwę folderu / pliku.",
        Files_Move_Desc_2: "Nowa lokalizacja:",
        Files_Drag_Desc: "Przeciągnij i upuść pliki, by je przesłać na hosting.",
        Files_Drag_Button: "Wgraj",
        Files_Error_1: "Nazwa pliku jest wymagana.",
        Files_Error_2: "Wystąpił błąd na zdalnym hoście: nie można przenieść lub zmienić nazwy pliku, miejsce docelowe już istnieje.."
      },
      Server_Users: {
        User_Page_Title: "Użytkowincy",
        User_Sub_Users_Empty: "Wygląda na to, że nie dodałeś żadnych użytkowników do serwera.",
        User_Create_Title_1: "Dodaj użytkownika",
        User_Create_Title_2: "Adres e-mail użytkownika",
        User_Create_Sub_User_Desc_1: "Wpisz adres e-mail użytkownika, który utworzył konto w panelu.",
        User_Create_Sub_User_Desc_2: "Adres e-mail nie może przekroczyć 191 znaków.",
        User_Create_Sub_User_Desc_3: "Należy podać prawidłowy adres e-mail.",
        User_Modify_Or_View_Email_Title: "Uprawnienia użytkownika {{subuser}}",
        User_Modify_Title: "Edycja plików",
        User_View_Title: "Podgląd plików",
        User_Modify_Button: "Zapisz",
        User_Create_Button_1: "Dodaj użytkownika",
        User_Create_Button_2: "Nowy użytkownik",
        User_Create_Sub_User_Desc: "Podczas tworzenia lub modyfikowania innych użytkowników można wybrać tylko te uprawnienia, które są aktualnie przypisane do Twojego konta.",
        User_Delete_Title: "Odebrać dostęp temu użytkownikowi?",
        User_Delete_Desc_1: "Jesteś pewien, że chcesz odebrać uprawnienia temu użytkownikowi? Natychmiastowo straci on dostęp do serwera.",
        User_Delete_Button: "Tak, odbierz dostęp",
        User_Show_2FA: "2FA włączone",
        User_Show_Permissions: "Uprawnienia",
        User_Create_Sub_Title_1: "Kontrola",
        User_Create_Sub_Title_2: "Użytkownik",
        User_Create_Sub_Title_3: "Pliki",
        User_Create_Sub_Title_4: "Kopia zapasowa",
        User_Create_Sub_Title_5: "Allokacja",
        User_Create_Sub_Title_6: "Uruchamianie",
        User_Create_Sub_Title_7: "Baza danych",
        User_Create_Sub_Title_8: "Harmonogram",
        User_Create_Sub_Title_9: "Ustawienia",
        User_Create_Desc_1: "Uparwnienie, które pozwala użytkownikowi na korzystanie z konsoli serwera.",
        User_Create_Desc_2: "Uparwnienie, które pozwala użytkownikowi na edycję, usuwanie oraz dodawanie użytkowników do serwera.",
        User_Create_Desc_3: "Uparwnienie, które pozwala użytkownikowi na edycję, dodawanie oraz usuwanie plików.",
        User_Create_Desc_4: "Uparwnienie, które pozwala użytkownikowi na tworzenie, pobieranie, przywracanie i usuwanie kopii zapasowych.",
        User_Create_Desc_5: "Uparwnienie, które pozwala użytkownikowi na modyfikację allokacji serwera.",
        User_Create_Desc_6: "Uparwnienie, które pozwala użytkownikowi na modyfikację uruchamiania serwera.",
        User_Create_Desc_7: "Uparwnienie, które pozwala użytkownikowi na dodawanie, edycję lub usuwanie bazy danych.",
        User_Create_Desc_8: "Uparwnienie, które pozwala użytkownikowi na edycję, tworzenie lub usuwanie harmonogramów.",
        User_Create_Desc_9: "Uparwnienie, które pozwala użytkownikowi na edycję ustawień serwera.",
        User_Create_Option_Desc_1: "Konsola",
        User_Create_Option_Desc_2: "Włączanie serwera",
        User_Create_Option_Desc_3: "Wyłączanie serwera",
        User_Create_Option_Desc_4: "Restartowanie serwera",
        User_Create_Option_Desc_5: "Dodaj użytkownika",
        User_Create_Option_Desc_6: "Przeglądanie użytkowników",
        User_Create_Option_Desc_7: "Edycja użytkowników",
        User_Create_Option_Desc_8: "Usuwanie użytkowników",
        User_Create_Option_Desc_9: "Przeglądanie plików",
        User_Create_Option_Desc_10: "Archiwizacja plików",
        User_Create_Option_Desc_11: "Dostęp do SFTP",
        User_Create_Option_Desc_12: "Pobieranie plików",
        User_Create_Option_Desc_13: "Przywracanie plików",
        User_Create_Option_Desc_14: "Obraz dockera",
        User_Create_Option_Desc_15: "Podgląd hasła",
        User_Create_Option_Desc_16: "Zmiana nazwy serwera",
        User_Create_Option_Desc_17: "Reinstalacja serwera",
        User_Create_Option_Description_1: "Uprawnienie, które pozwala użytkownikowi na wysyłanie poleceń poprzez konsolę.",
        User_Create_Option_Description_2: "Uprawnienie, które pozwala użytkownikowi na uruchamianie serwera.",
        User_Create_Option_Description_3: "Uprawnienie, które pozwala użytkownikowi na zatrzymywanie serwera.",
        User_Create_Option_Description_4: "Uprawnienie, które pozwala użytkownikowi na restartowanie serwera.",
        User_Create_Option_Description_5: "Uprawnienie, które pozwala użytkownikowi na dodawanie użytkowników do serwera.",
        User_Create_Option_Description_6: "Uprawnienie, które pozwala użytkownikowi na wgląd do uprawnień użytkowników.",
        User_Create_Option_Description_7: "Uprawnienie, które pozwala użytkownikowi na modyfikację uprawnień użytkowników.",
        User_Create_Option_Description_8: "Uprawnienie, które pozwala użytkownikowi na usuwanie użytkowników z serwera.",
        User_Create_Option_Description_9: "Uprawnienie, które pozwala użytkownikowi na tworzenie plików i folderów.",
        User_Create_Option_Description_10: "Uprawnienie, które pozwala użytkownikowi na wyświetlanie folderów.",
        User_Create_Option_Description_11: "Uprawnienie, które pozwala użytkownikowi na pobieranie plików.",
        User_Create_Option_Description_12: "Uprawnienie, które pozwala użytkownikowi na edycję plików.",
        User_Create_Option_Description_13: "Uprawnienie, które pozwala użytkownikowi na usuwanie plików.",
        User_Create_Option_Description_14: "Uprawnienie, które pozwala użytkownikowi na archiwizowanie i dezarchiwizowanie plików.",
        User_Create_Option_Description_15: "Uprawnienie, które pozwala użytkownikowi na łączenie się poprzez SFTP.",
        User_Create_Option_Description_16: "Uprawnienie, które pozwala użytkownikowi na tworzenie kopii zapasowych.",
        User_Create_Option_Description_17: "Uprawnienie, które pozwala użytkownikowi na wyświetlanie kopii zapasowych.",
        User_Create_Option_Description_18: "Uprawnienie, które pozwala użytkownikowi na usuwanie kopii zapasowych.",
        User_Create_Option_Description_19: "Uprawnienie, które pozwala użytkownikowi na pobieranie kopii zapasowych.",
        User_Create_Option_Description_20: "Uprawnienie, które pozwala użytkownikowi na przywracanie kopii zapasowych.",
        User_Create_Option_Description_21: "Uprawnienie, które pozwala użytkownikowi na wyświetlanie allokacji serwera.",
        User_Create_Option_Description_22: "Uprawnienie, które pozwala użytkownikowi na edycję allokacji serwera.",
        User_Create_Option_Description_23: "Uprawnienie, które pozwala użytkownikowi na zmianę głównego połączenia allokacyjnego.",
        User_Create_Option_Description_24: "Uprawnienie, które pozwala użytkownikowi na usuwanie wpisów allokacji serwera.",
        User_Create_Option_Description_25: "Uprawnienie, które pozwala użytkownikowi na wyświetlanie opcji uruchamiania.",
        User_Create_Option_Description_26: "Uprawnienie, które pozwala użytkownikowi na edycję opcji uruchamiania.",
        User_Create_Option_Description_27: "Uprawnienie, które pozwala użytkownikowi na edycję obrazu dockera.",
        User_Create_Option_Description_28: "Uprawnienie, które pozwala użytkownikowi na tworzenie baz danych.",
        User_Create_Option_Description_29: "Uprawnienie, które pozwala użytkownikowi na wyświetlanie dostępnych baz danych.",
        User_Create_Option_Description_30: "Uprawnienie, które pozwala użytkownikowi na generowanie nowych haseł do baz danych.",
        User_Create_Option_Description_31: "Uprawnienie, które pozwala użytkownikowi na usuwanie baz danych.",
        User_Create_Option_Description_32: "Uprawnienie, które pozwala użytkownikowi na wyświetlanie haseł baz danych.",
        User_Create_Option_Description_33: "Uprawnienie, które pozwala użytkownikowi na tworzenie harmonogramów.",
        User_Create_Option_Description_34: "Uprawnienie, które pozwala użytkownikowi na wyświetlanie harmonogramów.",
        User_Create_Option_Description_35: "Uprawnienie, które pozwala użytkownikowi na edycję harmonogramów.",
        User_Create_Option_Description_36: "Uprawnienie, które pozwala użytkownikowi na usuwanie harmonogramów.",
        User_Create_Option_Description_37: "Uprawnienie, które pozwala użytkownikowi na zmianę nazwy serwera.",
        User_Create_Option_Description_38: "Uprawnienie, które pozwala użytkownikowi na reinstalację serwera."
      },
      Server_Network: {
        Network_Page_Title: "Sieć",
        Network_Alocations_Desc_1: "Obecnie używasz {{data}} z {{limit}} udostępnionych allokacji dla tego serwera.",
        Network_Create_Alocation_Button: "Utwórz allokację",
        Network_Hostname: "Nazwa hosta",
        Network_IP_Address: "Adres IP",
        Network_Port: "Port",
        Network_Notes: "Notatki",
        Network_Primary: "Główny",
        Network_Primary_Button: "Ustaw jako główny",
        Network_Delete_Title: "Usunąć allokację?",
        Network_Delete_Button: "Usuń",
        Network_Delete_Desc_1: "Ta allokacja zostanie usunięta dla tego serwera. Na pewno chcesz kontynuować?",
        Network_Error_1: "Auto–allokacja nie jest dostępna dla tego serwera.",
      },
      Server_Schedules: {
        Task_Page_Title: "Harmonogram",
        Task_Empty_Message: "Brak skonfigurowanych harmonogramów dla tego serwera.",
        Task_Create_Button: "Utwórz harmonogram",
        Task_Edit_Button: "Zapisz zmiany",
        Task_Delete_Title: "Usunąć harmonogram?",
        Task_Delete_Button_1: "Tak, usuń",
        Task_Delete_Desc: "Jesteś pewien, że chcesz usunąć ten harmonogram? Wszystkie zadania zostaną usunięte, a uruchomione procesy zostaną zakończone.",
        Task_Delete_Button_2: "Usuń",
        Task_Create_Title: "Utwórz nowy harmonogram",
        Task_Edit_Title: "Edytuj harmonogram",
        Task_Create_Or_Edit_Title_1: "Nazwa harmonogramu",
        Task_Create_Or_Edit_Title_2: "Tylko, gdy serwer jest uruchomiony",
        Task_Create_Or_Edit_Title_3: "Harmonogram włączony",
        Task_Create_Or_Edit_Desc_1: "ID harmonogramu jest widoczne dla użytkownika.",
        Task_Create_Or_Edit_Desc_2: "System harmonogramów obsługuje użycie składni Cronjob podczas określania, kiedy zadania powinny zostać uruchomione. Użyj powyższych pól, aby określić, kiedy te zadania mają się rozpocząć.",
        Task_Create_Or_Edit_Desc_3: "Harmonogram może działać jedynie, gdy serwer jest włączony.",
        Task_Create_Or_Edit_Desc_4: "Harmonogram będzie działał automatycznie, jeśli jest włączony.",
        Task_Create_Or_Edit_Minute: "Minuty",
        Task_Create_Or_Edit_Hour: "Godziny",
        Task_Create_Or_Edit_Day_Of_Month: "Dzień miesiąca",
        Task_Create_Or_Edit_Month: "Miesiąc",
        Task_Create_Or_Edit_Day_Of_Week: "Dzień tygodnia",
        Task_New_Task_Button: "Nowe zadanie",
        Task_Run_Task_Button: "Uruchom teraz",
        Task_Cron_Row_Minute: "Minuty",
        Task_Cron_Row_Hour: "Godziny",
        Task_Cron_Row_Day_Month: "Dzień miesiąca",
        Task_Cron_Row_Month: "Miesiąc",
        Task_Cron_Row_Day_Week: "Dzień tygodnia",
        Task_Task_Page_Title: "Zadania",
        Task_Task_Processing: "Przetwarzanie",
        Task_Task_Last_Run: "Ostatnio uruchomione:",
        Task_Task_Next_Run: "Uruchomi się za:",
        Task_Task_Never: "Nigdy",
        Task_Task_NA: "Nie określono",
        Task_Task_Edit_Button: "Edytuj",
        Task_Task_Active: "Aktywne",
        Task_Task_Inactive: "Nieaktywne",
        Task_Task_Delete_Title: "Potwierdź usunięcie zadania",
        Task_Task_Delete_Button: "Usuń zadanie",
        Task_Task_Delete_Desc: "Jesteś pewien, że chcesz usunąć to zadanie? Nie będzie można przywrócić tej akcji.",
        Task_Task_Files_And_Folders_Message: "Ignorowane pliki i foldery:",
        Task_Task_Continue_Message: "Kontynuacja po awarii",
        Task_Task_Time_Message: "{{time}} sekund później",
        Task_Task_Edit_Title: "Edytuj zadanie",
        Task_Task_Create_Title: "Utwórz zadanie",
        Task_Task_Create_Or_Edit_Command: "Wykonaj komendę",
        Task_Task_Create_Or_Edit_Power: "Wykonaj akcję zasilania",
        Task_Task_Create_Or_Edit_Backup: "Utwórz kopię zapasową",
        Task_Task_Create_Or_Edit_Title_1: "Przesunięcie czasowe (w sekundach)",
        Task_Task_Create_Or_Edit_Title_2: "Wstępnie przyjęte",
        Task_Task_Create_Or_Edit_Title_3: "Ignorowane pliki",
        Task_Task_Create_Or_Edit_Title_4: "Kontynuacja po awarii",
        Task_Task_Create_Or_Edit_Title_5: "Akcja",
        Task_Task_Create_Or_Edit_Desc_1: "Czas oczekiwania po wykonaniu poprzedniego zadania przed uruchomieniem tego. Jeśli jest to pierwsze zadanie w harmonogramie, nie zostanie ono zastosowane.",
        Task_Task_Create_Or_Edit_Desc_2: "Uwzględnij w tej kopii zapasowej pliki i foldery, które mają zostać wykluczone. Domyślnie zostanie użyta zawartość twojego pliku .pteroignore. Jeśli osiągnąłeś limit kopii zapasowych, najstarsza kopia zapasowa zostanie podmieniona (opcjonalnie).",
        Task_Task_Create_Or_Edit_Desc_3: "Kolejne zadania zostaną uruchomione, gdy to zadanie się nie powiedzie.",
        Task_Task_Create_Or_Edit_Option_1: "Uruchom serwer",
        Task_Task_Create_Or_Edit_Option_2: "Zrestartuj serwer",
        Task_Task_Create_Or_Edit_Option_3: "Wyłącz serwer",
        Task_Task_Create_Or_Edit_Option_4: "Wyłącz serwer awaryjnie",
        Task_Task_Create_Or_Edit_Error_1: "Należy podać zakres plików.",
        Task_Task_Create_Or_Edit_Error_2: "Czas opóźnienia musi się mieścić w przedziale [0 ; 900].",
        Task_Task_Create_Or_Edit_Error_3: "Należy podać wartość opóźnienia.",
        Task_Task_Create_Or_Edit_Error_4: "Opóźnienie musi być większe od 0 sekund.",
        Task_Task_Create_Or_Edit_Error_5: "Opóźnienie musi być mniejsze od 900 sekund.",
        Task_Task_Create_Or_Edit_Error_6: "Nie można utworzyć kopii zapasowej serwera, jeśli nie masz zakupionego dodatku."
      },
      Server_Settings: {
        Settings_Page_Title: "Ustawienia",
        Settings_SFTP_Title_1: "Detale SFTP",
        Settings_SFTP_Title_2: "Adres serwera",
        Settings_SFTP_Title_3: "Nazwa użytkownika",
        Settings_SFTP_Desc_1: "Twoje hasło SFTP jest takie samo, jak hasło do Twojego konta w panelu.",
        Settings_SFTP_Button: "Uruchom SFTP",
        Settings_Debug_Title_1: "Informacje o debugowaniu",
        Settings_Debug_Title_2: "Węzeł",
        Settings_Debug_Title_3: "ID serwera",
        Settings_Reinstall_Title_1: "Przeinstaluj serwer",
        Settings_Reinstall_Title_2: "Potwierdź reinstalację serwera",
        Settings_Reinstall_Button: "Tak, przeinstaluj serwer",
        Settings_Reinstall_Desc_1: "Twój serwer zostanie zatrzymany, a niektóre jego pliki zostaną zmodyfikowane. Jesteś pewien, że chcesz kontynuować?",
        Settings_Reinstall_Desc_2: "Reinstalacja serwera zostanie ukończona, gdy niektóre pliki zostaną przywrócone do domyślnych.",
        Settings_Reinstall_Desc_3: "Przed przeinstalowaniem serwera zalecane jest utworzenie kopii zapasowej plików.",
        Settings_Reinstall_Success: "Serwer rozpoczął przywracanie podstawowych plików.",
        Settings_Reinstall_Error: "Nie można nawiązać połączenia z hostem, na którym działa ten serwer. Proszę spróbować ponownie.",
        Settings_Rename_Server_Title_1: "Zmień nazwę serwera",
        Settings_Rename_Server_Title_2: "Nazwa serwera",
        Settings_Rename_Server_Button: "Zapisz",
        Settings_Rename_Required: "Musisz podać nazwę serwera"
      },
      Server_Startup: {
        Startup_Page_Title: "Ustawienia uruchamiania",
        Startup_Command_Title_1: "Komenda startowa",
        Startup_Docker_Title: "Obraz dockera",
        Startup_Docker_Desc: "Jest to zaawansowana funkcja, pozwalająca wybrać obraz dockera do użycia podczas uruchamiania tego serwera.",
        Startup_Docker_Error: "Obraz dockera został przypisany przez administratora i nie może być tutaj zmieniony.",
        Startup_Variables_Title: "Zmienne",
        Startup_Variables_Read: "Tylko odczytywanie",
        Startup_Server_Error_Title: "Ups!",
      },
      Server_Features: {
        Features_Invalid_Java_Title_1: "Nieprawidłowa wersja Java. Zainstalować inną?",
        Features_Invalid_Java_Desc_1: "Ten serwer nie może być uruchomiony na tej wersji Java.",
        Features_Invalid_Java_Desc_2: `Klikając "Zaktualizuj obraz dockera" poniżej, potwierdzasz, że obraz dockera używany przez ten serwer zostanie zmieniony na nowy z wybraną wersją Java.`,
        Features_Invalid_Java_Desc_3: "Proszę wybrać wersję Java z poniższej listy.",
        Features_Invalid_Java_Button_1: "Zaktualizuj obraz dockera",
        Features_Invalid_Java_Button_2: "Anuluj",
        Features_Accept_Eula_Title: "Akceptacja Minecraft® EULA",
        Features_Accept_Eula_Desc_1: `Klikając "Akceptuję" poniżej, zgadzasz się z`,
        Features_Accept_Eula_Desc_2: "Minecraft® EULA",
        Features_Accept_Eula_Button_1: "Akceptuję",
        Features_Accept_Eula_Button_2: "Anuluj",
      },
      Server_States: {
        Server_Installing_Title: "Instalacja serwera",
        Server_Installing_Desc: "Twój serwer powinien być wkrótce gotowy, spróbuj ponownie za kilka minut.",
        Server_Suspended_Title: "Serwer przedawniony",
        Server_Suspended_Desc: "Serwer jest przedawniony, nie masz już do niego dostępu.",
        Server_Transferring_Title: "Transfer",
        Server_Transferring_Desc: "Twój serwer został połączony z nowym węzłem. Może to potrwać kilka minut.",
        Server_Restoring_Title: "Przywracanie kopii zapasowej",
        Server_Restoring_Desc: "Przywracasz kopię zapasową serwera. Może to potrwać kilka minut."
      },
      Page_Titles: {
        Title_Console: "Konsola",
        Title_File_Manager: "Menedżer plików",
        Title_Databases: "Baza danych",
        Title_Schedules: "Harmonogramy",
        Title_Users: "Użytkownicy",
        Title_Backups: "Kopie zapasowe",
        Title_Network: "Sieć",
        Title_Startup: "Uruchamianie",
        Title_Settings: "Ustawienia",
        Title_API_Credentials: "Kwalifikacje API"
      },
      Errors: {
        Error_Key_Undefined: "Błąd wewnętrzny: klucz dla tej wiadomości nie został ustawiony, skontaktuj się z autorem: Ferks#7575",
        Error_Server_Title: "Coś poszło nie tak, jak powinno",
        Error_Server_Desc: "Nie odnaleziono żądanego pliku.",
        Error_Connection: "Wystąpił błąd podczas komunikacji z serwerem, na którym działa ten hosting. Ten błąd został zapisany, spróbuj ponownie.",
        Error_Network: "Wystąpił problem z siecią",
        Error_Permission_Title: "Brak uprawnień",
        Error_Permission_Desc: "Nie posiadasz uprawnień, by korzystać z tej strony.",
        Error_Variables_1: "Pole z wartością jest wymagane.",
        Error_Variables_2: "Wartość musi składać się jedynie z jednej cyfry.",
        Error_Variables_3: "Wartość jest nieprawidłowa.",
        Error_Variables_4: "Wartość musi się składać z minimalnie jednego znaku.",
        Error_Variables_5: "Wartość posiada za dużo znaków.",
        Error_Variables_6: "Format wprowadzanej wartości jest nieprawidłowy.",
        Error_Variables_7: "Wartość może składać się jedynie z liter, cyft oraz myślników."
      },
      System_Translation: {
        System_Change_Language_Title: "Konfiguracja języka",
        System_Change_Language_Desc: "Wybierz język, który ma być wyświetlany na pulpicie nawigacyjnym."
      }
    }
}