export default {
    translation: {
      Login: {
        Title: "Logue para continuar",
        Username_or_Email: "Usuário ou Email",
        Password: "Senha",
        Login_Button: "Entrar",
        Forgot_Password: "Esqueceu sua senha?",
        Username_or_Email_Desc: "Deve ser fornecido um usuário ou e-mail.",
        Account_Password_Desc: "Por favor, insira a senha da sua conta.",
        Account_Incorrect: "Não foi possível encontrar uma conta com essas credenciais.",
        Many_Attempts: "Houve muitas tentativas de login. Tente novamente mais tarde.",
        Recaptcha_Error: "Falha na validação dos dados do reCAPTCHA.",
        Request_Failed: "Pedido falhou com o código de status 404",
        CSRF_Token: "CSRF Incompatível."
      },
      Reset_Password: {
        Password_Reset: "Redefinição de senha",
        Email: "Email",
        New_Password_Required: "Uma nova senha é necessária",
        Password_Characters_Min: "A sua nova senha deve ter pelo menos 8 caracteres.",
        Password_Not_Match: "A sua nova senha não corresponde.",
        Account_Email: "Digite o endereço de e-mail da sua conta para receber instruções sobre como redefinir sua senha.",
        Valid_Email: "O endereço de Email deve ser válido para continuar.",
        Send_Email: "Enviar Email",
        Return_to_Login: "Voltar para login",
        Reset_Password: "Redefinir senha",
        New_Password: "Nova senha",
        New_Password_Desc: "A senha deve ter no mínimo 8 caracteres.",
        Confirm_New_Password: "Confirmar nova senha",
        Send_Email_Link: "Nós enviamos por e-mail seu link de redefinição de senha!"
      },
      Two_Factor_Auth: {
        Device_Checkpoint: "Verificação de dispositivo",
        Recovery_Code: "Código de recuperação",
        Authentication_Code: "Código de Autenticação",
        Enter_Two_Factor_Desc_1: "Insira o token de dois fatores gerado pelo seu dispositivo.",
        Enter_Two_Factor_Desc_2: "Insira um dos códigos de recuperação gerados ao configurar a autenticação 2-Fatores nesta conta para poder continuar.",
        Lost_Device: "Eu perdi meu dispositivo",
        Have_Device: "Eu tenho o meu dispositivo",
        Continue: "Continuar"
      },
      Account_Overview: {
        Two_Factor_Activate_Desc_1: "Você deve fornecer um código de autenticação para continuar.",
        Two_Factor_Activate_Desc_2: "A autenticação de dois fatores está atualmente habilitada em sua conta.",
        Two_Factor_Activate_Desc_3: "O código do autenticador deve ter 6 dígitos.",
        Two_Factor_Active_Title: "Autenticação de dois fatores ativada",
        Two_Factor_Active_Desc_1: "A autenticação de dois fatores foi habilitada em sua conta. Caso você perca o acesso ao seu dispositivo autenticador, você precisará usar um dos códigos exibidos abaixo para acessar sua conta.",
        Two_Factor_Active_Desc_2: "Estes códigos não serão exibidos novamente. ",
        Two_Factor_Active_Desc_3: "Anote-os agora, armazenando-os em um repositório seguro, como um gerenciador de senhas.",
        Two_Factor_Active_Button: "Fechar",
        Two_Factor_Disabled_Desc: "Atualmente, você não tem a autenticação de dois fatores habilitada em sua conta. Clique no botão abaixo para começar a configurá-lo.",
        Two_Factor_Disable_Desc_1: "Você deve fornecer sua senha atual para poder continuar.",
        Two_Factor_Disable_Desc_2: "Para desativar a autenticação de dois fatores, você precisará fornecer a senha de sua conta.",
        Two_Factor_Disable_Title: "Senha atual",
        Two_Factor_Disable_Button: "Desativar",
        Two_Factor_Setup_Desc_1: "Digite o código de seu dispositivo autenticador após a digitalização da imagem QR.",
        Two_Factor_Setup_Desc_2: "Alternativamente, digite o seguinte símbolo em seu pedido de autenticação:",
        Two_Factor_Setup_Button: "Ativar",
        Two_Factor_Incorrect_Password: "A senha fornecida não é válida.",
        Button_Disable: "Desativar",
        Button_Enable: "Ativar",
        Create_Api_Desc_Title: "Descrição",
        Create_Api_Desc: "Uma descrição desta chave API.",
        Create_Api_Ips_Title: "IPs permitidos",
        Create_Api_Ips_Desc: "Deixe em branco para permitir que qualquer endereço IP utilize esta chave API, caso contrário, forneça cada endereço IP em uma nova linha.",
        Create_Api_Button: "Criar",
        Update_Email_Desc_1: "Você deve fornecer a senha atual de sua conta.",
        Update_Email_Required: "O e-mail é um campo obrigatório",
        Update_Email_Success_Title: "Sucesso",
        Update_Email_Success: "Seu e-mail principal foi atualizado.",
        Update_Email_Error_Title: "Erro",
        Update_Email_Button: "Atualizar E-mail",
        Update_Password_Title: "Nova senha",
        Update_Password_Desc_1: "Você deve fornecer sua senha atual.",
        Update_Password_Desc_2: "A confirmação da senha não corresponde à senha que você inseriu.",
        Update_Password_Desc_3: "Sua nova senha deve ter pelo menos 8 caracteres e ser exclusiva deste site.",
        Update_Password_Required: "A senha é um campo obrigatório",
        Update_Password_Button: "Atualizar senha",
        Update_Password_Error: "A senha atual fornecida é inválida.",
        Update_Password_Min: "A senha deve ter pelo menos 8 caracteres",
        Confirm_Password: "Confirmar senha",
        Account_Page_Title: "Visão Geral",
        Account_Two_Factor_Required_Title: "Autenticação de dois fatores é obrigatória",
        Account_Two_Factor_Required_Desc: "Sua conta deve ter a autenticação de dois fatores ativada para continuar.",
        Account_Update_Email_Title: "Atualizar Email",
        Account_Setup_Two_Factor_Title: "Configurar 2-Fatores",
        Api_Page_Title: "API da conta",
        Api_Create_Title: "Criar chave API",
        Api_List_Title: "Chaves API",
        Api_List_Loading: "Carregando...",
        Api_List_Empty: "Não existem chaves de API para esta conta.",
        Api_List_Used_1: "Última vez usada: ",
        Api_List_Used_2: "Nunca",
        Api_Delete_Title: "Confirme a exclusão da chave",
        Api_Delete_Button: "Sim, exclua a chave",
        Api_Delete_Desc: "Tem certeza de que deseja excluir esta chave de API? Todas as solicitações que o usam serão imediatamente invalidadas e falharão.",
        Api_Setup_Title: "Sua chave API",
        Api_Setup_Desc: "A chave API que você solicitou é mostrada abaixo. Guarde-a em um local seguro, ela não será mostrada novamente.",
        Api_Min_Characters: "A descrição deve ter pelo menos 4 caracteres",
        Api_Setup_Button: "Fechar",
        Api_Ip_Incorrect_1: "O endereço IP 1 deve ser um endereço IP válido.",
        Api_Ip_Incorrect_2: "O endereço IP 2 deve ser um endereço IP válido.",
        Api_Ip_Incorrect_3: "O endereço IP 3 deve ser um endereço IP válido."
      },
      Search: {
        Search_Title: "Buscar servidor",
        Search_Desc_1: "Por favor, insira pelo menos três caracteres para começar a busca.",
        Search_Desc_2: "Insira um nome de servidor, uuid ou alocação para iniciar a pesquisa."
      },
      Dashboard: {
        Dash_Page_Title: "Painel",
        Dash_Show_Server_1: "Mostrar outros servidores",
        Dash_Show_Server_2: "Mostrando seus servidores",
        Dash_Show_Server_3: "Não há outros servidores para exibir.",
        Dash_Show_Server_4: "Não há servidores associados à sua conta."
      },
      Server_Row: {
        Server_Unlimited: "Ilimitado",
        Server_Suspended: "Suspendido",
        Server_Connect_Error: "Erro de conexão",
        Server_Transferring: "Transferindo",
        Server_Installing: "Instalando",
        Server_Restoring_Backup: "Restaurando Backup",
        Server_Unavailable: "Indisponível",
        Server_Of: "de"
      },
      Elements: {
        Elements_Cancel_Button: "Cancelar",
        Elements_Copy_Text: "Copiado para area de transferência.",
        Elements_Error: "Um erro foi encontrado durante a apresentação desta página. Tente atualizar a página."
      },
      Server: {
        Server_Page_Title: "Console",
        Server_Transfer_Console: "A transferência falhou.",
        Server_Archived_Console: "O servidor foi arquivado com sucesso, tentando a conexão para a node alvo...",
        Server_Send_Command: "Digite um comando...",
        Server_State_Console: "Servidor foi marcado como ",
        Server_State_Starting: "iniciando",
        Server_State_Offline: "desligado",
        Server_State_Stopping: "parando",
        Server_State_Running: "online",
        Server_State_Connect: "Conectando...",
        Server_State_Install: "Este servidor está atualmente executando seu processo de instalação e a maioria das ações não estão disponíveis.",
        Server_State_Transfer: "Este servidor está atualmente sendo transferido para outra node e todas as ações não estão disponíveis.",
        Server_Button_Start: "Iniciar",
        Server_Button_Restart: "Reiniciar",
        Server_Button_Kill: "Matar",
        Server_Button_Stop: "Parar",
        Server_Memory_Graph_Title: "Uso de memória",
        Server_Cpu_Graph_Title: "Uso de CPU",
        Server_Graph_Desc: "Servidor está desligado.",
        Server_Websocket_Error: "Houve um erro na validação das credenciais fornecidas para o websocket. Por favor, atualize a página.",
        Server_Connect_Server: "Estamos tendo alguns problemas para nos conectarmos ao seu servidor, por favor espere..."
      },
      Server_Backup: {
        Backup_Page_Title: "Backups",
        Backup_Empty_1: "Parece que ficamos sem backups para mostrar a você, tente voltar uma página.",
        Backup_Empty_2: "Parece que atualmente não há backups armazenados para este servidor.",
        Backup_Forbidden: "Os backups não podem ser criados para este servidor porque o limite de backup está definido como 0.",
        Backup_Information: "foram criados backups para este servidor.",
        Backup_Create_Title_1: "Criar backup do servidor",
        Backup_Create_Title_2: "Nome do backup",
        Backup_Create_Title_3: "Arquivos e Diretórios Ignorados",
        Backup_Create_Title_4: "Trancar",
        Backup_Create_Desc_1: "Se fornecido, o nome que deve ser usado para fazer referência a este backup.",
        Backup_Create_Desc_2: "Digite os arquivos ou pastas a serem ignorados durante a geração deste backup. Deixe em branco para usar o conteúdo do arquivo .pteroignore na raiz do diretório do servidor, se presente. A correspondência de arquivos e pastas com caracteres curinga é suportada, além de negar uma regra ao prefixar o caminho com um ponto de exclamação.",
        Backup_Create_Desc_3: "Impede que este backup seja apagado até ser explicitamente desbloqueado.",
        Backup_Create_Start_Button: "Iniciar o backup",
        Backup_Create_Button: "Criar backup",
        Backup_Created_Title: "Desbloquear este backup?",
        Backup_Created_Desc_1: "Você tem certeza de que quer desbloquear este backup? Ele não será mais protegido contra apagamentos automáticos ou acidentais.",
        Backup_Created_Button: "Sim, desbloquear",
        Backup_Restore_Title: "Restaurar este backup?",
        Backup_Restore_Desc_1: "Este servidor será interrompido a fim de restaurar o backup. Uma vez iniciado o backup, você não será capaz de controlar o estado de energia do servidor, acessar o gerenciador de arquivos, ou criar backups adicionais até que ele seja concluído.",
        Backup_Restore_Desc_2: "Você tem certeza de que quer continuar?",
        Backup_Restore_Desc_3: "Remova todos os arquivos e pastas antes de restaurar este backup.",
        Backup_Restore_Button: "Restaurar o backup",
        Backup_Delete_Title: "Excluir este backup?",
        Backup_Delete_Desc_1: "Você tem certeza de que deseja apagar este backup? Esta é uma operação permanente e o backup não pode ser recuperado uma vez que foi apagado.",
        Backup_Delete_Button: "Sim, excluir backup",
        Backup_SubMenu_Download: "Download",
        Backup_SubMenu_Restore: "Restaurar",
        Backup_SubMenu_Unlock: "Desbloquear",
        Backup_SubMenu_Lock: "Bloquear",
        Backup_SubMenu_Delete: "Excluir"
      },
      Server_Databases: {
        Database_Page_Title: "Bancos de dados",
        Database_Show_Empty: "Parece que você não tem nenhum banco de dados.",
        Database_Show_Forbidden: "Não pode ser criado bancos de dados para este servidor.",
        Database_Limit_Desc: "bancos de dados foram alocados a este servidor.",
        Database_Create_Title_1: "Criar banco de dados",
        Database_Create_Title_2: "Nome do banco de dados",
        Database_Create_Title_3: "Conexões de",
        Database_Create_Desc_1: "Um nome descritivo para sua instância de banco de dados.",
        Database_Create_Desc_2: "De onde as conexões devem ser permitidas. Use % para qualquer.",
        Database_Create_Button_1: "Criar banco de dados",
        Database_Create_Button_2: "Novo banco de dados",
        Database_Create_Error_1: "Um erro inesperado foi encontrado durante o processamento, por favor tente novamente.",
        Database_Create_Error_2: "Deve ser fornecido um nome de banco de dados.",
        Database_Create_Error_3: "O nome do banco de dados deve ter pelo menos 3 caracteres.",
        Database_Create_Error_4: "O nome do banco de dados não deve exceder 48 caracteres.",
        Database_Create_Error_5: "O nome do banco de dados deve conter apenas caracteres alfanuméricos, sublinhados, travessões e/ou pontos.",
        Database_Create_Error_6: "Deve ser fornecido um valor de conexão.",
        Database_Create_Error_7: "Deve ser fornecido um endereço de conexão válido.",
        Database_Delete_Title_1: "Confirmar a exclusão do banco de dados",
        Database_Delete_Title_2: "Confirmar nome do banco de dados",
        Database_Delete_Title_3: "Detalhes da conexão do banco de dados",
        Database_Delete_Title_4: "Host",
        Database_Delete_Title_5: "Conexões de",
        Database_Delete_Title_6: "Usuário",
        Database_Delete_Title_7: "Senha",
        Database_Delete_Title_8: "String de conexão JDBC",
        Database_Delete_Desc_1: `A exclusão de um banco de dados é uma ação permanente, não pode ser desfeita. Isto apagará permanentemente o banco de dados "{{database}}" e removerá todos os dados associados.`,
        Database_Create_Desc_2: "Digite o nome do banco de dados para confirmar a exclusão.",
        Database_Delete_Button: "Excluir",
        Database_Rotate_Button: "Gerar nova senha",
        Database_Delete_Error_1: "O nome do banco de dados deve ser fornecido.",
        Database_Delete_Error_2: "Não foi encontrado nenhum host de banco de dados que atenda aos requisitos para este servidor."
      },
      Server_Files: {
        Files_Page_Title: "Gerenciador de arquivos",
        Files_Create_Button: "Novo arquivo",
        Files_Directory_Empty: "Este diretório parece estar vazio.",
        Files_Show_Files_Max: "Este diretório é muito grande para ser exibido no navegador, limitando a saída para os primeiros 250 arquivos.",
        Files_Chmod_Title: "Nível de permissão",
        Files_Chmod_Button: "Atualizar",
        Files_Delete_File_Or_Directory_Title: "Excluir este",
        Files_Delete_File_Or_Directory_Button: "Sim, excluir",
        Files_Delete_File_Or_Directory_Desc: "A exclusão de arquivos é uma operação permanente, não se pode desfazer esta ação.",
        Files_Delete_File: "arquivo",
        Files_Delete_Title: "Excluir estes arquivos?",
        Files_Delete_Desc_1: "Tem certeza de que deseja excluir {{selected}} arquivo(s)?",
        Files_Delete_Desc_2: "A exclusão do(s) arquivo(s) listado(s) abaixo é uma operação permanente, você não pode desfazer esta ação.",
        Files_Delete_Desc_3: "outros(s)",
        Files_Delete_Button: "Sim, excluir arquivos",
        Files_Delete_Directory: "diretório",
        Files_SubMenu_Rename: "Renomear",
        Files_SubMenu_Move: "Mover",
        Files_SubMenu_Permissions: "Permissões",
        Files_SubMenu_Copy: "Copiar",
        Files_SubMenu_Archive: "Compactar",
        Files_SubMenu_Unarchive: "Descompactar",
        Files_SubMenu_Download: "Baixar",
        Files_SubMenu_Delete: "Excluir",
        Files_Edit_Ptero_Ignore_1: "Você está editando um",
        Files_Edit_Ptero_Ignore_2: "Arquivo. Quaisquer arquivos ou diretórios listados aqui serão excluídos dos backups. Os curingas são compatíveis com o uso de um asterisco",
        Files_Edit_Ptero_Ignore_3: "Você pode negar uma regra anterior acrescentando um ponto de exclamação",
        Files_Edit_Save_Button: "Salvar conteúdo",
        Files_Create_Title: "Nome do arquivo",
        Files_Create_Desc: "Digite o nome com que este arquivo deve ser salvo",
        Files_Create_Error: "Nome do arquivo é um campo obrigatório",
        Files_Create_Button: "Criar arquivo",
        Files_Message_Archiving: "Compactando arquivos...",
        Files_Message_Deleting: "Excluindo arquivos...",
        Files_Create_Directory_Title: "Nome do diretório",
        Files_Create_Directory_Desc_1: "Um nome de diretório válido deve ser fornecido.",
        Files_Create_Directory_Desc_2: "Este diretório será criado em",
        Files_Create_Directory_Button: "Criar Diretório",
        Files_Move_Desc_1: "Digite o nome e diretório deste arquivo ou pasta, em relação ao diretório atual.",
        Files_Move_Desc_2: "Nova localização:",
        Files_Drag_Desc: "Arraste e solte arquivos para carregar.",
        Files_Drag_Button: "Importar",
        Files_Error_1: "Um nome para o arquivo é necessário.",
        Files_Error_2: "Ocorreu um erro no host remoto: Não é possível mover ou renomear o arquivo, o destino já existe.."
      },
      Server_Users: {
        User_Page_Title: "Usuários",
        User_Sub_Users_Empty: "Parece que você não tem nenhum subusuário.",
        User_Create_Title_1: "Criar novo subusuário",
        User_Create_Title_2: "Email do usuário",
        User_Create_Sub_User_Desc_1: "Digite o endereço de e-mail do usuário que você deseja convidar como um subusuário para este servidor.",
        User_Create_Sub_User_Desc_2: "Os endereços de e-mail não devem exceder 191 caracteres.",
        User_Create_Sub_User_Desc_3: "Um endereço de e-mail válido deve ser fornecido.",
        User_Modify_Or_View_Email_Title: "permissões para {{subuser}}",
        User_Modify_Title: "Modificar",
        User_View_Title: "Ver",
        User_Modify_Button: "Salvar",
        User_Create_Button_1: "Convidar usuário",
        User_Create_Button_2: "Novo usuário",
        User_Create_Sub_User_Desc: "Somente as permissões que sua conta está atualmente designada podem ser selecionadas quando da criação ou modificação de outros usuários.",
        User_Delete_Title: "Excluir este subusuário?",
        User_Delete_Desc_1: "Você tem certeza de que deseja remover este subusuário? Eles terão todo o acesso a este servidor revogado imediatamente.",
        User_Delete_Button: "Sim, remova o subusuário",
        User_Show_2FA: "2FA Ativado",
        User_Show_Permissions: "Permissões",
        User_Create_Sub_Title_1: "Controle",
        User_Create_Sub_Title_2: "Usuário",
        User_Create_Sub_Title_3: "Arquivos",
        User_Create_Sub_Title_4: "Backup",
        User_Create_Sub_Title_5: "Alocação",
        User_Create_Sub_Title_6: "Inicialização",
        User_Create_Sub_Title_7: "Banco de dados",
        User_Create_Sub_Title_8: "Cronograma",
        User_Create_Sub_Title_9: "Configurações",
        User_Create_Desc_1: "Permissões que controlam a capacidade do usuário de controlar o estado de poder de um servidor, ou enviar comandos.",
        User_Create_Desc_2: "Permissões que permitem a um usuário gerenciar outros subusuários em um servidor. Eles nunca serão capazes de editar sua própria conta, ou atribuir permissões que eles mesmos não possuem.",
        User_Create_Desc_3: "Permissões que controlam a capacidade de um usuário de modificar o sistema de arquivos para este servidor.",
        User_Create_Desc_4: "Permissões que controlam a capacidade de um usuário de criar e gerenciar backups do servidor.",
        User_Create_Desc_5: "Permissões que controlam a capacidade de um usuário de modificar as alocações de portas para este servidor.",
        User_Create_Desc_6: "Permissões que controlam a capacidade de um usuário de visualizar os parâmetros de inicialização deste servidor.",
        User_Create_Desc_7: "Permissões que controlam o acesso de um usuário ao gerenciamento do banco de dados para este servidor.",
        User_Create_Desc_8: "Permissões que controlam o acesso de um usuário ao gerenciamento de horários para este servidor.",
        User_Create_Desc_9: "Permissões que controlam o acesso de um usuário às configurações para este servidor.",
        User_Create_Option_Desc_1: "Console",
        User_Create_Option_Desc_2: "Iniciar",
        User_Create_Option_Desc_3: "Parar",
        User_Create_Option_Desc_4: "Reiniciar",
        User_Create_Option_Desc_5: "Criar",
        User_Create_Option_Desc_6: "Ler",
        User_Create_Option_Desc_7: "Atualizar",
        User_Create_Option_Desc_8: "Excluir",
        User_Create_Option_Desc_9: "Ler-Conteúdo",
        User_Create_Option_Desc_10: "Compactar",
        User_Create_Option_Desc_11: "SFTP",
        User_Create_Option_Desc_12: "Baixar",
        User_Create_Option_Desc_13: "Restaurar",
        User_Create_Option_Desc_14: "Imagem-Docker",
        User_Create_Option_Desc_15: "Ver-Senhas",
        User_Create_Option_Desc_16: "Renomear",
        User_Create_Option_Desc_17: "Reinstalar",
        User_Create_Option_Description_1: "Permite que um usuário envie comandos para a instância do servidor através do console.",
        User_Create_Option_Description_2: "Permite que um usuário inicie o servidor se ele for interrompido.",
        User_Create_Option_Description_3: "Permite que um usuário pare um servidor se ele estiver em execução.",
        User_Create_Option_Description_4: "Permite que um usuário execute um reinício de servidor. Isto lhes permite iniciar o servidor se ele estiver offline, mas não colocar o servidor em um estado completamente parado.",
        User_Create_Option_Description_5: "Permite que um usuário crie novos subusuários para o servidor.",
        User_Create_Option_Description_6: "Permite que o usuário visualize os subusuários e suas permissões para o servidor.",
        User_Create_Option_Description_7: "Permite que um usuário modifique outros subusuários.",
        User_Create_Option_Description_8: "Permite que um usuário exclua um subusuário do servidor.",
        User_Create_Option_Description_9: "Permite ao usuário criar arquivos e pastas adicionais através do Painel ou de upload direto.",
        User_Create_Option_Description_10: "Permite que um usuário visualize o conteúdo de um diretório, mas não visualize o conteúdo ou baixe arquivos.",
        User_Create_Option_Description_11: "Permite que um usuário veja o conteúdo de um determinado arquivo. Isto também permitirá que o usuário faça o download de arquivos.",
        User_Create_Option_Description_12: "Permite que um usuário atualize o conteúdo de um arquivo ou diretório existente.",
        User_Create_Option_Description_13: "Permite que um usuário exclua arquivos ou diretórios.",
        User_Create_Option_Description_14: "Permite que um usuário arquive o conteúdo de um diretório, bem como descompacte os arquivos existentes no sistema.",
        User_Create_Option_Description_15: "Permite que um usuário se conecte ao SFTP e gerencie os arquivos do servidor usando as outras permissões de arquivo atribuídas.",
        User_Create_Option_Description_16: "Permite que um usuário crie novos backups para este servidor.",
        User_Create_Option_Description_17: "Permite ao usuário visualizar todos os backups que existem para este servidor.",
        User_Create_Option_Description_18: "Permite que um usuário remova backups do sistema.",
        User_Create_Option_Description_19: "Permite que um usuário faça o download de um backup para o servidor. Perigo: isto permite ao usuário acessar todos os arquivos para o servidor no backup.",
        User_Create_Option_Description_20: "Permite que um usuário restaure um backup para o servidor. Perigo: isto permite que o usuário exclua todos os arquivos do servidor no processo.",
        User_Create_Option_Description_21: "Permite ao usuário visualizar todas as alocações atualmente atribuídas a este servidor. Os usuários com qualquer nível de acesso a este servidor podem sempre visualizar a alocação primária.",
        User_Create_Option_Description_22: "Permite que um usuário atribua alocações adicionais ao servidor.",
        User_Create_Option_Description_23: "Permite ao usuário alterar a alocação do servidor primário e anexar notas a cada alocação.",
        User_Create_Option_Description_24: "Permite que um usuário exclua uma alocação do servidor.",
        User_Create_Option_Description_25: "Permite que um usuário visualize as variáveis de inicialização de um servidor.",
        User_Create_Option_Description_26: "Permite que um usuário modifique as variáveis de inicialização do servidor.",
        User_Create_Option_Description_27: "Permite que um usuário modifique a imagem do Docker utilizada ao executar o servidor.",
        User_Create_Option_Description_28: "Permite que um usuário crie um novo banco de dados para este servidor.",
        User_Create_Option_Description_29: "Permite que um usuário visualize o banco de dados associado a este servidor.",
        User_Create_Option_Description_30: "Permite que um usuário gire a senha em uma instância do banco de dados. Se o usuário não tiver a permissão view_password, ele não verá a senha atualizada.",
        User_Create_Option_Description_31: "Permite que um usuário remova uma instância de banco de dados deste servidor.",
        User_Create_Option_Description_32: "Permite que um usuário visualize a senha associada a uma instância de banco de dados para este servidor.",
        User_Create_Option_Description_33: "Permite que um usuário crie novos horários para este servidor.",
        User_Create_Option_Description_34: "Permite ao usuário visualizar os horários e as tarefas associadas a eles para este servidor.",
        User_Create_Option_Description_35: "Permite que um usuário atualize horários e tarefas de agendamento para este servidor.",
        User_Create_Option_Description_36: "Permite que um usuário exclua horários para este servidor.",
        User_Create_Option_Description_37: "Permite que um usuário renomeie este servidor.",
        User_Create_Option_Description_38: "Permite que um usuário acione uma reinstalação deste servidor."
      },
      Server_Network: {
        Network_Page_Title: "Rede",
        Network_Alocations_Desc_1: "Atualmente você está usando {{data}} de {{limit}} alocações permitidas para este servidor.",
        Network_Create_Alocation_Button: "Criar Alocação",
        Network_Hostname: "Host",
        Network_IP_Address: "Endereço IP",
        Network_Port: "Porta",
        Network_Notes: "Notas",
        Network_Primary: "Primário",
        Network_Primary_Button: "Tornar Primário",
        Network_Delete_Title: "Remover esta alocação?",
        Network_Delete_Button: "Remover",
        Network_Delete_Desc_1: "Esta alocação será imediatamente removida de seu servidor. Você tem certeza de que quer continuar?",
        Network_Error_1: "A alocação automática do servidor não está habilitada.",
      },
      Server_Schedules: {
        Task_Page_Title: "Cronogramas",
        Task_Empty_Message: "Não há cronogramas configurados para este servidor.",
        Task_Create_Button: "Criar cronograma",
        Task_Edit_Button: "Salvar mudanças",
        Task_Delete_Title: "Excluir cronograma?",
        Task_Delete_Button_1: "Sim, excluir cronograma",
        Task_Delete_Desc: "Você tem certeza de que quer excluir este cronograma? Todas as tarefas serão removidas e quaisquer processos em andamento serão encerrados.",
        Task_Delete_Button_2: "Excluir",
        Task_Create_Title: "Criar um novo cronograma",
        Task_Edit_Title: "Editar cronograma",
        Task_Create_Or_Edit_Title_1: "Nome do cronograma",
        Task_Create_Or_Edit_Title_2: "Somente quando o servidor está online",
        Task_Create_Or_Edit_Title_3: "Cronograma Ativado",
        Task_Create_Or_Edit_Desc_1: "Um identificador para este cronograma.",
        Task_Create_Or_Edit_Desc_2: "O sistema de cronograma suporta o uso da sintaxe Cronjob ao definir quando as tarefas devem começar a ser executadas. Use os campos acima para especificar quando estas tarefas devem começar a ser executadas.",
        Task_Create_Or_Edit_Desc_3: "Somente execute este cronograma quando o servidor estiver em estado de funcionamento.",
        Task_Create_Or_Edit_Desc_4: "Este cronograma será executado automaticamente se ativado.",
        Task_Create_Or_Edit_Minute: "Minuto",
        Task_Create_Or_Edit_Hour: "Hora",
        Task_Create_Or_Edit_Day_Of_Month: "Dia do mês",
        Task_Create_Or_Edit_Month: "Mês",
        Task_Create_Or_Edit_Day_Of_Week: "Dia da semana",
        Task_New_Task_Button: "Nova Tarefa",
        Task_Run_Task_Button: "Executar agora",
        Task_Cron_Row_Minute: "Minuto",
        Task_Cron_Row_Hour: "Hora",
        Task_Cron_Row_Day_Month: "Dia (Mês)",
        Task_Cron_Row_Month: "Mês",
        Task_Cron_Row_Day_Week: "Dia (Semana)",
        Task_Task_Page_Title: "Tarefas",
        Task_Task_Processing: "Processando",
        Task_Task_Last_Run: "Último Processo:",
        Task_Task_Next_Run: "Próximo Processo:",
        Task_Task_Never: "Nunca",
        Task_Task_NA: "n/a",
        Task_Task_Edit_Button: "Editar",
        Task_Task_Active: "Ativo",
        Task_Task_Inactive: "Inativo",
        Task_Task_Delete_Title: "Confirmar exclusão de tarefas",
        Task_Task_Delete_Button: "Excluir tarefa",
        Task_Task_Delete_Desc: "Você tem certeza de que quer excluir esta tarefa? Esta ação não pode ser desfeita.",
        Task_Task_Files_And_Folders_Message: "Ignorando arquivos e pastas:",
        Task_Task_Continue_Message: "Continuar se falhar",
        Task_Task_Time_Message: "{{time}}seg. depois",
        Task_Task_Edit_Title: "Editar Tarefa",
        Task_Task_Create_Title: "Criar tarefa",
        Task_Task_Create_Or_Edit_Command: "Enviar comando",
        Task_Task_Create_Or_Edit_Power: "Enviar ação de iniciar",
        Task_Task_Create_Or_Edit_Backup: "Criar backup",
        Task_Task_Create_Or_Edit_Title_1: "Compensação de tempo (em segundos)",
        Task_Task_Create_Or_Edit_Title_2: "Carga",
        Task_Task_Create_Or_Edit_Title_3: "Arquivos Ignorados",
        Task_Task_Create_Or_Edit_Title_4: "Continuar sobre o fracasso",
        Task_Task_Create_Or_Edit_Title_5: "Ação",
        Task_Task_Create_Or_Edit_Desc_1: "O tempo de espera após a tarefa anterior é executado antes de executar esta tarefa. Se esta for a primeira tarefa em um cronograma, isto não será aplicado.",
        Task_Task_Create_Or_Edit_Desc_2: "Opcional. Inclua os arquivos e pastas a serem excluídos neste backup. Por padrão, o conteúdo de seu arquivo .pteroignore será utilizado. Se você tiver atingido seu limite de backup, o backup mais antigo será rotacionado.",
        Task_Task_Create_Or_Edit_Desc_3: "As tarefas futuras serão executadas quando esta tarefa falhar.",
        Task_Task_Create_Or_Edit_Option_1: "Iniciar o servidor",
        Task_Task_Create_Or_Edit_Option_2: "Reiniciar o servidor",
        Task_Task_Create_Or_Edit_Option_3: "Parar o servidor",
        Task_Task_Create_Or_Edit_Option_4: "Terminar o servidor",
        Task_Task_Create_Or_Edit_Error_1: "Deve ser fornecida uma carga para a tarefa.",
        Task_Task_Create_Or_Edit_Error_2: "A compensação de tempo deve ser um número válido entre 0 e 900.",
        Task_Task_Create_Or_Edit_Error_3: "Deve ser fornecido um valor de compensação de tempo.",
        Task_Task_Create_Or_Edit_Error_4: "A compensação de tempo deve ser de pelo menos 0 segundos.",
        Task_Task_Create_Or_Edit_Error_5: "A compensação de tempo deve ser inferior a 900 segundos.",
        Task_Task_Create_Or_Edit_Error_6: "Uma tarefa de backup não pode ser criada quando o limite de backup do servidor é definido como 0."
      },
      Server_Settings: {
        Settings_Page_Title: "Configurações",
        Settings_SFTP_Title_1: "Detalhes do SFTP",
        Settings_SFTP_Title_2: "Endereço do servidor",
        Settings_SFTP_Title_3: "Usuário",
        Settings_SFTP_Desc_1: "Sua senha SFTP é a mesma senha que você usa para acessar este painel.",
        Settings_SFTP_Button: "Abrir SFTP",
        Settings_Debug_Title_1: "Informações sobre depuração",
        Settings_Debug_Title_2: "Node",
        Settings_Debug_Title_3: "ID do servidor",
        Settings_Reinstall_Title_1: "Reinstalar servidor",
        Settings_Reinstall_Title_2: "Confirmar reinstalação do servidor",
        Settings_Reinstall_Button: "Sim, reinstalar servidor",
        Settings_Reinstall_Desc_1: "Seu servidor será interrompido e alguns arquivos poderão ser excluídos ou modificados durante este processo, você tem certeza de que deseja continuar?",
        Settings_Reinstall_Desc_2: "A reinstalação de seu servidor irá pará-lo e, em seguida, executar novamente o script de instalação que inicialmente o configurou.",
        Settings_Reinstall_Desc_3: "Alguns arquivos podem ser excluídos ou modificados durante este processo, por favor, faça uma cópia de segurança de seus dados antes de continuar.",
        Settings_Reinstall_Success: "Seu servidor começou o processo de reinstalação.",
        Settings_Reinstall_Error: "Não foi possível estabelecer uma conexão com a máquina que roda este servidor. Por favor, tente novamente.",
        Settings_Rename_Server_Title_1: "Mudar o nome do servidor",
        Settings_Rename_Server_Title_2: "Nome do servidor",
        Settings_Rename_Server_Button: "Salvar",
        Settings_Rename_Required: "O nome é um campo obrigatório"
      },
      Server_Startup: {
        Startup_Page_Title: "Configurações de inicialização",
        Startup_Command_Title_1: "Comandos de inicialização",
        Startup_Docker_Title: "Imagem Docker",
        Startup_Docker_Desc: "Este é um recurso avançado que permite selecionar uma imagem Docker para usar ao executar esta instância de servidor.",
        Startup_Docker_Error: "A imagem do Docker deste servidor foi definida manualmente por um administrador e não pode ser alterada através desta UI.",
        Startup_Variables_Title: "Variáveis",
        Startup_Variables_Read: "Somente leitura",
        Startup_Server_Error_Title: "Oops!",
      },
      Server_Features: {
        Features_Invalid_Java_Title_1: "Versão inválida do Java, atualizar imagem Docker?",
        Features_Invalid_Java_Desc_1: "Este servidor não pode iniciar devido ao não cumprimento da versão Java requerida.",
        Features_Invalid_Java_Desc_2: `Ao pressionar "Atualizar imagem" abaixo você está reconhecendo que a imagem Docker que este servidor usa será mudada para uma imagem abaixo que tenha a versão Java que você está solicitando.`,
        Features_Invalid_Java_Desc_3: "Favor selecionar uma versão Java da lista abaixo.",
        Features_Invalid_Java_Button_1: "Atualizar imagem",
        Features_Invalid_Java_Button_2: "Cancelar",
        Features_Accept_Eula_Title: "Aceitar Minecraft® EULA",
        Features_Accept_Eula_Desc_1: `Ao pressionar "Aceito" abaixo, você está indicando sua concordância com o`,
        Features_Accept_Eula_Desc_2: "Minecraft® EULA",
        Features_Accept_Eula_Button_1: "Aceito",
        Features_Accept_Eula_Button_2: "Cancelar",
        Features_Invalid_GSL_Title: "GSL Token Inválido!",
        Features_Invalid_GSL_Desc_1: "Parece que o Token de Login do seu servidor (GSL Token) é inválido ou expirou.",
        Features_Invalid_GSL_Desc_2: "Você pode gerar um novo e inseri-lo abaixo ou deixar o campo em branco para removê-lo completamente.",
        Features_Invalid_GSL_Desc_3: "GSL Token",
        Features_Invalid_GSL_Desc_4: "Visite https://steamcommunity.com/dev/managegameservers para gerar um token.",
        Features_Invalid_GSL_Button: "Atualizar GSL Token",
        Features_Invalid_PID_Title_1: "Memória ou limite de processo alcançado...",
        Features_Invalid_PID_Title_2: "Possível limite de recursos atingido...",
        Features_Invalid_PID_Desc_1: "Este servidor atingiu o limite máximo de processo ou memória.",
        Features_Invalid_PID_Desc_2: "Aumentando",
        Features_Invalid_PID_Desc_3: "na configuração das wings,",
        Features_Invalid_PID_Desc_4: ", pode ajudar a resolver este problema.",
        Features_Invalid_PID_Desc_5: "Nota: As wings devem ser reiniciadas para que as alterações do arquivo de configuração entrem em vigor",
        Features_Invalid_PID_Desc_6: "Este servidor está tentando usar mais recursos do que os alocados. Favor entrar em contato com o administrador e dar-lhes o erro abaixo.",
        Features_Invalid_PID_Desc_7: "pthread_create falhou, Possivelmente fora da memória ou dos limites de processo/recursos atingidos",
        Features_Invalid_Disk_Title: "Fora do espaço disponível em disco...",
        Features_Invalid_Disk_Desc_1: "Este servidor ficou sem espaço disponível em disco e não pode completar o processo de instalação ou atualização.",
        Features_Invalid_Disk_Desc_2: "Certifique-se de que a máquina tenha espaço suficiente em disco digitando",
        Features_Invalid_Disk_Desc_3: "na máquina que hospeda este servidor. Exclua arquivos ou aumente o espaço disponível em disco para resolver o problema.",
        Features_Invalid_Disk_Desc_4: "Este servidor ficou sem espaço disponível em disco e não pode completar o processo de instalação ou atualização. Favor entrar em contato com o(s) administrador(es) e informá-lo(s) sobre problemas de espaço em disco.",
      },
      Server_States: {
        Server_Installing_Title: "Instalação em andamento",
        Server_Installing_Desc: "Seu servidor deve estar pronto em breve, tente novamente em alguns minutos.",
        Server_Suspended_Title: "Servidor Suspenso",
        Server_Suspended_Desc: "Este servidor está suspenso e não pode ser acessado.",
        Server_Transferring_Title: "Transferindo",
        Server_Transferring_Desc: "Seu servidor está sendo transferido para uma nova node, por favor, verifique mais tarde.",
        Server_Restoring_Title: "Restaurando backup",
        Server_Restoring_Desc: "Seu servidor está sendo restaurado a partir de um backup, por favor, verifique novamente em alguns minutos."
      },
      Page_Titles: {
        Title_Console: "Console",
        Title_File_Manager: "Gerenciador de arquivos",
        Title_Databases: "Bancos de dados",
        Title_Schedules: "Cronogramas",
        Title_Users: "Usuários",
        Title_Backups: "Backups",
        Title_Network: "Rede",
        Title_Startup: "Inicialização",
        Title_Settings: "Configurações",
        Title_API_Credentials: "Definições da API"
      },
      Times_And_Dates: {
        Date_Format: "dd'-'MM'-'yyyy h:mma",
        Time_Minutes_1: "Há 4 minutos",
        Time_Minutes_2: "Há 3 minutos",
        Time_Minutes_3: "Há 2 minutos",
        Time_Minutes_4: "Há 1 minuto",
        Time_Minutes_5: "Há menos de um minuto",
        Time_Minutes_6: "Há menos de um minuto atrás",
        Time_Minutes_7: "1 Minuto atrás",
        Time_Minutes_8: "2 Minutos atrás",
        Time_Minutes_9: "3 Minutos atrás",
        Time_Minutes_10: "4 Minutos atrás",
        Time_Minutes_11: "5 Minutos atrás",
        Time_Minutes_12: "6 Minutos atrás",
        Time_Minutes_13: "7 Minutos atrás",
        Time_Minutes_14: "8 Minutos atrás",
        Time_Minutes_15: "9 Minutos atrás",
        Time_Minutes_16: "10 Minutos atrás",
        Time_Minutes_17: "11 Minutos atrás",
        Time_Minutes_18: "12 Minutos atrás",
        Time_Minutes_19: "13 Minutos atrás",
        Time_Minutes_20: "14 Minutos atrás",
        Time_Minutes_21: "15 Minutos atrás",
        Time_Minutes_22: "16 Minutos atrás",
        Time_Minutes_23: "17 Minutos atrás",
        Time_Minutes_24: "18 Minutos atrás",
        Time_Minutes_25: "19 Minutos atrás",
        Time_Minutes_26: "20 Minutos atrás",
        Time_Minutes_27: "21 Minutos atrás",
        Time_Minutes_28: "22 Minutos atrás",
        Time_Minutes_29: "23 Minutos atrás",
        Time_Minutes_30: "24 Minutos atrás",
        Time_Minutes_31: "25 Minutos atrás",
        Time_Minutes_32: "26 Minutos atrás",
        Time_Minutes_33: "27 Minutos atrás",
        Time_Minutes_34: "28 Minutos atrás",
        Time_Minutes_35: "29 Minutos atrás",
        Time_Minutes_36: "30 Minutos atrás",
        Time_Minutes_37: "31 Minutos atrás",
        Time_Minutes_38: "32 Minutos atrás",
        Time_Minutes_39: "33 Minutos atrás",
        Time_Minutes_40: "34 Minutos atrás",
        Time_Minutes_41: "35 Minutos atrás",
        Time_Minutes_42: "36 Minutos atrás",
        Time_Minutes_43: "37 Minutos atrás",
        Time_Minutes_44: "38 Minutos atrás",
        Time_Minutes_45: "39 Minutos atrás",
        Time_Minutes_46: "40 Minutos atrás",
        Time_Minutes_47: "41 Minutos atrás",
        Time_Minutes_48: "42 Minutos atrás",
        Time_Minutes_49: "43 Minutos atrás",
        Time_Minutes_50: "44 Minutos atrás",
        Time_Minutes_51: "45 Minutos atrás",
        Time_Minutes_52: "46 Minutos atrás",
        Time_Minutes_53: "47 Minutos atrás",
        Time_Minutes_54: "48 Minutos atrás",
        Time_Minutes_55: "49 Minutos atrás",
        Time_Minutes_56: "50 Minutos atrás",
        Time_Minutes_57: "51 Minutos atrás",
        Time_Minutes_58: "52 Minutos atrás",
        Time_Minutes_59: "53 Minutos atrás",
        Time_Minutes_60: "54 Minutos atrás",
        Time_Minutes_61: "55 Minutos atrás",
        Time_Minutes_62: "56 Minutos atrás",
        Time_Minutes_63: "57 Minutos atrás",
        Time_Minutes_64: "58 Minutos atrás",
        Time_Minutes_65: "59 Minutos atrás",
        Time_Hours_1: "1 Hora atrás",
        Time_Hours_2: "2 Horas atrás",
        Time_Hours_3: "3 Horas atrás",
        Time_Hours_4: "4 Horas atrás",
        Time_Hours_5: "5 Horas atrás",
        Time_Hours_6: "6 Horas atrás",
        Time_Hours_7: "7 Horas atrás",
        Time_Hours_8: "8 Horas atrás",
        Time_Hours_9: "9 Horas atrás",
        Time_Hours_10: "10 Horas atrás",
        Time_Hours_11: "11 Horas atrás",
        Time_Hours_12: "12 Horas atrás",
        Time_Hours_13: "13 Horas atrás",
        Time_Hours_14: "14 Horas atrás",
        Time_Hours_15: "15 Horas atrás",
        Time_Hours_16: "16 Horas atrás",
        Time_Hours_17: "17 Horas atrás",
        Time_Hours_18: "18 Horas atrás",
        Time_Hours_19: "19 Horas atrás",
        Time_Hours_20: "20 Horas atrás",
        Time_Hours_21: "21 Horas atrás",
        Time_Hours_22: "22 Horas atrás",
        Time_Hours_23: "23 Horas atrás",
        Time_Days_1: "1 dia atrás",
        Time_Days_2: "2 dias atrás"
      },
      Errors: {
        Error_Key_Undefined: "Erro Interno: A chave para essa mensagem não foi definida, contate o autor: Ferks#7575",
        Error_Server_Title: "Algo deu errado",
        Error_Server_Desc: "O recurso solicitado não foi encontrado.",
        Error_Connection: "Houve um erro de comunicação com a máquina que roda este servidor. Este erro foi registrado, por favor tente novamente.",
        Error_Network: "Erro de rede",
        Error_Permission_Title: "Acesso negado",
        Error_Permission_Desc: "Você não tem permissão de acesso a esta página.",
        Error_Variables_1: "Este campo é obrigatório.",
        Error_Variables_2: "O valor deve ser de 1 dígito.",
        Error_Variables_3: "Este valor não é válido.",
        Error_Variables_4: "O valor deve ser pelo menos 1.",
        Error_Variables_5: "Este valor é maior do que limite.",
        Error_Variables_6: "O formato do valor é inválido.",
        Error_Variables_7: "O valor deve conter apenas letras, números e travessões."
      },
    }
}