export default {
    translation: {
      Login: {
        Title: "Conectați-vă pentru a continua",
        Username_or_Email: "Nume de utilizator sau Email",
        Password: "Parolă",
        Login_Button: "Conectează-te",
        Forgot_Password: "Ai uitat parola?",
        Username_or_Email_Desc: "Introdu un nume de utilizator sau email.",
        Account_Password_Desc: "Introdu parola contului.",
        Account_Incorrect: "Nu a fost găsit nici un cont care să corespundă acestor date.",
        Many_Attempts: "Ai încercat să te conectezi de prea multe ori. Reîncearcă mai târziu.",
        Recaptcha_Error: "Eroare in validarea informațiilor reCAPTCHA.",
        Request_Failed: "Solicitarea a eșuat cu codul 404",
        CSRF_Token: "Token-ul CSRF nu s-a potrivit."
      },
      Reset_Password: {
        Password_Reset: "Cere Resetarea Parolei",
        Email: "Email",
        New_Password_Required: "Introdu o parolă nouă.",
        Password_Characters_Min: "Nouă parolă trebuie să aibă cel puțin 8 caractere.",
        Password_Not_Match: "Parola nouă nu se potrivește.",
        Account_Email: "Introdu email-ul contului pentru a primi instucțiuni pentru resetearea parolei.",
        Valid_Email: "Introdu o adresă validă de email pentru a continua.",
        Send_Email: "Trimite email",
        Return_to_Login: "Revin-o la conectare",
        Reset_Password: "Resetează parola",
        New_Password: "Parolă Nouă",
        New_Password_Desc: "Nouă parolă trebuie să aibă cel puțin 8 caractere.",
        Confirm_New_Password: "Confirmă parolă nouă",
        Send_Email_Link: "V-am expediat prin email linkul de resetare a parolei!"
      },
      Two_Factor_Auth: {
        Device_Checkpoint: "Punct de control al dispozitivului",
        Recovery_Code: "Cod de recuperare",
        Authentication_Code: "Cod de autentificare",
        Enter_Two_Factor_Desc_1: "Introduceți autentificarea cu doi factori generat de dispozitivul dvs.",
        Enter_Two_Factor_Desc_2: "Introduceți unul dintre codurile de recuperare generate când ați configurat autentificarea cu doi factori pentru acest cont pentru a continua.",
        Lost_Device: "Mi-am Pierdut Dispozitivul",
        Have_Device: "Mi-am Pierdut Dispozitivul",
        Continue: "Continuă"
      },
      Account_Overview: {
        Two_Factor_Activate_Desc_1: "Trebuie să furnizați un cod de autentificare pentru a continua.",
        Two_Factor_Activate_Desc_2: "Autentificarea cu doi factori este în prezent activată pe contul dvs.",
        Two_Factor_Activate_Desc_3: "Codul de autentificare trebuie să aibă 6 cifre.",
        Two_Factor_Active_Title: "Autentificare cu doi factori activată",
        Two_Factor_Active_Desc_1: "Autentificarea cu doi factori a fost activată în contul dvs. Dacă pierdeți accesul la dispozitivul dvs. de autentificare, va trebui să utilizați unul dintre codurile afișate mai jos pentru a vă accesa contul.",
        Two_Factor_Active_Desc_2: "Aceste coduri nu vor fi afișate din nou. ",
        Two_Factor_Active_Desc_3: "Vă rugăm să le notați acum, stocându-le într-un loc securizat, cum ar fi un manager de parole.",
        Two_Factor_Active_Button: "Închide",
        Two_Factor_Disabled_Desc: "În prezent, nu aveți autentificarea cu doi factori activată în contul dvs. Faceți clic pe butonul de mai jos pentru a începe configurarea acestuia.",
        Two_Factor_Disable_Desc_1: "Trebuie să furnizați parola curentă pentru a continua.",
        Two_Factor_Disable_Desc_2: "Pentru a dezactiva autentificarea cu doi factori, va trebui să furnizați parola contului.",
        Two_Factor_Disable_Title: "Parola actuală",
        Two_Factor_Disable_Button: "Dezactivați Autentificare cu doi factori",
        Two_Factor_Setup_Desc_1: "Introduceți codul de pe dispozitivul dvs. de autentificare după scanarea imaginii QR.",
        Two_Factor_Setup_Desc_2: "Sau, introduceți următorul token în aplicația dvs. de autentificare:",
        Two_Factor_Setup_Button: "Setează",
        Two_Factor_Incorrect_Password: "Parola furnizată este invalidă.",
        Button_Disable: "Dezactiveză",
        Button_Enable: "Activează",
        Create_Api_Desc_Title: "Descriere",
        Create_Api_Desc: "O descriere a acestei chei API.",
        Create_Api_Ips_Title: "IP-uri permise",
        Create_Api_Ips_Desc: "Lăsați necompletat pentru a permite oricărei adrese IP să utilizeze această cheie API, altfel furnizați fiecare adresă IP pe o linie nouă.",
        Create_Api_Button: "Crează",
        Update_Email_Desc_1: "Trebuie să furnizați parola curentă a contului.",
        Update_Email_Required: "Email-ul este un câmp obligatoriu",
        Update_Email_Success_Title: "Succes",
        Update_Email_Success: "Email-ul dvs. principal a fost actualizat.",
        Update_Email_Error_Title: "Eroare",
        Update_Email_Button: "Actualizați email-ul",
        Update_Password_Title: "Parolă Nouă",
        Update_Password_Desc_1: "Trebuie să furnizați parola curentă.",
        Update_Password_Desc_2: "Confirmarea parolei nu se potrivește cu parola pe care ați introdus-o.",
        Update_Password_Desc_3: "Noua dvs. parolă trebuie să aibă cel puțin 8 caractere și să fie unică pentru acest site.",
        Update_Password_Required: "Parola este un câmp obligatoriu",
        Update_Password_Button: "Actualizeză parola",
        Update_Password_Error: "Parola furnizată nu este validă pentru acest cont.",
        Update_Password_Min: "Parola trebuie să aibă cel puțin 8 caractere",
        Confirm_Password: "Confirmă parola",
        Account_Page_Title: "Informații Generale Cont",
        Account_Two_Factor_Required_Title: "Autentificare cu doi factori necesară",
        Account_Two_Factor_Required_Desc: "Pentru a continua, contul dvs. trebuie să aibă activată autentificarea cu doi factori.",
        Account_Update_Email_Title: "Actualizare Adresă de Email",
        Account_Setup_Two_Factor_Title: "Configureză Autentificarea cu Doi Factori",
        Api_Page_Title: "API Cont",
        Api_Create_Title: "Crează cheia API",
        Api_List_Title: "Chei API",
        Api_List_Loading: "Se încarcă...",
        Api_List_Empty: "Nu există chei API pentru acest cont.",
        Api_List_Used_1: "Ultima dată utilizat: ",
        Api_List_Used_2: "Niciodată",
        Api_Delete_Title: "Confirmă ștergerea cheii",
        Api_Delete_Button: "Da, șterge cheia",
        Api_Delete_Desc: "Sigur doriți să ștergeți această cheie API? Toate cererile care o folosesc vor fi imediat blocate și vor eșua.",
        Api_Setup_Title: "Cheia dvs. API",
        Api_Setup_Desc: "Cheia API pe care ați solicitat-o este afișată mai jos. Vă rugăm să păstrați acest lucru într-un loc sigur, nu va fi afișat din nou.",
        Api_Min_Characters: "Descrierea trebuie să aibă cel puțin 4 caractere",
        Api_Setup_Button: "Închide",
        Api_Ip_Incorrect_1: "Adresa IP 1 trebuie să fie o adresă validă IP.",
        Api_Ip_Incorrect_2: "Adresa IP 2 trebuie să fie o adresă validă IP.",
        Api_Ip_Incorrect_3: "Adresa IP 3 trebuie să fie o adresă validă IP."
      },
      Search: {
        Search_Title: "Termen de căutare",
        Search_Desc_1: "Introduceți cel puțin trei caractere pentru a începe căutarea.",
        Search_Desc_2: "Introduceți un nume de server, uuid sau o adresă pentru a începe căutarea."
      },
      Dashboard: {
        Dash_Page_Title: "Panou de control",
        Dash_Show_Server_1: "Afișează serverele altora",
        Dash_Show_Server_2: "Afișează serverele dvs",
        Dash_Show_Server_3: "Nu există alte servere de afișat.",
        Dash_Show_Server_4: "Nu există servere asociate contului dvs."
      },
      Server_Row: {
        Server_Unlimited: "Nelimitat",
        Server_Suspended: "Suspendat",
        Server_Connect_Error: "Eroare de conexiune",
        Server_Transferring: "Se transferă",
        Server_Installing: "Se instaleză",
        Server_Restoring_Backup: "Restaurarea Copiei de Rezervă",
        Server_Unavailable: "Indisponibil",
        Server_Of: "de"
      },
      Elements: {
        Elements_Cancel_Button: "Anuleză",
        Elements_Copy_Text: "Copiat în clipboard.",
        Elements_Error: "A fost întâlnită o eroare de aplicație la redarea acestei vizualizări. Încercați să reîmprospătați pagina."
      },
      Server: {
        Server_Page_Title: "Consolă",
        Server_Transfer_Console: "Transferul a eșuat.",
        Server_Archived_Console: "Serverul a fost arhivat cu succes, se încearcă conectarea la server..",
        Server_Send_Command: "Introdu o comandă...",
        Server_State_Console: "Server marcat ca ",
        Server_State_Starting: "se pornește",
        Server_State_Offline: "offline",
        Server_State_Stopping: "se oprește",
        Server_State_Running: "rulează",
        Server_State_Connect: "Se conectează...",
        Server_State_Install: "Acest server rulează în prezent procesul de instalare și majoritatea acțiunilor sunt indisponibile.",
        Server_State_Transfer: "Acest server este în prezent transferat către un alt server și toate acțiunile sunt indisponibile.",
        Server_Button_Start: "Pornește",
        Server_Button_Restart: "Re-pornește",
        Server_Button_Kill: "Pune Capăt",
        Server_Button_Stop: "Oprește",
        Server_Memory_Graph_Title: "Utilizare RAM",
        Server_Cpu_Graph_Title: "Utilizare CPU",
        Server_Graph_Desc: "Server-ul este offline.",
        Server_Websocket_Error: "A apărut o eroare la validarea acreditărilor furnizate pentru websocket. Vă rugăm să reîmprospătați pagina.",
        Server_Connect_Server: "Avem unele probleme la conectarea cu serverul dumneavoastra, vă rugăm să așteptați..."
      },
      Server_Backup: {
        Backup_Page_Title: "Backup-uri",
        Backup_Empty_1: "Am rămas fără backup-uri pentru a vă arăta, încercați să reveniți la o pagină.",
        Backup_Empty_2: "Se pare că nu există backup-uri stocate în prezent pentru acest server.",
        Backup_Forbidden: "Nu poți creea backup-uri pe acest server.",
        Backup_Information: "backup-uri au fost create pe acest server.",
        Backup_Create_Title_1: "Crează Backup",
        Backup_Create_Title_2: "Numele backup-ului",
        Backup_Create_Title_3: "Fișiere și foldere ignorate",
        Backup_Create_Title_4: "Blocat",
        Backup_Create_Desc_1: "Dacă este furnizat, numele care ar trebui folosit pentru a face referire la aceast backup.",
        Backup_Create_Desc_2: "Introduceți fișierele sau folderele ignorate în timp ce generați aceast backup. Lăsați necompletat pentru a utiliza conținutul fișierului .pteroignore, dacă este prezent.",
        Backup_Create_Desc_3: "Previne această copie de rezervă să fie ștearsă până când este deblocată.",
        Backup_Create_Start_Button: "Începeți backup",
        Backup_Create_Button: "Creați un backup",
        Backup_Created_Title: "Deblocați aceast backup?",
        Backup_Created_Desc_1: "Sunteți sigur că doriți să deblocați aceast backup? Nu va mai fi protejată de ștergeri automate sau accidentale.",
        Backup_Created_Button: "Da, deblochează",
        Backup_Restore_Title: "Restabiliți aceast backup?",
        Backup_Restore_Desc_1: "Acest server va fi oprit pentru a restabili backup-ul. Odată ce backup-ul a început, nu veți mai putea controla starea de alimentare a serverului, nu veți mai putea accesa managerul de fișiere și nu veți crea copii de rezervă suplimentare până la finalizare.",
        Backup_Restore_Desc_2: "Sunteți sigur că doriți să continuați?",
        Backup_Restore_Desc_3: "Ștergeți toate fișierele și folderele înainte de a restaura această copie de rezervă.",
        Backup_Restore_Button: "Restabiliți backup",
        Backup_Delete_Title: "Ștergeți aceast backup?",
        Backup_Delete_Desc_1: "Sunteți sigur că doriți să ștergeți aceast backup? Aceasta este o operațiune permanentă și backup-ul nu poate fi recuperată odată ce va fi șters.",
        Backup_Delete_Button: "Da, șterge backup",
        Backup_SubMenu_Download: "Descărcă",
        Backup_SubMenu_Restore: "Restaurareză",
        Backup_SubMenu_Unlock: "Deblochează",
        Backup_SubMenu_Lock: "Blocheză",
        Backup_SubMenu_Delete: "Șterge"
      },
      Server_Databases: {
        Database_Page_Title: "Baze de date",
        Database_Show_Empty: "Nu aveți baze de date.",
        Database_Show_Forbidden: "Nu pot fi create baze de date pentru acest server.",
        Database_Limit_Desc: "baze de date au fost alocate acestui server.",
        Database_Create_Title_1: "Creați o nouă bază de date",
        Database_Create_Title_2: "Numele bazei de date",
        Database_Create_Title_3: "Conexiuni de la",
        Database_Create_Desc_1: "Un nume descriptiv pentru baza de date.",
        Database_Create_Desc_2: "De unde ar trebui permise conexiunile. Folosiți % pentru orice conectare.",
        Database_Create_Button_1: "Creează o bază de date",
        Database_Create_Button_2: "Bază de date nouă",
        Database_Create_Error_1: "A fost întâlnită o eroare neașteptată la procesarea acestei solicitări, vă rugăm să încercați din nou.",
        Database_Create_Error_2: "Trebuie furnizat un nume de bază de date.",
        Database_Create_Error_3: "Numele bazei de date trebuie să aibă cel puțin 3 caractere.",
        Database_Create_Error_4: "Numele bazei de date nu trebuie să depășească 48 de caractere.",
        Database_Create_Error_5: "Numele bazei de date trebuie să conțină numai caractere alfanumerice, litere de subliniere, liniuțe și/sau puncte.",
        Database_Create_Error_6: "Trebuie furnizată o valoare de conexiune.",
        Database_Create_Error_7: "Trebuie furnizată o adresă de conexiune validă.",
        Database_Delete_Title_1: "Confirmați ștergerea bazei de date",
        Database_Delete_Title_2: "Confirmați numele bazei de date",
        Database_Delete_Title_3: "Detalii de conectare la baza de date",
        Database_Delete_Title_4: "Date conectare",
        Database_Delete_Title_5: "Conexiuni de la",
        Database_Delete_Title_6: "Nume de utilizator",
        Database_Delete_Title_7: "Parolă",
        Database_Delete_Title_8: "Conexiune JDBC",
        Database_Rotate_Button: "Regenerează parola",
        Database_Delete_Desc_1: `Ștergerea unei baze de date este o acțiune permanentă, nu poate fi anulată. Aceasta acțiune va șterge definitiv baza de date "{{database}}".`,
        Database_Create_Desc_2: "Introduceți numele bazei de date pentru a confirma ștergerea.",
        Database_Delete_Button: "Ștergeți baza de date",
        Database_Delete_Error_1: "Introdu numele bazei de date.",
        Database_Delete_Error_2: "Nu a fost găsită niciun server conectat cu baza de date."
      },
      Server_Files: {
        Files_Page_Title: "Manager de fișiere",
        Files_Create_Button: "Fișier nou",
        Files_Directory_Empty: "Acest folder pare gol.",
        Files_Show_Files_Max: "Acest folder este prea mare pentru a fi afișat în browser, limitând la primele 250 de fișiere.",
        Files_Chmod_Title: "Mod Fișier",
        Files_Chmod_Button: "Actualizare",
        Files_Delete_File_Or_Directory_Title: "Ștergeți aceasta",
        Files_Delete_File_Or_Directory_Button: "Da, șterge",
        Files_Delete_File_Or_Directory_Desc: "Ștergerea fișierelor este o operațiune permanentă, nu puteți anula această acțiune.",
        Files_Delete_File: "Fișier",
        Files_Delete_Directory: "Folder",
        Files_Delete_Title: "Ștergeți aceste fișiere?",
        Files_Delete_Desc_1: "Sunteți sigur că doriți să ștergeți {{selected}} fișier(e)?",
        Files_Delete_Desc_2: "Ștergerea fișierelor enumerate mai jos este o operațiune permanentă, nu puteți anula această acțiune.",
        Files_Delete_Desc_3: "altele",
        Files_Delete_Button: "Da, ștergeți fișierele",
        Files_SubMenu_Rename: "Redenumiți",
        Files_SubMenu_Move: "Mutați",
        Files_SubMenu_Permissions: "Permisiuni",
        Files_SubMenu_Copy: "Copiere",
        Files_SubMenu_Archive: "Arhivare",
        Files_SubMenu_Unarchive: "Dezarhivare",
        Files_SubMenu_Download: "Descărcare",
        Files_SubMenu_Delete: "Șterge",
        Files_Edit_Ptero_Ignore_1: "Ediți un",
        Files_Edit_Ptero_Ignore_2: "fișier. Orice fișiere sau folder enumerate aici vor fi excluse din backup-uri. Wildcards sunt acceptate prin utilizarea unui asterisc",
        Files_Edit_Ptero_Ignore_3: "Puteți anula o regulă anterioară adăugând înainte un semn de exclamare",
        Files_Edit_Save_Button: "Salvați conținutul",
        Files_Create_Title: "Numele fișierului",
        Files_Create_Desc: "Introduceți numele sub care ar trebui să fie salvat acest fișier.",
        Files_Create_Error: "FileName este un câmp obligatoriu",
        Files_Create_Button: "Creați fișierul",
        Files_Message_Archiving: "Fișierele se arhivează...",
        Files_Message_Deleting: "Fișierele se șterg...",
        Files_Create_Directory_Title: "Numele folderului",
        Files_Create_Directory_Desc_1: "Trebuie furnizat un nume valid de foler.",
        Files_Create_Directory_Desc_2: "Acest folder va fi creat ca",
        Files_Create_Directory_Button: "Creați folder",
        Files_Move_Desc_1: "Introduceți noul nume și folderul acestui fișier sau folder, în raport cu folderul curent.",
        Files_Move_Desc_2: "Locație nouă:",
        Files_Drag_Desc: "Trageți și plasați fișiere pentru a le încărca.",
        Files_Drag_Button: "Încărcare",
        Files_Error_1: "Este necesar un nume pentru fișier.",
        Files_Error_2: "A apărut o eroare la server: Nu se poate muta sau redenumi fișierul, destinația există deja.."
      },
      Server_Users: {
        User_Page_Title: "Sub-tilizatori",
        User_Sub_Users_Empty: "Se pare că nu aveți sub-utilizatori.",
        User_Create_Title_1: "Creați un sub-utilizator nou",
        User_Create_Title_2: "Email utilizator",
        User_Create_Sub_User_Desc_1: "Introduceți adresa de email a persoanei pe care doriți să-l invitați ca subutilizator pentru acest server.",
        User_Create_Sub_User_Desc_2: "Adresele de email nu trebuie să depășească 191 de caractere.",
        User_Create_Sub_User_Desc_3: "Trebuie furnizată o adresă de email validă.",
        User_Modify_Or_View_Email_Title: "permisiuni pentru {{subuser}}",
        User_Modify_Title: "Modificare",
        User_View_Title: "Vizualizare",
        User_Modify_Button: "Salvare",
        User_Create_Button_1: "Invitați utilizator",
        User_Create_Button_2: "Utilizator nou",
        User_Create_Sub_User_Desc: "Doar permisiunile cărora le este atribuit în prezent contul dumneavoastră pot fi selectate atunci când creați sau modificați alți utilizatori.",
        User_Delete_Title: "Ștergeți acest subutilizator?",
        User_Delete_Desc_1: "Sunteți sigur că doriți să eliminați acest subutilizator? Aceștia vor avea accesul la acest server revocat imediat.",
        User_Delete_Button: "Da, eliminați sub-utilizatorul",
        User_Show_2FA: "2FA activat",
        User_Show_Permissions: "Permisiuni",
        User_Create_Sub_Title_1: "Control",
        User_Create_Sub_Title_2: "Utilizator",
        User_Create_Sub_Title_3: "Fișier",
        User_Create_Sub_Title_4: "Backup",
        User_Create_Sub_Title_5: "Rețea",
        User_Create_Sub_Title_6: "Pornire",
        User_Create_Sub_Title_7: "Baze de date",
        User_Create_Sub_Title_8: "Programări",
        User_Create_Sub_Title_9: "Setări",
        User_Create_Desc_1: "Permisiuni care controlează capacitatea utilizatorilor de a controla starea de alimentare a unui server sau de a trimite comenzi.",
        User_Create_Desc_2: "Permisiuni care permit unui utilizator să gestioneze alți subutilizatori pe un server. Ei nu vor putea niciodată să-și editeze propriul cont sau să atribuie permisiuni pe care nu le au ei înșiși.",
        User_Create_Desc_3: "Permisiuni care controlează capacitatea unui utilizator de a modifica sistemul de fișiere pentru acest server.",
        User_Create_Desc_4: "Permisiuni care controlează capacitatea unui utilizator de a genera și gestiona copii de rezervă ale serverului.",
        User_Create_Desc_5: "Permisiuni care controlează capacitatea unui utilizator de a modifica alocările de porturi pentru acest server.",
        User_Create_Desc_6: "Permisiuni care controlează capacitatea unui utilizator de a vedea parametrii de pornire ai acestui server.",
        User_Create_Desc_7: "Permisiuni care controlează accesul unui utilizator la gestionarea bazei de date pentru acest server.",
        User_Create_Desc_8: "Permisiuni care controlează accesul unui utilizator la gestionarea programului pentru acest server.",
        User_Create_Desc_9: "Permisiuni care controlează accesul unui utilizator la setările pentru acest server.",
        User_Create_Option_Desc_1: "Consolă",
        User_Create_Option_Desc_2: "Pornește",
        User_Create_Option_Desc_3: "Oprește",
        User_Create_Option_Desc_4: "Restarteză",
        User_Create_Option_Desc_5: "Creează",
        User_Create_Option_Desc_6: "Citește",
        User_Create_Option_Desc_7: "Actualizeză",
        User_Create_Option_Desc_8: "Șterge",
        User_Create_Option_Desc_9: "Citește conținut",
        User_Create_Option_Desc_10: "Arhiveză",
        User_Create_Option_Desc_11: "SFTP",
        User_Create_Option_Desc_12: "Descărcă",
        User_Create_Option_Desc_13: "Restaurare",
        User_Create_Option_Desc_14: "Imagine-docker",
        User_Create_Option_Desc_15: "Vizualizare parolă",
        User_Create_Option_Desc_16: "Redenumește",
        User_Create_Option_Desc_17: "Reinstaleză",
        User_Create_Option_Description_1: "Permite unui utilizator să trimită comenzi instanței de server prin consolă.",
        User_Create_Option_Description_2: "Permite unui utilizator să pornească serverul dacă acesta este oprit.",
        User_Create_Option_Description_3: "Permite unui utilizator să oprească un server dacă rulează.",
        User_Create_Option_Description_4: "Permite unui utilizator să efectueze o repornire a serverului. Acest lucru îi permite să pornească serverul dacă este offline, dar nu pune serverul într-o stare complet oprită.",
        User_Create_Option_Description_5: "Permite unui utilizator să creeze noi subutilizatori pentru server.",
        User_Create_Option_Description_6: "Permite utilizatorului să vadă subutilizatorii și permisiunile acestora pentru server.",
        User_Create_Option_Description_7: "Permite unui utilizator să modifice alți subutilizatori.",
        User_Create_Option_Description_8: "Permite unui utilizator să șteargă un subutilizator de pe server.",
        User_Create_Option_Description_9: "Permite unui utilizator să creeze fișiere și foldere suplimentare prin intermediul panoului sau să încarce direct.",
        User_Create_Option_Description_10: "Permite unui utilizator să vadă conținutul unui director, dar nu să vadă conținutul sau să descarce fișiere.",
        User_Create_Option_Description_11: "Permite unui utilizator să vadă conținutul unui anumit fișier. Acest lucru va permite și utilizatorului să descarce fișiere.",
        User_Create_Option_Description_12: "Permite unui utilizator să actualizeze conținutul unui fișier sau director existent.",
        User_Create_Option_Description_13: "Permite unui utilizator să șteargă fișiere sau directoare.",
        User_Create_Option_Description_14: "Permite unui utilizator să arhiveze conținutul unui director, precum și să decomprimeze arhivele existente pe sistem.",
        User_Create_Option_Description_15: "Permite unui utilizator să se conecteze la SFTP și să gestioneze fișierele serverului folosind celelalte permisiuni de fișiere alocate.",
        User_Create_Option_Description_16: "Permite unui utilizator să creeze copii de rezervă noi pentru acest server.",
        User_Create_Option_Description_17: "Permite unui utilizator să vadă toate copiile de rezervă care există pentru acest server.",
        User_Create_Option_Description_18: "Permite unui utilizator să elimine copiile de rezervă din sistem.",
        User_Create_Option_Description_19: "Permite unui utilizator să descarce o copie de rezervă pentru server. Pericol: aceasta permite unui utilizator să acceseze toate fișierele pentru server din backup.",
        User_Create_Option_Description_20: "Permite unui utilizator să restaureze o copie de rezervă pentru server. Pericol: aceasta permite utilizatorului să șteargă toate fișierele serverului din proces.",
        User_Create_Option_Description_21: "Permite unui utilizator să vadă toate alocările alocate în prezent acestui server. Utilizatorii cu orice nivel de acces la acest server pot vedea întotdeauna alocarea principală.",
        User_Create_Option_Description_22: "Permite unui utilizator să atribuie alocări suplimentare serverului.",
        User_Create_Option_Description_23: "Permite unui utilizator să modifice alocarea serverului principal și să atașeze note la fiecare alocare.",
        User_Create_Option_Description_24: "Permite unui utilizator să șteargă o alocare de pe server.",
        User_Create_Option_Description_25: "Permite unui utilizator să vadă variabilele de pornire pentru un server.",
        User_Create_Option_Description_26: "Permite unui utilizator să modifice variabilele de pornire pentru server.",
        User_Create_Option_Description_27: "Permite unui utilizator să modifice imaginea Docker folosită atunci când rulează serverul.",
        User_Create_Option_Description_28: "Permite unui utilizator să creeze o nouă bază de date pentru acest server.",
        User_Create_Option_Description_29: "Permite unui utilizator să vadă baza de date asociată cu acest server.",
        User_Create_Option_Description_30: "Permite unui utilizator să rotească parola într-o instanță de bază de date. Dacă utilizatorul nu are permisiunea view_password, nu va vedea parola actualizată.",
        User_Create_Option_Description_31: "Permite unui utilizator să elimine o instanță de bază de date de pe acest server.",
        User_Create_Option_Description_32: "Permite unui utilizator să vadă parola asociată cu o instanță de bază de date pentru acest server.",
        User_Create_Option_Description_33: "Permite unui utilizator să creeze noi programe pentru acest server.",
        User_Create_Option_Description_34: "Permite unui utilizator să vadă programele și sarcinile asociate cu acestea pentru acest server.",
        User_Create_Option_Description_35: "Permite unui utilizator să actualizeze programele și să programeze sarcini pentru acest server.",
        User_Create_Option_Description_36: "Permite unui utilizator să șteargă programele pentru acest server.",
        User_Create_Option_Description_37: "Permite unui utilizator să redenumească acest server.",
        User_Create_Option_Description_38: "Permite unui utilizator să declanșeze o reinstalare a acestui server."
      },
      Server_Network: {
         Network_Page_Title: "Rețea",
         Network_Alocations_Desc_1: "În prezent utilizați {{data}} din {{limit}} alocații permise pentru acest server.",
         Network_Create_Alocation_Button: "Creați o alocare",
         Network_Hostname: "Nume gazdă",
         Network_IP_Address: "Adresă IP",
         Network_Port: "Port",
         Network_Notes: "Descriere",
         Network_Primary: "Primar",
         Network_Primary_Button: "Faceți principal",
         Network_Delete_Title: "Șterge această alocare?",
         Network_Delete_Button: "Șterge",
         Network_Delete_Desc_1: "Această alocare va fi imediat eliminată de pe serverul dumneavoastră. Sigur doriți să continuați?",
         Network_Error_1: "Alocarea automată a serverului nu este activată pentru aceast server.",
       },
      Server_Schedules: {
        Task_Page_Title: "Programări",
        Task_Empty_Message: "Nu există programări configurate pentru acest server.",
        Task_Create_Button: "Creează Programare",
        Task_Edit_Button: "Salvați modificările",
        Task_Delete_Title: "Ștergeți programarea?",
        Task_Delete_Button_1: "Da, ștergeți programarea",
        Task_Delete_Desc: "Sunteți sigur că doriți să ștergeți acest programarea? Toate sarcinile vor fi eliminate și toate procesele care rulează vor fi încheiate.",
        Task_Delete_Button_2: "Șterge",
        Task_Create_Title: "Crează o programarea nouă",
        Task_Edit_Title: "Editați programarea",
        Task_Create_Or_Edit_Title_1: "Numele programarii",
        Task_Create_Or_Edit_Title_2: "Doar când serverul este online",
        Task_Create_Or_Edit_Title_3: "Programare activată",
        Task_Create_Or_Edit_Desc_1: "Un identificator care poate fi citit de om pentru acest program.",
        Task_Create_Or_Edit_Desc_2: "Sistemul de planificare acceptă utilizarea sintaxei Cronjob atunci când se definește când sarcinile ar trebui să înceapă să ruleze. Utilizați câmpurile de mai sus pentru a specifica când aceste sarcini ar trebui să înceapă să ruleze.",
        Task_Create_Or_Edit_Desc_3: "Execută această programare numai când serverul este într-o stare de rulare.",
        Task_Create_Or_Edit_Desc_4: "Acestă programarea va fi executat automat dacă este activată.",
        Task_Create_Or_Edit_Minute: "Minut",
        Task_Create_Or_Edit_Hour: "Oră",
        Task_Create_Or_Edit_Day_Of_Month: "Ziua lunii",
        Task_Create_Or_Edit_Month: "Lună",
        Task_Create_Or_Edit_Day_Of_Week: "Ziua săptămânii",
        Task_New_Task_Button: "Sarcina nouă",
        Task_Run_Task_Button: "Rulează acum",
        Task_Cron_Row_Minute: "Minut",
        Task_Cron_Row_Hour: "Oră",
        Task_Cron_Row_Day_Month: "Ziua (în lună)",
        Task_Cron_Row_Month: "Lună",
        Task_Cron_Row_Day_Week: "Ziua (în săptămâna)",
        Task_Task_Page_Title: "Sarcini",
        Task_Task_Processing: "Se procesează",
        Task_Task_Last_Run: "Ultima rulare la:",
        Task_Task_Next_Run: "Următoarea rulare la:",
        Task_Task_Never: "Niciodată",
        Task_Task_NA: "n/a",
        Task_Task_Edit_Button: "Editare",
        Task_Task_Active: "Activ",
        Task_Task_Inactive: "Inactiv",
        Task_Task_Delete_Title: "Confirmeză ștergerea sarciniilor",
        Task_Task_Delete_Button: "Ștergeți sarcina",
        Task_Task_Delete_Desc: "Sunteți sigur că doriți să ștergeți această sarcină? Această acțiune nu poate fi anulată.",
        Task_Task_Files_And_Folders_Message: "Ignorarea fișierelor și folderelor:",
        Task_Task_Continue_Message: "Continuă chiar dacă esuează",
        Task_Task_Time_Message: "{{time}} mai târziu",
        Task_Task_Edit_Title: "Editați sarcina",
        Task_Task_Create_Title: "Creați o sarcină",
        Task_Task_Create_Or_Edit_Command: "Trimite comanda",
        Task_Task_Create_Or_Edit_Power: "Trimiteți acțiunea de statut",
        Task_Task_Create_Or_Edit_Backup: "Creați o copie de rezervă",
        Task_Task_Create_Or_Edit_Title_1: "Decalaj de timp (în secunde)",
        Task_Task_Create_Or_Edit_Title_2: "Sarcă utilă",
        Task_Task_Create_Or_Edit_Title_3: "Fișiere ignorate",
        Task_Task_Create_Or_Edit_Title_4: "Continuați la eșec",
        Task_Task_Create_Or_Edit_Title_5: "Acțiune",
        Task_Task_Create_Or_Edit_Desc_1: "Timpul de așteptare după ce sarcina anterioară se execută înainte de a rula aceasta. Dacă aceasta este prima sarcină dintr-o programare, aceasta nu va fi aplicată.",
        Task_Task_Create_Or_Edit_Desc_2: "Opțional. Includeți fișierele și folderele care vor fi excluse în această copie de rezervă. În mod implicit, conținutul fișierului dvs. .pteroignore va fi folosit. Dacă ați atins limita de rezervă, cea mai veche copie de rezervă va fi rotită.",
        Task_Task_Create_Or_Edit_Desc_3: "Sarcinile viitoare vor fi executate când această sarcină eșuează.",
        Task_Task_Create_Or_Edit_Option_1: "Porniți serverul",
        Task_Task_Create_Or_Edit_Option_2: "Reporniți serverul",
        Task_Task_Create_Or_Edit_Option_3: "Opriți serverul",
        Task_Task_Create_Or_Edit_Option_4: "Închideți serverul",
        Task_Task_Create_Or_Edit_Error_1: "Trebuie furnizată o sarcină utilă.",
        Task_Task_Create_Or_Edit_Error_2: "Decalajul de timp trebuie să fie un număr valid între 0 și 900.",
        Task_Task_Create_Or_Edit_Error_3: "Trebuie furnizată o valoare a decalajului de timp.",
        Task_Task_Create_Or_Edit_Error_4: "Decalajul de timp trebuie să fie de cel puțin 0 secunde.",
        Task_Task_Create_Or_Edit_Error_5: "Decalajul de timp trebuie să fie mai mic de 900 de secunde.",
        Task_Task_Create_Or_Edit_Error_6: "O sarcină de backup nu poate fi creată când limita de backup a serverului este setată la 0."
      },
      Server_Settings: {
        Settings_Page_Title: "Setări",
        Settings_SFTP_Title_1: "Detalii SFTP",
        Settings_SFTP_Title_2: "Adresă Server",
        Settings_SFTP_Title_3: "Nume de utilizator",
        Settings_SFTP_Desc_1: "Parola dvs. SFTP este aceeași parolă pe care o utilizați pentru a accesa acest panou.",
        Settings_SFTP_Button: "Lanseză SFTP",
        Settings_Debug_Title_1: "Informații pentru Debug",
        Settings_Debug_Title_2: "Server",
        Settings_Debug_Title_3: "ID Server",
        Settings_Reinstall_Title_1: "Reinstaleză serverul",
        Settings_Reinstall_Title_2: "Confirmă reinstalarea serverului",
        Settings_Reinstall_Button: "Da, reinstalează serverul",
        Settings_Reinstall_Desc_1: "Serverul dvs. va fi oprit și unele fișiere pot fi șterse sau modificate în timpul acestui proces, sunteți sigur că doriți să continuați?",
        Settings_Reinstall_Desc_2: "Reinstalarea serverului îl va opri, apoi va rula din nou scriptul de instalare.",
        Settings_Reinstall_Desc_3: "Unele fișiere pot fi șterse sau modificate în timpul acestui proces, vă rugăm să faceți o copie de rezervă a datelor înainte de a continua.",
        Settings_Reinstall_Success: "Serverul dvs. a început procesul de instalare.",
        Settings_Reinstall_Error: "Nu s-a putut stabili o conexiune la serverul ce rulează acest server. Vă rugăm să încercați din nou.",
        Settings_Rename_Server_Title_1: "Schimba numele serverului",
        Settings_Rename_Server_Title_2: "Nume Server",
        Settings_Rename_Server_Button: "Savează",
        Settings_Rename_Required: "Numele este un câmp obligatoriu"
      },
      Server_Startup: {
        Startup_Page_Title: "Parametrii Pornire",
        Startup_Command_Title_1: "Comanda pornire",
        Startup_Docker_Title: "Imagine Docker",
        Startup_Docker_Desc: "Aceasta este o setare avansată care vă permite să selectați o Imagine Docker pe care să o utilizați atunci când rulați aceast server.",
        Startup_Docker_Error: "Imaginea Docker a acestui server a fost setată manual de un administrator și nu poate fi modificată de dumneavoastră.",
        Startup_Variables_Title: "Variabile",
        Startup_Variables_Read: "Doar Citire",
        Startup_Server_Error_Title: "Oops!",
      },
      Server_Features: {
        Features_Invalid_Java_Title_1: "Versiunea Java invalidă, actualizați Imaginea Docker?",
        Features_Invalid_Java_Desc_1: "Acest server nu poate porni deoarece versiunea Java necesară nu este selectată.",
        Features_Invalid_Java_Desc_2: `Apăsând pe „Actualizați Imaginează Docker” de mai jos, confirmați că imaginea Docker pe care o folosește acest server va fi schimbată într-o imagine de mai jos care are versiunea Java pe care o solicitați.`,
        Features_Invalid_Java_Desc_3: "Vă rugăm să selectați o versiune Java din lista de mai jos.",
        Features_Invalid_Java_Button_1: "Actualizați Imaginează Docker",
        Features_Invalid_Java_Button_2: "Anuleză",
        Features_Accept_Eula_Title: "Accept Minecraft® EULA",
        Features_Accept_Eula_Desc_1: `Apăsând pe „Eu accept” de mai jos, indicați acordul dvs. cu privire la`,
        Features_Accept_Eula_Desc_2: "Minecraft® EULA",
        Features_Accept_Eula_Button_1: "Eu accept",
        Features_Accept_Eula_Button_2: "Anuleză",
        Features_Invalid_GSL_Title: "Token GSL invalid!",
        Features_Invalid_GSL_Desc_1: "Se pare că simbolul tău de conectare la serverul de jocuri (indicativ GSL) este invalid sau a expirat.",
        Features_Invalid_GSL_Desc_2: "Puteți fie să generați unul nou și să îl introduceți mai jos, fie să lăsați câmpul necompletat pentru a-l elimina complet.",
        Features_Invalid_GSL_Desc_3: "Token GSL",
        Features_Invalid_GSL_Desc_4: "Vizitați https://steamcommunity.com/dev/managegameservers pentru a genera un token.",
        Features_Invalid_GSL_Button: "Actualizați tokenul GSL",
        Features_Invalid_PID_Title_1: "Limita de memorie sau proces atinsă...",
        Features_Invalid_PID_Title_2: "Limita posibilă de resurse a fost atinsă...",
        Features_Invalid_PID_Desc_1: "Acest server a atins limita maximă de proces sau memorie.",
        Features_Invalid_PID_Desc_2: "În creștere",
        Features_Invalid_PID_Desc_3: "container_pid_limit",
        Features_Invalid_PID_Desc_4: "în configurația aripi",
        Features_Invalid_PID_Desc_5: "config.yml",
        Features_Invalid_PID_Desc_6: ", ar putea ajuta la rezolvarea acestei probleme.",
        Features_Invalid_PID_Desc_7: "Notă: Wings trebuie repornit pentru ca modificările fișierului de configurare să aibă efect",
        Features_Invalid_PID_Desc_8: "Acest server încearcă să folosească mai multe resurse decât alocate. Vă rugăm să contactați administratorul și să îi transmiteți eroarea de mai jos.",
        Features_Invalid_PID_Desc_9: "pthread_create nu a reușit, posibil memorie lipsită sau limitele de proces/resurse atinse",
        Features_Invalid_Disk_Title: "Spațiu disponibil pe disc...",
        Features_Invalid_Disk_Desc_1: "Acest server a rămas fără spațiu disponibil pe disc și nu poate finaliza procesul de instalare sau actualizare.",
        Features_Invalid_Disk_Desc_2: "Asigurați-vă că aparatul are suficient spațiu pe disc tastând",
        Features_Invalid_Disk_Desc_3: "df -h",
        Features_Invalid_Disk_Desc_4: "pe mașina care găzduiește acest server. Ștergeți fișierele sau măriți spațiul disponibil pe disc pentru a rezolva problema.",
        Features_Invalid_Disk_Desc_5: "Acest server a epuizat spațiul disponibil pe disc și nu poate finaliza procesul de instalare sau actualizare. Vă rugăm să luați legătura cu administratorul(i) și să-i informați despre problemele legate de spațiul pe disc.",
      },
      Server_States: {
        Server_Installing_Title: "Se instaleză",
        Server_Installing_Desc: "Serverul dvs. ar trebui să fie gata în curând, vă rugăm să verificați din nou peste câteva minute.",
        Server_Suspended_Title: "Server Suspendat",
        Server_Suspended_Desc: "Acest server este suspendat și nu poate fi accesat.",
        Server_Transferring_Title: "Se transferă",
        Server_Transferring_Desc: "Serverul dvs. este transferat pe un server nou, vă rugăm să verificați din nou peste câteva minute.",
        Server_Restoring_Title: "Restaurare din Backup",
        Server_Restoring_Desc: "Serverul dvs. este restaurat dintr-o copie de rezervă, vă rugăm să verificați din nou peste câteva minute."
      },
      Page_Titles: {
        Title_Console: "Consolă",
        Title_File_Manager: "Manager Fișiere",
        Title_Databases: "Baze de date",
        Title_Schedules: "Programări",
        Title_Users: "Sub-tilizatori",
        Title_Backups: "Backup-uri",
        Title_Network: "Rețea",
        Title_Startup: "Pornire",
        Title_Settings: "Setări",
        Title_API_Credentials: "Date API"
      },
      Times_And_Dates: {
        Date_Format: "dd'-'MM'-'yyyy h:mma", // For details about formats, look at this: https://thecodebarbarian.com/formatting-javascript-dates-with-moment-js.html
        Time_Minutes_1: "4 Minute în urmă",
        Time_Minutes_2: "3 Minute în urmă",
        Time_Minutes_3: "2 Minute în urmă",
        Time_Minutes_4: "1 Minute în urmă",
        Time_Minutes_5: "Mai puțin de un minut",
        Time_Minutes_6: "Mai puțin de un minut în urmă",
        Time_Minutes_7: "1 Minut în urmă",
        Time_Minutes_8: "2 Minute în urmă",
        Time_Minutes_9: "3 Minute în urmă",
        Time_Minutes_10: "4 Minute în urmă",
        Time_Minutes_11: "5 Minute în urmă",
        Time_Minutes_12: "6 Minute în urmă",
        Time_Minutes_13: "7 Minute în urmă",
        Time_Minutes_14: "8 Minute în urmă",
        Time_Minutes_15: "9 Minute în urmă",
        Time_Minutes_16: "10 Minute în urmă",
        Time_Minutes_17: "11 Minute în urmă",
        Time_Minutes_18: "12 Minute în urmă",
        Time_Minutes_19: "13 Minute în urmă",
        Time_Minutes_20: "14 Minute în urmă",
        Time_Minutes_21: "15 Minute în urmă",
        Time_Minutes_22: "16 Minute în urmă",
        Time_Minutes_23: "17 Minute în urmă",
        Time_Minutes_24: "18 Minute în urmă",
        Time_Minutes_25: "19 Minute în urmă",
        Time_Minutes_26: "20 Minute în urmă",
        Time_Minutes_27: "21 Minute în urmă",
        Time_Minutes_28: "22 Minute în urmă",
        Time_Minutes_29: "23 Minute în urmă",
        Time_Minutes_30: "24 Minute în urmă",
        Time_Minutes_31: "25 Minute în urmă",
        Time_Minutes_32: "26 Minute în urmă",
        Time_Minutes_33: "27 Minute în urmă",
        Time_Minutes_34: "28 Minute în urmă",
        Time_Minutes_35: "29 Minute în urmă",
        Time_Minutes_36: "30 Minute în urmă",
        Time_Minutes_37: "31 Minute în urmă",
        Time_Minutes_38: "32 Minute în urmă",
        Time_Minutes_39: "33 Minute în urmă",
        Time_Minutes_40: "34 Minute în urmă",
        Time_Minutes_41: "35 Minute în urmă",
        Time_Minutes_42: "36 Minute în urmă",
        Time_Minutes_43: "37 Minute în urmă",
        Time_Minutes_44: "38 Minute în urmă",
        Time_Minutes_45: "39 Minute în urmă",
        Time_Minutes_46: "40 Minute în urmă",
        Time_Minutes_47: "41 Minute în urmă",
        Time_Minutes_48: "42 Minute în urmă",
        Time_Minutes_49: "43 Minute în urmă",
        Time_Minutes_50: "44 Minute în urmă",
        Time_Minutes_51: "45 Minute în urmă",
        Time_Minutes_52: "46 Minute în urmă",
        Time_Minutes_53: "47 Minute în urmă",
        Time_Minutes_54: "48 Minute în urmă",
        Time_Minutes_55: "49 Minute în urmă",
        Time_Minutes_56: "50 Minute în urmă",
        Time_Minutes_57: "51 Minute în urmă",
        Time_Minutes_58: "52 Minute în urmă",
        Time_Minutes_59: "53 Minute în urmă",
        Time_Minutes_60: "54 Minute în urmă",
        Time_Minutes_61: "55 Minute în urmă",
        Time_Minutes_62: "56 Minute în urmă",
        Time_Minutes_63: "57 Minute în urmă",
        Time_Minutes_64: "58 Minute în urmă",
        Time_Minutes_65: "59 Minute în urmă",
        Time_Hours_1: "1 Oră în urmă",
        Time_Hours_2: "2 Ore în urmă",
        Time_Hours_3: "3 Ore în urmă",
        Time_Hours_4: "4 Ore în urmă",
        Time_Hours_5: "5 Ore în urmă",
        Time_Hours_6: "6 Ore în urmă",
        Time_Hours_7: "7 Ore în urmă",
        Time_Hours_8: "8 Ore în urmă",
        Time_Hours_9: "9 Ore în urmă",
        Time_Hours_10: "10 Ore în urmă",
        Time_Hours_11: "11 Ore în urmă",
        Time_Hours_12: "12 Ore în urmă",
        Time_Hours_13: "13 Ore în urmă",
        Time_Hours_14: "14 Ore în urmă",
        Time_Hours_15: "15 Ore în urmă",
        Time_Hours_16: "16 Ore în urmă",
        Time_Hours_17: "17 Ore în urmă",
        Time_Hours_18: "18 Ore în urmă",
        Time_Hours_19: "19 Ore în urmă",
        Time_Hours_20: "20 Ore în urmă",
        Time_Hours_21: "21 Ore în urmă",
        Time_Hours_22: "22 Ore în urmă",
        Time_Hours_23: "23 Ore în urmă",
        Time_Days_1: "1 zi în urmă",
        Time_Days_2: "2 zile în urmă"
      },
      Errors: {
        Error_Key_Undefined: "Eroare internă: cheia pentru acest mesaj nu a fost setată, contactați autorul: Ferks#7575",
        Error_Server_Title: "Ceva nu a mers bine",
        Error_Server_Desc: "Resursa solicitată nu a fost găsită.",
        Error_Connection: "A apărut o eroare la comunicarea cu host-ul ce găzduieste acest server. Această eroare a fost înregistrată, vă rugăm să încercați din nou.",
        Error_Network: "Eroare de Rețea",
        Error_Permission_Title: "Acces Interzis",
        Error_Permission_Desc: "Nu aveți permisiunea de a accesa această pagină.",
        Error_Variables_1: "Câmpul este obligatoriu.",
        Error_Variables_2: "Valoarea trebuie să fie de 1 cifră.",
        Error_Variables_3: "Valoarea invalidă.",
        Error_Variables_4: "Valoarea trebuie să fie de cel puțin 1.",
        Error_Variables_5: "Această valoare este mai mare decât limita.",
        Error_Variables_6: "Formatarea valorii este invalidă.",
        Error_Variables_7: "Valoarea poate conține doar litere, cifre și liniuțe."
      },
    }
}
