export default {
    translation: {
      Login: {
        Title: "Войдите, чтобы продолжить",
        Username_or_Email: "Имя пользователя или электронная почта",
        Password: "Пароль",
        Login_Button: "Вход в систему",
        Forgot_Password: "Забыли пароль?",
        Username_or_Email_Desc: "Необходимо указать имя пользователя или электронную почту.",
        Account_Password_Desc: "Пожалуйста, введите пароль вашей учетной записи.",
        Account_Incorrect: "Учетной записи, соответствующей этим учетным данным, найти не удалось.",
        Many_Attempts: "Было слишком много попыток входа в систему. Пожалуйста, повторите попытку позже.",
        Recaptcha_Error: "Не удалось проверить данные reCAPTCHA.",
        Request_Failed: "Запрос не прошел с кодом состояния 404",
        CSRF_Token: "Несоответствие маркера CSRF."
      },
      Reset_Password: {
        Password_Reset: "Запрос на сброс пароля",
        Email: "Электронная почта",
        New_Password_Required: "Необходимо ввести новый пароль.",
        Password_Characters_Min: "Длина вашего нового пароля должна составлять не менее 8 символов.",
        Password_Not_Match: "Ваш новый пароль не совпадает.",
        Account_Email: "Введите адрес электронной почты вашей учетной записи, чтобы получить инструкции по сбросу пароля.",
        Valid_Email: "Для продолжения необходимо указать действительный адрес электронной почты.",
        Send_Email: "Отправить электронное письмо",
        Return_to_Login: "Вернуться к входу в систему",
        Reset_Password: "Сброс пароля",
        New_Password: "Новый пароль",
        New_Password_Desc: "Длина пароля должна составлять не менее 8 символов.",
        Confirm_New_Password: "Подтверждение нового пароля",
        Send_Email_Link: "Мы отправили вам ссылку для восстановления пароля по электронной почте!"
      },
      Two_Factor_Auth: {
        Device_Checkpoint: "Контрольная точка устройства",
        Recovery_Code: "Код восстановления",
        Authentication_Code: "Код аутентификации",
        Enter_Two_Factor_Desc_1: "Введите двухфакторный токен, сгенерированный вашим устройством.",
        Enter_Two_Factor_Desc_2: "Введите один из кодов восстановления, сгенерированных при настройке двухфакторной аутентификации на этой учетной записи, чтобы продолжить.",
        Lost_Device: "Я потерял свое устройство",
        Have_Device: "У меня есть устройство",
        Continue: "Продолжить"
      },
      Account_Overview: {
        Two_Factor_Activate_Desc_1: "Для продолжения необходимо ввести код аутентификации.",
        Two_Factor_Activate_Desc_2: "В настоящее время на вашей учетной записи включена двухфакторная аутентификация.",
        Two_Factor_Activate_Desc_3: "Код аутентификатора должен состоять из 6 цифр.",
        Two_Factor_Active_Title: "Двухфакторная аутентификация включена",
        Two_Factor_Active_Desc_1: "На вашем аккаунте включена двухфакторная аутентификация. Если вы потеряете доступ к своему устройству аутентификации, вам нужно будет использовать один из кодов, показанных ниже, чтобы получить доступ к своей учетной записи.",
        Two_Factor_Active_Desc_2: "Эти коды больше не будут отображаться. ",
        Two_Factor_Active_Desc_3: "Пожалуйста, запомните их сейчас и храните в надежном хранилище, например, в менеджере паролей.",
        Two_Factor_Active_Button: "Закрыть",
        Two_Factor_Disabled_Desc: "В настоящее время на вашей учетной записи не включена двухфакторная аутентификация. Нажмите кнопку ниже, чтобы начать ее настройку.",
        Two_Factor_Disable_Desc_1: "Для продолжения вы должны указать свой текущий пароль.",
        Two_Factor_Disable_Desc_2: "Чтобы отключить двухфакторную аутентификацию, вам нужно будет сообщить пароль своей учетной записи.",
        Two_Factor_Disable_Title: "Текущий пароль",
        Two_Factor_Disable_Button: "Отключить двухфакторный режим",
        Two_Factor_Setup_Desc_1: "Введите код с устройства аутентификации после сканирования QR-изображения.",
        Two_Factor_Setup_Desc_2: "В качестве альтернативы введите следующий токен в приложение аутентификатора:",
        Two_Factor_Setup_Button: "Настройка",
        Two_Factor_Incorrect_Password: "Указанный пароль недействителен.",
        Button_Disable: "Отключить",
        Button_Enable: "Включить",
        Create_Api_Desc_Title: "Описание",
        Create_Api_Desc: "Описание этого ключа API.",
        Create_Api_Ips_Title: "Разрешенные IP-адреса",
        Create_Api_Ips_Desc: "Оставьте пустым, чтобы разрешить любому IP-адресу использовать этот ключ API, в противном случае укажите каждый IP-адрес в новой строке.",
        Create_Api_Button: "Создать",
        Update_Email_Desc_1: "Вы должны указать текущий пароль учетной записи.",
        Update_Email_Required: "Электронная почта является обязательным полем",
        Update_Email_Success_Title: "Успех",
        Update_Email_Success: "Ваш основной адрес электронной почты был обновлен.",
        Update_Email_Error_Title: "Ошибка",
        Update_Email_Button: "Обновление электронной почты",
        Update_Password_Title: "Новый пароль",
        Update_Password_Desc_1: "Вы должны указать свой текущий пароль.",
        Update_Password_Desc_2: "Подтверждение пароля не соответствует введенному вами паролю.",
        Update_Password_Desc_3: "Ваш новый пароль должен состоять не менее чем из 8 символов и быть уникальным для этого сайта.",
        Update_Password_Required: "Пароль является обязательным полем",
        Update_Password_Button: "Обновить пароль",
        Update_Password_Error: "Предоставленный пароль был недействителен для этой учетной записи.",
        Update_Password_Min: "Пароль должен состоять не менее чем из 8 символов",
        Confirm_Password: "Подтверждение пароля",
        Account_Page_Title: "Обзор счета",
        Account_Two_Factor_Required_Title: "Требуется 2-факторный",
        Account_Two_Factor_Required_Desc: "Чтобы продолжить, в вашей учетной записи должна быть включена двухфакторная аутентификация.",
        Account_Update_Email_Title: "Обновить адрес электронной почты",
        Account_Setup_Two_Factor_Title: "Настройка двух факторов",
        Api_Page_Title: "API учетной записи",
        Api_Create_Title: "Создайте ключ API",
        Api_List_Title: "API-ключи",
        Api_List_Loading: "Загрузка...",
        Api_List_Empty: "Для этой учетной записи не существует ключей API.",
        Api_List_Used_1: "Последнее использование: ",
        Api_List_Used_2: "Никогда",
        Api_Delete_Title: "Подтверждение удаления клавиш",
        Api_Delete_Button: "Да, клавиша удаления",
        Api_Delete_Desc: "Вы уверены, что хотите удалить этот ключ API? Все запросы, использующие его, будут немедленно признаны недействительными и будут отклонены.",
        Api_Setup_Title: "Ваш ключ API",
        Api_Setup_Desc: "Запрошенный вами ключ API показан ниже. Пожалуйста, храните его в безопасном месте, он больше не будет показан.",
        Api_Min_Characters: "Описание должно содержать не менее 4 символов",
        Api_Setup_Button: "Закрыть",
        Api_Ip_Incorrect_1: "IP-адрес 1 должен быть действительным IP-адресом.",
        Api_Ip_Incorrect_2: "IP-адрес 2 должен быть действительным IP-адресом.",
        Api_Ip_Incorrect_3: "IP-адрес 3 должен быть действительным IP-адресом."
      },
      Search: {
        Search_Title: "Поисковый термин",
        Search_Desc_1: "Пожалуйста, введите не менее трех символов, чтобы начать поиск.",
        Search_Desc_2: "Введите имя сервера, uuid или распределение, чтобы начать поиск."
      },
      Dashboard: {
        Dash_Page_Title: "Приборная панель",
        Dash_Show_Server_1: "Показывать чужие серверы",
        Dash_Show_Server_2: "Показывать свои серверы",
        Dash_Show_Server_3: "Других серверов для отображения нет.",
        Dash_Show_Server_4: "Нет никаких серверов, связанных с вашей учетной записью."
      },
      Server_Row: {
        Server_Unlimited: "Неограниченный",
        Server_Suspended: "Приостановлено",
        Server_Connect_Error: "Ошибка подключения",
        Server_Transferring: "Передача",
        Server_Installing: "Установка",
        Server_Restoring_Backup: "Восстановление резервной копии",
        Server_Unavailable: "Недоступно",
        Server_Of: "из"
      },
      Elements: {
        Elements_Cancel_Button: "Отмена",
        Elements_Copy_Text: "Копируется в буфер обмена.",
        Elements_Error: "Во время рендеринга этого представления приложение столкнулось с ошибкой. Попробуйте обновить страницу."
      },
      Server: {
        Server_Page_Title: "Консоль",
        Server_Transfer_Console: "Передача не удалась.",
        Server_Archived_Console: "Сервер успешно архивирован, попытка подключения к целевому узлу...",
        Server_Send_Command: "Введите команду...",
        Server_State_Console: "Сервер помечен как ",
        Server_State_Starting: "начало",
        Server_State_Offline: "оффлайн",
        Server_State_Stopping: "остановка",
        Server_State_Running: "работает",
        Server_State_Connect: "Подключение...",
        Server_State_Install: "В настоящее время на этом сервере идет процесс установки, и большинство действий недоступно.",
        Server_State_Transfer: "В настоящее время этот сервер передается другому узлу, и все действия недоступны.",
        Server_Button_Start: "Дом",
        Server_Button_Restart: "Перезапустите",
        Server_Button_Kill: "Убей",
        Server_Button_Stop: "Стоп",
        Server_Memory_Graph_Title: "Использование памяти",
        Server_Cpu_Graph_Title: "Использование процессора",
        Server_Graph_Desc: "Сервер находится в автономном режиме.",
        Server_Websocket_Error: "Произошла ошибка при проверке учетных данных, предоставленных для веб-сокета. Пожалуйста, обновите страницу.",
        Server_Connect_Server: "У нас возникли проблемы с подключением к вашему серверу, пожалуйста, подождите..."
      },
      Server_Backup: {
        Backup_Page_Title: "Резервные копии",
        Backup_Empty_1: "Похоже, у нас закончились резервные копии для показа, попробуйте вернуться на страницу назад.",
        Backup_Empty_2: "Похоже, что для этого сервера в настоящее время не хранятся резервные копии.",
        Backup_Forbidden: "Резервные копии не могут быть созданы для этого сервера, поскольку лимит резервного копирования установлен на 0.",
        Backup_Information: "для этого сервера были созданы резервные копии.",
        Backup_Create_Title_1: "Создание резервной копии сервера",
        Backup_Create_Title_2: "Имя резервной копии",
        Backup_Create_Title_3: "Игнорируемые файлы и каталоги",
        Backup_Create_Title_4: "Заблокировано",
        Backup_Create_Desc_1: "Если указано, имя, которое должно использоваться для ссылки на эту резервную копию.",
        Backup_Create_Desc_2: "Введите файлы или папки, которые следует игнорировать при создании этой резервной копии. Оставьте пустым, чтобы использовать содержимое файла .pteroignore в корне каталога сервера, если он есть. Поддерживается поиск файлов и папок в подстановочных знаках, а также отмена правила с помощью префикса пути с восклицательным знаком.",
        Backup_Create_Desc_3: "Предотвращает удаление этой резервной копии до ее явного разблокирования.",
        Backup_Create_Start_Button: "Начать резервное копирование",
        Backup_Create_Button: "Создание резервной копии",
        Backup_Created_Title: "Разблокировать эту резервную копию?",
        Backup_Created_Desc_1: "Вы уверены, что хотите разблокировать эту резервную копию? Она больше не будет защищена от автоматического или случайного удаления.",
        Backup_Created_Button: "Да, разблокировать",
        Backup_Restore_Title: "Восстановить эту резервную копию?",
        Backup_Restore_Desc_1: "Для восстановления резервной копии сервер будет остановлен. После запуска резервного копирования вы не сможете контролировать состояние питания сервера, получить доступ к файловому менеджеру или создать дополнительные резервные копии до его завершения.",
        Backup_Restore_Desc_2: "Вы уверены, что хотите продолжать?",
        Backup_Restore_Desc_3: "Перед восстановлением этой резервной копии удалите все файлы и папки.",
        Backup_Restore_Button: "Восстановление резервной копии",
        Backup_Delete_Title: "Удалить эту резервную копию?",
        Backup_Delete_Desc_1: "Вы уверены, что хотите удалить эту резервную копию? Это постоянная операция, и после удаления резервная копия не может быть восстановлена.",
        Backup_Delete_Button: "Да, удалить резервную копию",
        Backup_SubMenu_Download: "Скачать",
        Backup_SubMenu_Restore: "Восстановить",
        Backup_SubMenu_Unlock: "Разблокировать",
        Backup_SubMenu_Lock: "Замок",
        Backup_SubMenu_Delete: "Удалить"
      },
      Server_Databases: {
        Database_Page_Title: "Базы данных",
        Database_Show_Empty: "Похоже, что у вас нет баз данных.",
        Database_Show_Forbidden: "Базы данных не могут быть созданы для этого сервера.",
        Database_Limit_Desc: "баз данных были выделены этому серверу.",
        Database_Create_Title_1: "Создайте новую базу данных",
        Database_Create_Title_2: "Имя базы данных",
        Database_Create_Title_3: "Соединения из",
        Database_Create_Desc_1: "Описательное имя для экземпляра вашей базы данных.",
        Database_Create_Desc_2: "Откуда должны быть разрешены соединения. Используйте % для подстановочных знаков.",
        Database_Create_Button_1: "Создать базу данных",
        Database_Create_Button_2: "Новая база данных",
        Database_Create_Error_1: "При обработке этого запроса возникла непредвиденная ошибка, пожалуйста, попробуйте еще раз.",
        Database_Create_Error_2: "Необходимо указать имя базы данных.",
        Database_Create_Error_3: "Имя базы данных должно состоять не менее чем из 3 символов.",
        Database_Create_Error_4: "Имя базы данных не должно превышать 48 символов.",
        Database_Create_Error_5: "Имя базы данных должно содержать только буквенно-цифровые символы, подчеркивания, тире и/или точки.",
        Database_Create_Error_6: "Необходимо указать значение соединения.",
        Database_Create_Error_7: "Необходимо указать действительный адрес подключения.",
        Database_Delete_Title_1: "Подтвердите удаление базы данных",
        Database_Delete_Title_2: "Подтверждение имени базы данных",
        Database_Delete_Title_3: "Детали подключения к базе данных",
        Database_Delete_Title_4: "Конечная точка",
        Database_Delete_Title_5: "Соединения из",
        Database_Delete_Title_6: "Имя пользователя",
        Database_Delete_Title_7: "Пароль",
        Database_Delete_Title_8: "Строка подключения JDBC",
        Database_Rotate_Button: "Повернуть пароль",
        Database_Delete_Desc_1: `Удаление базы данных - это постоянное действие, его нельзя отменить. В результате база данных "{{database}}" будет удалена навсегда, а все связанные с ней данные будут удалены.`,
        Database_Create_Desc_2: "Введите имя базы данных для подтверждения удаления.",
        Database_Delete_Button: "Удалить базу данных",
        Database_Delete_Error_1: "Необходимо указать имя базы данных.",
        Database_Delete_Error_2: "Не найден хост базы данных, отвечающий требованиям для этого сервера."
      },
      Server_Files: {
        Files_Page_Title: "Файловый менеджер",
        Files_Create_Button: "Новый файл",
        Files_Directory_Empty: "Этот каталог кажется пустым.",
        Files_Show_Files_Max: "Этот каталог слишком велик для отображения в браузере, поэтому вывод ограничивается первыми 250 файлами.",
        Files_Chmod_Title: "Режим файла",
        Files_Chmod_Button: "Обновление",
        Files_Delete_File_Or_Directory_Title: "Удалить это",
        Files_Delete_File_Or_Directory_Button: "Да, удалить",
        Files_Delete_File_Or_Directory_Desc: "Удаление файлов является постоянной операцией, вы не можете отменить это действие.",
        Files_Delete_File: "Файл",
        Files_Delete_Directory: "Каталог",
        Files_Delete_Title: "Удалить эти файлы?",
        Files_Delete_Desc_1: "Вы уверены, что хотите удалить {{selected}} файл(ы)?",
        Files_Delete_Desc_2: "Удаление файла(ов), перечисленных ниже, является постоянной операцией, и вы не можете отменить это действие.",
        Files_Delete_Desc_3: "другой (другие)",
        Files_Delete_Button: "Да, Удаление файлов",
        Files_SubMenu_Rename: "Переименовать",
        Files_SubMenu_Move: "Переместить",
        Files_SubMenu_Permissions: "Разрешения",
        Files_SubMenu_Copy: "Копировать",
        Files_SubMenu_Archive: "Архив",
        Files_SubMenu_Unarchive: "Распакуйте",
        Files_SubMenu_Download: "Скачать",
        Files_SubMenu_Delete: "Удалить",
        Files_Edit_Ptero_Ignore_1: "Вы редактируете",
        Files_Edit_Ptero_Ignore_2: "файл. Любые файлы или каталоги, перечисленные здесь, будут исключены из резервного копирования. Подстановочные знаки поддерживаются с помощью звездочки",
        Files_Edit_Ptero_Ignore_3: "Вы можете отменить предыдущее правило, добавив восклицательный знак",
        Files_Edit_Save_Button: "Сохранить содержимое",
        Files_Create_Title: "Имя файла",
        Files_Create_Desc: "Введите имя, под которым должен быть сохранен этот файл.",
        Files_Create_Error: "FileName является обязательным полем",
        Files_Create_Button: "Создать файл",
        Files_Message_Archiving: "Архивирование файлов...",
        Files_Message_Deleting: "Удаление файлов...",
        Files_Create_Directory_Title: "Название каталога",
        Files_Create_Directory_Desc_1: "Должно быть указано действительное имя каталога.",
        Files_Create_Directory_Desc_2: "Этот каталог будет создан как",
        Files_Create_Directory_Button: "Создать каталог",
        Files_Move_Desc_1: "Введите новое имя и каталог этого файла или папки, относительно текущего каталога.",
        Files_Move_Desc_2: "Новое место:",
        Files_Drag_Desc: "Перетаскивайте файлы для загрузки.",
        Files_Drag_Button: "Загрузить",
        Files_Error_1: "Необходимо указать имя файла.",
        Files_Error_2: "На удаленном хосте произошла ошибка: Cannot move or rename file, destination already exists..."
      },
      Server_Users: {
        User_Page_Title: "Пользователи",
        User_Sub_Users_Empty: "Похоже, что у вас нет ни одного подпользователя.",
        User_Create_Title_1: "Создание нового подпользователя",
        User_Create_Title_2: "Электронная почта пользователя",
        User_Create_Sub_User_Desc_1: "Введите адрес электронной почты пользователя, которого вы хотите пригласить в качестве субпользователя для этого сервера.",
        User_Create_Sub_User_Desc_2: "Адреса электронной почты не должны превышать 191 символ.",
        User_Create_Sub_User_Desc_3: "Необходимо указать действительный адрес электронной почты.",
        User_Modify_Or_View_Email_Title: "разрешения на {{subuser}}",
        User_Modify_Title: "Изменить",
        User_View_Title: "Посмотреть",
        User_Modify_Button: "Сохранить",
        User_Create_Button_1: "Пригласить пользователя",
        User_Create_Button_2: "Новый пользователь",
        User_Create_Sub_User_Desc: "При создании или изменении других пользователей могут быть выбраны только те разрешения, которые назначены вашей учетной записи.",
        User_Delete_Title: "Удалить этого субпользователя?",
        User_Delete_Desc_1: "Вы уверены, что хотите удалить этого субпользователя? У него будет немедленно отозван весь доступ к этому серверу.",
        User_Delete_Button: "Да, удалить подпользователя",
        User_Show_2FA: "2FA Включено",
        User_Show_Permissions: "Разрешения",
        User_Create_Sub_Title_1: "Контроль",
        User_Create_Sub_Title_2: "Пользователь",
        User_Create_Sub_Title_3: "Файл",
        User_Create_Sub_Title_4: "Резервное копирование",
        User_Create_Sub_Title_5: "Распределение",
        User_Create_Sub_Title_6: "Стартап",
        User_Create_Sub_Title_7: "База данных",
        User_Create_Sub_Title_8: "Расписание",
        User_Create_Sub_Title_9: "Настройки",
        User_Create_Desc_1: "Разрешения, контролирующие способность пользователя управлять состоянием питания сервера или отправлять команды.",
        User_Create_Desc_2: "Разрешения, позволяющие пользователю управлять другими пользователями на сервере. Они никогда не смогут редактировать свою собственную учетную запись или назначать разрешения, которых у них самих нет.",
        User_Create_Desc_3: "Разрешения, контролирующие способность пользователя изменять файловую систему данного сервера.",
        User_Create_Desc_4: "Разрешения, контролирующие способность пользователя создавать и управлять резервными копиями сервера.",
        User_Create_Desc_5: "Разрешения, контролирующие способность пользователя изменять распределение портов для этого сервера.",
        User_Create_Desc_6: "Разрешения, контролирующие возможность пользователя просматривать параметры запуска этого сервера.",
        User_Create_Desc_7: "Разрешения, контролирующие доступ пользователя к управлению базой данных для данного сервера.",
        User_Create_Desc_8: "Разрешения, контролирующие доступ пользователя к управлению расписанием для этого сервера.",
        User_Create_Desc_9: "Разрешения, контролирующие доступ пользователя к настройкам данного сервера.",
        User_Create_Option_Desc_1: "Консоль",
        User_Create_Option_Desc_2: "Начало",
        User_Create_Option_Desc_3: "Остановить",
        User_Create_Option_Desc_4: "Перезапустить",
        User_Create_Option_Desc_5: "Создать",
        User_Create_Option_Desc_6: "Читать",
        User_Create_Option_Desc_7: "Обновление",
        User_Create_Option_Desc_8: "Удалить",
        User_Create_Option_Desc_9: "Read-content",
        User_Create_Option_Desc_10: "Архив",
        User_Create_Option_Desc_11: "SFTP",
        User_Create_Option_Desc_12: "Скачать",
        User_Create_Option_Desc_13: "Восстановить",
        User_Create_Option_Desc_14: "Docker-образ",
        User_Create_Option_Desc_15: "Просмотр_пароля",
        User_Create_Option_Desc_16: "Переименовать",
        User_Create_Option_Desc_17: "Переустановите",
        User_Create_Option_Description_1: "Позволяет пользователю отправлять команды экземпляру сервера через консоль.",
        User_Create_Option_Description_2: "Позволяет пользователю запустить сервер, если он остановлен.",
        User_Create_Option_Description_3: "Позволяет пользователю остановить сервер, если он запущен.",
        User_Create_Option_Description_4: "Позволяет пользователю выполнить перезапуск сервера. Это позволяет запустить сервер, если он находится в автономном режиме, но не переводить его в полностью остановленное состояние.",
        User_Create_Option_Description_5: "Позволяет пользователю создавать новых подпользователей для сервера.",
        User_Create_Option_Description_6: "Позволяет пользователю просматривать субпользователей и их разрешения для сервера.",
        User_Create_Option_Description_7: "Позволяет пользователю изменять других субпользователей.",
        User_Create_Option_Description_8: "Позволяет пользователю удалить подпользователя с сервера.",
        User_Create_Option_Description_9: "Позволяет пользователю создавать дополнительные файлы и папки с помощью панели или прямой загрузки.",
        User_Create_Option_Description_10: "Позволяет пользователю просматривать содержимое каталога, но не просматривать содержимое или загружать файлы.",
        User_Create_Option_Description_11: "Позволяет пользователю просмотреть содержимое заданного файла. Это также позволяет пользователю скачивать файлы.",
        User_Create_Option_Description_12: "Позволяет пользователю обновить содержимое существующего файла или каталога.",
        User_Create_Option_Description_13: "Позволяет пользователю удалять файлы или каталоги.",
        User_Create_Option_Description_14: "Позволяет пользователю архивировать содержимое каталога, а также распаковывать существующие в системе архивы.",
        User_Create_Option_Description_15: "Позволяет пользователю подключаться к SFTP и управлять файлами сервера, используя другие назначенные разрешения на файлы.",
        User_Create_Option_Description_16: "Позволяет пользователю создавать новые резервные копии для этого сервера.",
        User_Create_Option_Description_17: "Позволяет пользователю просмотреть все резервные копии, существующие для данного сервера.",
        User_Create_Option_Description_18: "Позволяет пользователю удалять резервные копии из системы.",
        User_Create_Option_Description_19: "Позволяет пользователю загрузить резервную копию сервера. Опасно: это позволяет пользователю получить доступ ко всем файлам сервера в резервной копии.",
        User_Create_Option_Description_20: "Позволяет пользователю восстановить резервную копию сервера. Опасность: при этом пользователь может удалить все файлы сервера.",
        User_Create_Option_Description_21: "Позволяет пользователю просмотреть все распределения, назначенные на данный сервер. Пользователи с любым уровнем доступа к этому серверу всегда могут просматривать основное распределение.",
        User_Create_Option_Description_22: "Позволяет пользователю назначать дополнительные распределения на сервер.",
        User_Create_Option_Description_23: "Позволяет пользователю изменить распределение основного сервера и прикрепить примечания к каждому распределению.",
        User_Create_Option_Description_24: "Позволяет пользователю удалить распределение с сервера.",
        User_Create_Option_Description_25: "Позволяет пользователю просмотреть переменные запуска для сервера.",
        User_Create_Option_Description_26: "Позволяет пользователю изменять переменные запуска сервера.",
        User_Create_Option_Description_27: "Позволяет пользователю изменять образ Docker, используемый при запуске сервера.",
        User_Create_Option_Description_28: "Позволяет пользователю создать новую базу данных для этого сервера.",
        User_Create_Option_Description_29: "Позволяет пользователю просматривать базу данных, связанную с этим сервером.",
        User_Create_Option_Description_30: "Позволяет пользователю изменять пароль на экземпляре базы данных. Если у пользователя нет разрешения view_password, он не увидит обновленный пароль.",
        User_Create_Option_Description_31: "Позволяет пользователю удалить экземпляр базы данных с этого сервера.",
        User_Create_Option_Description_32: "Позволяет пользователю просмотреть пароль, связанный с экземпляром базы данных для данного сервера.",
        User_Create_Option_Description_33: "Позволяет пользователю создавать новые расписания для этого сервера.",
        User_Create_Option_Description_34: "Позволяет пользователю просматривать расписания и связанные с ними задачи для данного сервера.",
        User_Create_Option_Description_35: "Позволяет пользователю обновлять расписания и планировать задачи для этого сервера.",
        User_Create_Option_Description_36: "Позволяет пользователю удалять расписания для этого сервера.",
        User_Create_Option_Description_37: "Позволяет пользователю переименовать этот сервер.",
        User_Create_Option_Description_38: "Позволяет пользователю инициировать переустановку этого сервера."
      },
      Server_Network: {
        Network_Page_Title: "Сеть",
        Network_Alocations_Desc_1: "В настоящее время вы используете {{data}} из {{limit}} разрешенных распределений для этого сервера.",
        Network_Create_Alocation_Button: "Создать распределение",
        Network_Hostname: "Имя хоста",
        Network_IP_Address: "IP-адрес",
        Network_Port: "Порт",
        Network_Notes: "Примечания",
        Network_Primary: "Основной",
        Network_Primary_Button: "Сделать первичным",
        Network_Delete_Title: "Удалить это распределение?",
        Network_Delete_Button: "Удалить",
        Network_Delete_Desc_1: "Это распределение будет немедленно удалено с вашего сервера. Вы уверены, что хотите продолжить?",
        Network_Error_1: "Автораспределение серверов не включено для этого экземпляра.",
      },
      Server_Schedules: {
        Task_Page_Title: "Расписания",
        Task_Empty_Message: "Для этого сервера не настроено никаких расписаний.",
        Task_Create_Button: "Создать расписание",
        Task_Edit_Button: "Сохранить изменения",
        Task_Delete_Title: "Удалить расписание?",
        Task_Delete_Button_1: "Да, удалить расписание",
        Task_Delete_Desc: "Вы уверены, что хотите удалить это расписание? Все задания будут удалены, а все запущенные процессы будут завершены.",
        Task_Delete_Button_2: "Удалить",
        Task_Create_Title: "Создать новое расписание",
        Task_Edit_Title: "Редактирование расписания",
        Task_Create_Or_Edit_Title_1: "Название расписания",
        Task_Create_Or_Edit_Title_2: "Только когда сервер находится в режиме онлайн",
        Task_Create_Or_Edit_Title_3: "Расписание включено",
        Task_Create_Or_Edit_Desc_1: "Человекочитаемый идентификатор для этого расписания.",
        Task_Create_Or_Edit_Desc_2: "Система расписания поддерживает использование синтаксиса Cronjob при определении времени начала выполнения задач. Используйте поля выше, чтобы указать время начала выполнения этих задач.",
        Task_Create_Or_Edit_Desc_3: "Выполняйте это расписание только тогда, когда сервер находится в работающем состоянии.",
        Task_Create_Or_Edit_Desc_4: "Это расписание будет выполняться автоматически, если оно включено.",
        Task_Create_Or_Edit_Minute: "Минута",
        Task_Create_Or_Edit_Hour: "Час",
        Task_Create_Or_Edit_Day_Of_Month: "День месяца",
        Task_Create_Or_Edit_Month: "Месяц",
        Task_Create_Or_Edit_Day_Of_Week: "День недели",
        Task_New_Task_Button: "Новая задача",
        Task_Run_Task_Button: "Беги сейчас",
        Task_Cron_Row_Minute: "Минута",
        Task_Cron_Row_Hour: "Час",
        Task_Cron_Row_Day_Month: "День (месяц)",
        Task_Cron_Row_Month: "Месяц",
        Task_Cron_Row_Day_Week: "День (неделя)",
        Task_Task_Page_Title: "Задачи",
        Task_Task_Processing: "Обработка",
        Task_Task_Last_Run: "Последний запуск в:",
        Task_Task_Next_Run: "Следующий запуск в:",
        Task_Task_Never: "Никогда",
        Task_Task_NA: "n/a",
        Task_Task_Edit_Button: "Редактировать",
        Task_Task_Active: "Активный",
        Task_Task_Inactive: "Неактивный",
        Task_Task_Delete_Title: "Подтвердите удаление задания",
        Task_Task_Delete_Button: "Удалить задачу",
        Task_Task_Delete_Desc: "Вы уверены, что хотите удалить эту задачу? Это действие нельзя отменить.",
        Task_Task_Files_And_Folders_Message: "Игнорирование файлов и папок:",
        Task_Task_Continue_Message: "Продолжается при неудаче",
        Task_Task_Time_Message: "{{time}} позже",
        Task_Task_Edit_Title: "Редактирование задачи",
        Task_Task_Create_Title: "Создать задачу",
        Task_Task_Create_Or_Edit_Command: "Отправить команду",
        Task_Task_Create_Or_Edit_Power: "Отправить действие питания",
        Task_Task_Create_Or_Edit_Backup: "Создание резервной копии",
        Task_Task_Create_Or_Edit_Title_1: "Смещение по времени (в секундах)",
        Task_Task_Create_Or_Edit_Title_2: "Полезная нагрузка",
        Task_Task_Create_Or_Edit_Title_3: "Игнорируемые файлы",
        Task_Task_Create_Or_Edit_Title_4: "Продолжить о неудаче",
        Task_Task_Create_Or_Edit_Title_5: "Действие",
        Task_Task_Create_Or_Edit_Desc_1: "Количество времени, которое необходимо выждать после выполнения предыдущего задания перед запуском этого. Если это первая задача в расписании, это значение не будет применяться.",
        Task_Task_Create_Or_Edit_Desc_2: "Необязательно. Включите файлы и папки, которые будут исключены из резервного копирования. По умолчанию будет использоваться содержимое файла .pteroignore. Если вы достигли лимита резервного копирования, будет ротироваться самая старая резервная копия.",
        Task_Task_Create_Or_Edit_Desc_3: "Последующие задания будут выполняться в случае неудачи этого задания.",
        Task_Task_Create_Or_Edit_Option_1: "Запуск сервера",
        Task_Task_Create_Or_Edit_Option_2: "Перезапустите сервер",
        Task_Task_Create_Or_Edit_Option_3: "Остановите сервер",
        Task_Task_Create_Or_Edit_Option_4: "Завершить работу сервера",
        Task_Task_Create_Or_Edit_Error_1: "Необходимо предоставить полезную нагрузку задания.",
        Task_Task_Create_Or_Edit_Error_2: "Временное смещение должно быть действительным числом в диапазоне от 0 до 900.",
        Task_Task_Create_Or_Edit_Error_3: "Необходимо указать значение временного смещения.",
        Task_Task_Create_Or_Edit_Error_4: "Временное смещение должно быть не менее 0 секунд.",
        Task_Task_Create_Or_Edit_Error_5: "Временное смещение должно быть меньше 900 секунд.",
        Task_Task_Create_Or_Edit_Error_6: "Задание резервного копирования не может быть создано, если лимит резервного копирования сервера установлен на 0."
      },
      Server_Settings: {
        Settings_Page_Title: "Настройки",
        Settings_SFTP_Title_1: "SFTP Подробнее",
        Settings_SFTP_Title_2: "Адрес сервера",
        Settings_SFTP_Title_3: "Имя пользователя",
        Settings_SFTP_Desc_1: "Ваш пароль SFTP такой же, как и пароль, который вы используете для доступа к этой панели.",
        Settings_SFTP_Button: "Запуск SFTP",
        Settings_Debug_Title_1: "Отладочная информация",
        Settings_Debug_Title_2: "Узел",
        Settings_Debug_Title_3: "Идентификатор сервера",
        Settings_Reinstall_Title_1: "Переустановка сервера",
        Settings_Reinstall_Title_2: "Подтвердите переустановку сервера",
        Settings_Reinstall_Button: "Да, переустановите сервер",
        Settings_Reinstall_Desc_1: "Ваш сервер будет остановлен, и некоторые файлы могут быть удалены или изменены во время этого процесса, вы уверены, что хотите продолжить?",
        Settings_Reinstall_Desc_2: "Переустановка вашего сервера остановит его, а затем заново запустит сценарий установки, который первоначально его настроил.",
        Settings_Reinstall_Desc_3: "В ходе этого процесса некоторые файлы могут быть удалены или изменены, поэтому перед продолжением работы создайте резервную копию данных.",
        Settings_Reinstall_Success: "Ваш сервер начал процесс переустановки.",
        Settings_Reinstall_Error: "Не удалось установить соединение с машиной, на которой работает этот сервер. Пожалуйста, попробуйте еще раз.",
        Settings_Rename_Server_Title_1: "Изменить имя сервера",
        Settings_Rename_Server_Title_2: "Имя сервера",
        Settings_Rename_Server_Button: "Сохранить",
        Settings_Rename_Required: "Имя является обязательным полем"
      },
      Server_Startup: {
        Startup_Page_Title: "Настройки запуска",
        Startup_Command_Title_1: "Команда запуска",
        Startup_Docker_Title: "Образ Docker",
        Startup_Docker_Desc: "Это расширенная функция, позволяющая выбрать образ Docker для использования при запуске данного экземпляра сервера.",
        Startup_Docker_Error: "Образ Docker этого сервера был установлен администратором вручную и не может быть изменен через этот пользовательский интерфейс.",
        Startup_Variables_Title: "Переменные",
        Startup_Variables_Read: "Только чтение",
        Startup_Server_Error_Title: "Упс!",
      },
      Server_Features: {
        Features_Invalid_Java_Title_1: "Неверная версия Java, обновить образ Docker?",
        Features_Invalid_Java_Desc_1: "Этот сервер не может запуститься из-за несоответствия требуемой версии Java.",
        Features_Invalid_Java_Desc_2: `Нажав кнопку "Обновить образ Docker" ниже, вы подтверждаете, что образ Docker, который использует этот сервер, будет изменен на образ ниже, который имеет версию Java, которую вы запрашиваете.`,
        Features_Invalid_Java_Desc_3: "Пожалуйста, выберите версию Java из списка ниже.",
        Features_Invalid_Java_Button_1: "Обновить образ Docker",
        Features_Invalid_Java_Button_2: "Cancel",
        Features_Accept_Eula_Title: "Принять EULA Minecraft®",
        Features_Accept_Eula_Desc_1: `Нажимая кнопку "Я принимаю" ниже, вы подтверждаете свое согласие с`,
        Features_Accept_Eula_Desc_2: "Minecraft® EULA",
        Features_Accept_Eula_Button_1: "Я принимаю",
        Features_Accept_Eula_Button_2: "Отмена",
        Features_Invalid_GSL_Title: "Неверный токен GSL!",
        Features_Invalid_GSL_Desc_1: "Похоже, что ваш токен входа на игровой сервер (GSL-токен) недействителен или истек срок его действия.",
        Features_Invalid_GSL_Desc_2: "Вы можете либо создать новый и ввести его ниже, либо оставить поле пустым, чтобы полностью удалить его.",
        Features_Invalid_GSL_Desc_3: "Жетон GSL",
        Features_Invalid_GSL_Desc_4: "Посетите сайт https://steamcommunity.com/dev/managegameservers, чтобы сгенерировать токен.",
        Features_Invalid_GSL_Button: "Обновление GSL-токена",
        Features_Invalid_PID_Title_1: "Достигнут предел памяти или процесса...",
        Features_Invalid_PID_Title_2: "Возможно, достигнут лимит ресурсов...",
        Features_Invalid_PID_Desc_1: "Этот сервер достиг максимального предела процесса или памяти.",
        Features_Invalid_PID_Desc_2: "Увеличение",
        Features_Invalid_PID_Desc_3: "в конфигурации крыльев",
        Features_Invalid_PID_Desc_4: ", может помочь решить эту проблему.",
        Features_Invalid_PID_Desc_5: "Примечание: Чтобы изменения конфигурационного файла вступили в силу, Wings необходимо перезапустить.",
        Features_Invalid_PID_Desc_6: "Этот сервер пытается использовать больше ресурсов, чем выделено. Пожалуйста, свяжитесь с администратором и сообщите ему о приведенной ниже ошибке.",
        Features_Invalid_PID_Desc_7: "pthread_create failed, Возможно, закончилась память или достигнуты лимиты процессов/ресурсов",
        Features_Invalid_Disk_Title: "Закончилось свободное место на диске...",
        Features_Invalid_Disk_Desc_1: "На этом сервере закончилось доступное дисковое пространство, и он не может завершить процесс установки или обновления.",
        Features_Invalid_Disk_Desc_2: "Убедитесь, что на машине достаточно места на диске, набрав",
        Features_Invalid_Disk_Desc_3: "на машине, на которой расположен этот сервер. Удалите файлы или увеличьте доступное дисковое пространство, чтобы решить проблему.",
        Features_Invalid_Disk_Desc_4: "На этом сервере закончилось доступное дисковое пространство, и он не может завершить процесс установки или обновления. Пожалуйста, свяжитесь с администратором(ами) и сообщите им о проблемах с дисковым пространством.",
      },
      Server_States: {
        Server_Installing_Title: "Запуск программы установки",
        Server_Installing_Desc: "Ваш сервер скоро будет готов, пожалуйста, повторите попытку через несколько минут.",
        Server_Suspended_Title: "Сервер приостановлен",
        Server_Suspended_Desc: "Работа этого сервера приостановлена, и доступ к нему невозможен.",
        Server_Transferring_Title: "Передача",
        Server_Transferring_Desc: "Ваш сервер переносится на новый узел, пожалуйста, проверьте позже.",
        Server_Restoring_Title: "Восстановление из резервной копии",
        Server_Restoring_Desc: "Ваш сервер в настоящее время восстанавливается из резервной копии, пожалуйста, проверьте через несколько минут."
      },
      Page_Titles: {
        Title_Console: "Консоль",
        Title_File_Manager: "Файловый менеджер",
        Title_Databases: "Базы данных",
        Title_Schedules: "Расписания",
        Title_Users: "Пользователи",
        Title_Backups: "Резервные копии",
        Title_Network: "Сеть",
        Title_Startup: "Стартап",
        Title_Settings: "Настройки",
        Title_API_Credentials: "Учетные данные API"
      },
      Times_And_Dates: {
        Date_Format: "dd'-'MM'-'yyyy h:mma",
        Time_Minutes_1: "4 минуты назад",
        Time_Minutes_2: "3 минуты назад",
        Time_Minutes_3: "2 минуты назад",
        Time_Minutes_4: "1 минуты назад",
        Time_Minutes_5: "Менее минуты назад",
        Time_Minutes_6: "Менее минуты назад",
        Time_Minutes_7: "1 минуту назад",
        Time_Minutes_8: "2 минуты назад",
        Time_Minutes_9: "3 минуты назад",
        Time_Minutes_10: "4 минуты назад",
        Time_Minutes_11: "5 минуты назад",
        Time_Minutes_12: "6 минуты назад",
        Time_Minutes_13: "7 минуты назад",
        Time_Minutes_14: "8 минуты назад",
        Time_Minutes_15: "9 минуты назад",
        Time_Minutes_16: "10 минуты назад",
        Time_Minutes_17: "11 минуты назад",
        Time_Minutes_18: "12 минуты назад",
        Time_Minutes_19: "13 минуты назад",
        Time_Minutes_20: "14 минуты назад",
        Time_Minutes_21: "15 минуты назад",
        Time_Minutes_22: "16 минуты назад",
        Time_Minutes_23: "17 минуты назад",
        Time_Minutes_24: "18 минуты назад",
        Time_Minutes_25: "19 минуты назад",
        Time_Minutes_26: "20 минуты назад",
        Time_Minutes_27: "21 минуты назад",
        Time_Minutes_28: "22 минуты назад",
        Time_Minutes_29: "23 минуты назад",
        Time_Minutes_30: "24 минуты назад",
        Time_Minutes_31: "25 минуты назад",
        Time_Minutes_32: "26 минуты назад",
        Time_Minutes_33: "27 минуты назад",
        Time_Minutes_34: "28 минуты назад",
        Time_Minutes_35: "29 минуты назад",
        Time_Minutes_36: "30 минуты назад",
        Time_Minutes_37: "31 минуты назад",
        Time_Minutes_38: "32 минуты назад",
        Time_Minutes_39: "33 минуты назад",
        Time_Minutes_40: "34 минуты назад",
        Time_Minutes_41: "35 минуты назад",
        Time_Minutes_42: "36 минуты назад",
        Time_Minutes_43: "37 минуты назад",
        Time_Minutes_44: "38 минуты назад",
        Time_Minutes_45: "39 минуты назад",
        Time_Minutes_46: "40 минуты назад",
        Time_Minutes_47: "41 минуты назад",
        Time_Minutes_48: "42 минуты назад",
        Time_Minutes_49: "43 минуты назад",
        Time_Minutes_50: "44 минуты назад",
        Time_Minutes_51: "45 минуты назад",
        Time_Minutes_52: "46 минуты назад",
        Time_Minutes_53: "47 минуты назад",
        Time_Minutes_54: "48 минуты назад",
        Time_Minutes_55: "49 минуты назад",
        Time_Minutes_56: "50 минуты назад",
        Time_Minutes_57: "51 минуты назад",
        Time_Minutes_58: "52 минуты назад",
        Time_Minutes_59: "53 минуты назад",
        Time_Minutes_60: "54 минуты назад",
        Time_Minutes_61: "55 минуты назад",
        Time_Minutes_62: "56 минуты назад",
        Time_Minutes_63: "57 минуты назад",
        Time_Minutes_64: "58 минуты назад",
        Time_Minutes_65: "59 минуты назад",
        Time_Hours_1: "1 час назад",
        Time_Hours_2: "2 часа назад",
        Time_Hours_3: "3 часа назад",
        Time_Hours_4: "4 часа назад",
        Time_Hours_5: "5 часа назад",
        Time_Hours_6: "6 часа назад",
        Time_Hours_7: "7 часа назад",
        Time_Hours_8: "8 часа назад",
        Time_Hours_9: "9 часа назад",
        Time_Hours_10: "10 часа назад",
        Time_Hours_11: "11 часа назад",
        Time_Hours_12: "12 часа назад",
        Time_Hours_13: "13 часа назад",
        Time_Hours_14: "14 часа назад",
        Time_Hours_15: "15 часа назад",
        Time_Hours_16: "16 часа назад",
        Time_Hours_17: "17 часа назад",
        Time_Hours_18: "18 часа назад",
        Time_Hours_19: "19 часа назад",
        Time_Hours_20: "20 часа назад",
        Time_Hours_21: "21 часа назад",
        Time_Hours_22: "22 часа назад",
        Time_Hours_23: "23 часа назад",
        Time_Days_1: "1 день назад",
        Time_Days_2: "2 дня назад"
      },
      Errors: {
        Error_Key_Undefined: "Внутренняя ошибка: Ключ для этого сообщения не был установлен, свяжитесь с автором: Ferks#7575",
        Error_Server_Title: "Что-то пошло не так",
        Error_Server_Desc: "Запрашиваемый ресурс не найден.",
        Error_Connection: "Произошла ошибка во время связи с машиной, на которой установлен этот сервер. Эта ошибка была зарегистрирована, пожалуйста, попробуйте еще раз.",
        Error_Network: "Ошибка сети",
        Error_Permission_Title: "Доступ запрещен",
        Error_Permission_Desc: "У вас нет разрешения на доступ к этой странице.",
        Error_Variables_1: "Поле значения является обязательным.",
        Error_Variables_2: "Значение должно состоять из 1 цифры.",
        Error_Variables_3: "Это значение недействительно.",
        Error_Variables_4: "Значение должно быть не менее 1.",
        Error_Variables_5: "Это значение больше предельного.",
        Error_Variables_6: "Формат значения недействителен.",
        Error_Variables_7: "Значение может содержать только буквы, цифры и тире."
      },
    }
}