export default {
    translation: {
      Login: {
        Title: "Inicie sesión para continuar",
        Username_or_Email: "Nombre de usuario o correo electrónico",
        Password: "Contraseña",
        Login_Button: "Inicio de sesión",
        Forgot_Password: "¿Ha olvidado su contraseña?",
        Username_or_Email_Desc: "Se debe proporcionar un nombre de usuario o un correo electrónico.",
        Account_Password_Desc: "Por favor, introduzca la contraseña de su cuenta.",
        Account_Incorrect: "No se ha podido encontrar ninguna cuenta que coincida con esas credenciales.",
        Many_Attempts: "Ha habido demasiados intentos de inicio de sesión. Por favor, inténtelo de nuevo más tarde.",
        Recaptcha_Error: "Fallo al validar los datos de reCAPTCHA.",
        Request_Failed: "Solicitud fallida con código de estado 404",
        CSRF_Token: "CSRF token mismatch."
      },
      Reset_Password: {
        Password_Reset: "Solicitar el restablecimiento de la contraseña",
        Email: "El e-mail",
        New_Password_Required: "Se requiere una nueva contraseña.",
        Password_Characters_Min: "Su nueva contraseña debe tener al menos 8 caracteres.",
        Password_Not_Match: "Su nueva contraseña no coincide.",
        Account_Email: "Introduzca la dirección de correo electrónico de su cuenta para recibir instrucciones sobre cómo restablecer su contraseña.",
        Valid_Email: "Se debe proporcionar una dirección de correo electrónico válida para continuar.",
        Send_Email: "Enviar correo electrónico",
        Return_to_Login: "Volver al inicio de sesión",
        Reset_Password: "Restablecer contraseña",
        New_Password: "Nueva contraseña",
        New_Password_Desc: "Las contraseñas deben tener al menos 8 caracteres.",
        Confirm_New_Password: "Confirmar nueva contraseña",
        Send_Email_Link: "Hemos enviado por correo electrónico el enlace para restablecer la contraseña."
      },
      Two_Factor_Auth: {
        Device_Checkpoint: "Punto de control del dispositivo",
        Recovery_Code: "Código de recuperación",
        Authentication_Code: "Código de autentificación",
        Enter_Two_Factor_Desc_1: "Introduzca el token de dos factores generado por su dispositivo.",
        Enter_Two_Factor_Desc_2: "Introduzca uno de los códigos de recuperación generados al configurar la autenticación de 2 factores en esta cuenta para continuar.",
        Lost_Device: "He perdido mi dispositivo",
        Have_Device: "Tengo mi dispositivo",
        Continue: "Continuar"
      },
      Account_Overview: {
        Two_Factor_Activate_Desc_1: "Debe proporcionar un código de autenticación para continuar.",
        Two_Factor_Activate_Desc_2: "La autenticación de dos factores está actualmente activada en su cuenta.",
        Two_Factor_Activate_Desc_3: "El código del autentificador debe tener 6 dígitos.",
        Two_Factor_Active_Title: "Autenticación de dos factores activada",
        Two_Factor_Active_Desc_1: "Se ha activado la autenticación de dos factores en su cuenta. Si pierde el acceso a su dispositivo de autenticación, tendrá que utilizar uno de los códigos que se muestran a continuación para acceder a su cuenta.",
        Two_Factor_Active_Desc_2: "Estos códigos no volverán a aparecer. ",
        Two_Factor_Active_Desc_3: "Por favor, tome nota de ellas ahora almacenándolas en un repositorio seguro como un gestor de contraseñas.",
        Two_Factor_Active_Button: "Cerrar",
        Two_Factor_Disabled_Desc: "Actualmente no tienes activada la autenticación de dos factores en tu cuenta. Haz clic en el botón siguiente para empezar a configurarla.",
        Two_Factor_Disable_Desc_1: "Debe proporcionar su contraseña actual para poder continuar.",
        Two_Factor_Disable_Desc_2: "Para desactivar la autenticación de dos factores tendrá que proporcionar la contraseña de su cuenta.",
        Two_Factor_Disable_Title: "Contraseña actual",
        Two_Factor_Disable_Button: "Desactivar dos factores",
        Two_Factor_Setup_Desc_1: "Introduzca el código de su dispositivo autenticador después de escanear la imagen QR.",
        Two_Factor_Setup_Desc_2: "Alternativamente, introduzca el siguiente token en su aplicación de autenticación:",
        Two_Factor_Setup_Button: "Configurar",
        Two_Factor_Incorrect_Password: "La contraseña proporcionada no es válida.",
        Button_Disable: "Desactivar",
        Button_Enable: "Activar",
        Create_Api_Desc_Title: "Descripción",
        Create_Api_Desc: "Una descripción de esta clave API.",
        Create_Api_Ips_Title: "IPs permitidas",
        Create_Api_Ips_Desc: "Deje el espacio en blanco para permitir que cualquier dirección IP utilice esta clave de API, de lo contrario proporcione cada dirección IP en una nueva línea.",
        Create_Api_Button: "Crear",
        Update_Email_Desc_1: "Debe proporcionar la contraseña actual de su cuenta.",
        Update_Email_Required: "El correo electrónico es un campo obligatorio",
        Update_Email_Success_Title: "Éxito",
        Update_Email_Success: "Su correo electrónico principal ha sido actualizado.",
        Update_Email_Error_Title: "Error",
        Update_Email_Button: "Actualizar el correo electrónico",
        Update_Password_Title: "Nueva contraseña",
        Update_Password_Desc_1: "Debe proporcionar su contraseña actual.",
        Update_Password_Desc_2: "La confirmación de la contraseña no coincide con la contraseña introducida.",
        Update_Password_Desc_3: "Su nueva contraseña debe tener al menos 8 caracteres y ser única para este sitio web.",
        Update_Password_Required: "La contraseña es un campo obligatorio",
        Update_Password_Button: "Actualizar contraseña",
        Update_Password_Error: "La contraseña proporcionada no es válida para esta cuenta.",
        Update_Password_Min: "La contraseña debe tener al menos 8 caracteres",
        Confirm_Password: "Confirmar contraseña",
        Account_Page_Title: "Resumen de la cuenta",
        Account_Two_Factor_Required_Title: "Se requieren 2 factores",
        Account_Two_Factor_Required_Desc: "Su cuenta debe tener activada la autenticación de dos factores para poder continuar.",
        Account_Update_Email_Title: "Actualizar la dirección de correo electrónico",
        Account_Setup_Two_Factor_Title: "Configurar dos factores",
        Api_Page_Title: "API de la cuenta",
        Api_Create_Title: "Crear una clave API",
        Api_List_Title: "Claves API",
        Api_List_Loading: "Cargando...",
        Api_List_Empty: "No existen claves API para esta cuenta.",
        Api_List_Used_1: "Último uso: ",
        Api_List_Used_2: "Nunca",
        Api_Delete_Title: "Confirmar el borrado de la llave",
        Api_Delete_Button: "Sí, tecla de borrar",
        Api_Delete_Desc: "¿Está seguro de que desea eliminar esta clave API? Todas las solicitudes que la utilicen serán inmediatamente invalidadas y fallarán.",
        Api_Setup_Title: "Su clave API",
        Api_Setup_Desc: "La clave API que ha solicitado se muestra a continuación. Por favor, guárdela en un lugar seguro, no se volverá a mostrar.",
        Api_Min_Characters: "La descripción debe tener al menos 4 caracteres",
        Api_Setup_Button: "Cerrar",
        Api_Ip_Incorrect_1: "La dirección IP 1 debe ser una dirección IP válida.",
        Api_Ip_Incorrect_2: "La dirección IP 2 debe ser una dirección IP válida.",
        Api_Ip_Incorrect_3: "La dirección IP 3 debe ser una dirección IP válida."
      },
      Search: {
        Search_Title: "Término de búsqueda",
        Search_Desc_1: "Por favor, introduzca al menos tres caracteres para comenzar la búsqueda.",
        Search_Desc_2: "Introduzca un nombre de servidor, uuid o asignación para comenzar la búsqueda."
      },
      Dashboard: {
        Dash_Page_Title: "Panel",
        Dash_Show_Server_1: "Mostrar los servidores de otros",
        Dash_Show_Server_2: "Mostrar sus servidores",
        Dash_Show_Server_3: "No hay otros servidores para mostrar.",
        Dash_Show_Server_4: "No hay servidores asociados a su cuenta."
      },
      Server_Row: {
        Server_Unlimited: "Ilimitado",
        Server_Suspended: "Suspendido",
        Server_Connect_Error: "Error de conexión",
        Server_Transferring: "Transfiriendo",
        Server_Installing: "Instalando",
        Server_Restoring_Backup: "Restauración la copia de seguridad",
        Server_Unavailable: "No disponible",
        Server_Of: "de"
      },
      Elements: {
        Elements_Cancel_Button: "Cancelar",
        Elements_Copy_Text: "Copiado en el portapapeles.",
        Elements_Error: "La aplicación ha encontrado un error al renderizar esta vista. Intente actualizar la página."
      },
      Server: {
        Server_Page_Title: "Consola",
        Server_Transfer_Console: "La transferencia ha fallado.",
        Server_Archived_Console: "El servidor ha sido archivado con éxito, intentando la conexión con el nodo de destino..",
        Server_Send_Command: "Escribe un comando...",
        Server_State_Console: "Servidor marcado como ",
        Server_State_Starting: "empezando por",
        Server_State_Offline: "desconectado",
        Server_State_Stopping: "parada",
        Server_State_Running: "corriendo",
        Server_State_Connect: "Conectando...",
        Server_State_Install: "Este servidor está ejecutando su proceso de instalación y la mayoría de las acciones no están disponibles.",
        Server_State_Transfer: "Este servidor está siendo transferido a otro nodo y todas las acciones no están disponibles.",
        Server_Button_Start: "Inicie",
        Server_Button_Restart: "Reiniciar",
        Server_Button_Kill: "Matar",
        Server_Button_Stop: "Detener",
        Server_Memory_Graph_Title: "Uso de la memoria",
        Server_Cpu_Graph_Title: "Uso de la CPU",
        Server_Graph_Desc: "El servidor está desconectado.",
        Server_Websocket_Error: "Se ha producido un error al validar las credenciales proporcionadas para el websocket. Por favor, actualice la página.",
        Server_Connect_Server: "Estamos teniendo problemas para conectarnos a su servidor, por favor espere..."
      },
      Server_Backup: {
        Backup_Page_Title: "Copias de seguridad",
        Backup_Empty_1: "Parece que nos hemos quedado sin copias de seguridad que mostrarte, prueba a retroceder una página.",
        Backup_Empty_2: "Parece que no hay copias de seguridad almacenadas actualmente para este servidor.",
        Backup_Forbidden: "No se pueden crear copias de seguridad para este servidor porque el límite de copias de seguridad está fijado en 0.",
        Backup_Information: "se han creado copias de seguridad para este servidor.",
        Backup_Create_Title_1: "Crear una copia de seguridad del servidor",
        Backup_Create_Title_2: "Nombre de la copia de seguridad",
        Backup_Create_Title_3: "Archivos y directorios ignorados",
        Backup_Create_Title_4: "Bloqueado",
        Backup_Create_Desc_1: "Si se proporciona, el nombre que debe usarse para hacer referencia a esta copia de seguridad.",
        Backup_Create_Desc_2: "Introduzca los archivos o carpetas que se van a ignorar al generar esta copia de seguridad. Déjelo en blanco para utilizar el contenido del archivo .pteroignore en la raíz del directorio del servidor, si está presente. Se admite la coincidencia de archivos y carpetas con comodines, además de negar una regla anteponiendo un signo de exclamación a la ruta.",
        Backup_Create_Desc_3: "Impide que esta copia de seguridad se borre hasta que se desbloquee explícitamente.",
        Backup_Create_Start_Button: "Iniciar copia de seguridad",
        Backup_Create_Button: "Crear copia de seguridad",
        Backup_Created_Title: "¿Desbloquear esta copia de seguridad?",
        Backup_Created_Desc_1: "¿Estás seguro de que quieres desbloquear esta copia de seguridad? Ya no estará protegida contra los borrados automáticos o accidentales.",
        Backup_Created_Button: "Sí, desbloquear",
        Backup_Restore_Title: "¿Restaurar esta copia de seguridad?",
        Backup_Restore_Desc_1: "Este servidor se detendrá para restaurar la copia de seguridad. Una vez iniciada la copia de seguridad, no podrá controlar el estado de energía del servidor, acceder al gestor de archivos o crear copias de seguridad adicionales hasta que haya finalizado.",
        Backup_Restore_Desc_2: "¿Estás seguro de que quieres continuar?",
        Backup_Restore_Desc_3: "Elimine todos los archivos y carpetas antes de restaurar esta copia de seguridad.",
        Backup_Restore_Button: "Restaurar copia de seguridad",
        Backup_Delete_Title: "¿Borrar esta copia de seguridad?",
        Backup_Delete_Desc_1: "¿Está seguro de que desea eliminar esta copia de seguridad? Esta es una operación permanente y la copia de seguridad no se puede recuperar una vez eliminada.",
        Backup_Delete_Button: "Sí, borrar copia de seguridad",
        Backup_SubMenu_Download: "Descargar",
        Backup_SubMenu_Restore: "Restaurar",
        Backup_SubMenu_Unlock: "Desbloquear",
        Backup_SubMenu_Lock: "Bloqueo",
        Backup_SubMenu_Delete: "Borrar"
      },
      Server_Databases: {
        Database_Page_Title: "Bases de datos",
        Database_Show_Empty: "Parece que no tiene bases de datos.",
        Database_Show_Forbidden: "No se pueden crear bases de datos para este servidor.",
        Database_Limit_Desc: "bases de datos han sido asignadas a este servidor.",
        Database_Create_Title_1: "Crear una nueva base de datos",
        Database_Create_Title_2: "Nombre de la base de datos",
        Database_Create_Title_3: "Conexiones desde",
        Database_Create_Desc_1: "Un nombre descriptivo para su instancia de base de datos.",
        Database_Create_Desc_2: "Desde dónde se deben permitir las conexiones. Utilice % para los comodines.",
        Database_Create_Button_1: "Crear base de datos",
        Database_Create_Button_2: "Nueva base de datos",
        Database_Create_Error_1: "Se ha producido un error inesperado al procesar esta solicitud, por favor, inténtelo de nuevo.",
        Database_Create_Error_2: "Se debe proporcionar un nombre de base de datos.",
        Database_Create_Error_3: "El nombre de la base de datos debe tener al menos 3 caracteres.",
        Database_Create_Error_4: "El nombre de la base de datos no debe superar los 48 caracteres.",
        Database_Create_Error_5: "El nombre de la base de datos sólo debe contener caracteres alfanuméricos, guiones bajos, guiones y/o puntos.",
        Database_Create_Error_6: "Se debe proporcionar un valor de conexión.",
        Database_Create_Error_7: "Debe proporcionarse una dirección de conexión válida.",
        Database_Delete_Title_1: "Confirmar la eliminación de la base de datos",
        Database_Delete_Title_2: "Confirmar el nombre de la base de datos",
        Database_Delete_Title_3: "Detalles de la conexión a la base de datos",
        Database_Delete_Title_4: "Punto final",
        Database_Delete_Title_5: "Conexiones de",
        Database_Delete_Title_6: "Nombre de usuario",
        Database_Delete_Title_7: "Contraseña",
        Database_Delete_Title_8: "Cadena de conexión JDBC",
        Database_Rotate_Button: "Rotar la contraseña",
        Database_Delete_Desc_1: `Eliminar una base de datos es una acción permanente, no se puede deshacer. Esto borrará permanentemente la base de datos "{{database}}" y eliminará todos los datos asociados.`,
        Database_Create_Desc_2: "Introduzca el nombre de la base de datos para confirmar la eliminación.",
        Database_Delete_Button: "Borrar la base de datos",
        Database_Delete_Error_1: "Debe indicarse el nombre de la base de datos.",
        Database_Delete_Error_2: "No se ha encontrado ningún host de base de datos que cumpla los requisitos de este servidor."
      },
      Server_Files: {
        Files_Page_Title: "Gestor de archivos",
        Files_Create_Button: "Nuevo archivo",
        Files_Directory_Empty: "Este directorio parece estar vacío.",
        Files_Show_Files_Max: "Este directorio es demasiado grande para mostrarlo en el navegador, limitando la salida a los primeros 250 archivos.",
        Files_Chmod_Title: "Modo de archivo",
        Files_Chmod_Button: "Actualización",
        Files_Delete_File_Or_Directory_Title: "Borrar esto",
        Files_Delete_File_Or_Directory_Button: "Sí, borrar",
        Files_Delete_File_Or_Directory_Desc: "La eliminación de archivos es una operación permanente, no se puede deshacer esta acción.",
        Files_Delete_File: "Archivo",
        Files_Delete_Directory: "Directorio",
        Files_Delete_Title: "¿Borrar estos archivos?",
        Files_Delete_Desc_1: "¿Está seguro de que quiere eliminar los archivos {{selected}}?",
        Files_Delete_Desc_2: "La eliminación de los archivos enumerados a continuación es una operación permanente, no se puede deshacer esta acción.",
        Files_Delete_Desc_3: "otro(s)",
        Files_Delete_Button: "Sí, borrar archivos",
        Files_SubMenu_Rename: "Rebautizar",
        Files_SubMenu_Move: "Moverse",
        Files_SubMenu_Permissions: "Permisos",
        Files_SubMenu_Copy: "Copiar",
        Files_SubMenu_Archive: "Archivo",
        Files_SubMenu_Unarchive: "Desarchivar",
        Files_SubMenu_Download: "Descargar",
        Files_SubMenu_Delete: "Borrar",
        Files_Edit_Ptero_Ignore_1: "Estás editando un",
        Files_Edit_Ptero_Ignore_2: "archivo. Cualquier archivo o directorio que aparezca aquí será excluido de las copias de seguridad. Los comodines se admiten utilizando un asterisco",
        Files_Edit_Ptero_Ignore_3: "Puede negar una regla anterior añadiendo un signo de exclamación",
        Files_Edit_Save_Button: "Guardar contenido",
        Files_Create_Title: "Nombre del archivo",
        Files_Create_Desc: "Introduzca el nombre con el que debe guardarse este archivo.",
        Files_Create_Error: "FileName es un campo obligatorio",
        Files_Create_Button: "Crear archivo",
        Files_Date_Format: "dd, MM, yyyy h:mma",
        Files_Message_Archiving: "Archivar archivos...",
        Files_Message_Deleting: "Borrar archivos...",
        Files_Create_Directory_Title: "Nombre del directorio",
        Files_Create_Directory_Desc_1: "Se debe proporcionar un nombre de directorio válido.",
        Files_Create_Directory_Desc_2: "Este directorio se creará como",
        Files_Create_Directory_Button: "Crear directorio",
        Files_Move_Desc_1: "Introduzca el nuevo nombre y el directorio de este archivo o carpeta, en relación con el directorio actual.",
        Files_Move_Desc_2: "Nueva ubicación:",
        Files_Drag_Desc: "Arrastre y suelte los archivos para cargarlos.",
        Files_Drag_Button: "Subir",
        Files_Error_1: "Se requiere un nombre para el archivo.",
        Files_Error_2: "Se ha producido un error en el host remoto: No se puede mover o renombrar el archivo, el destino ya existe.."
      },
      Server_Users: {
        User_Page_Title: "Usuarios",
        User_Sub_Users_Empty: "Parece que no tienes ningún subusuario.",
        User_Create_Title_1: "Crear un nuevo subusuario",
        User_Create_Title_2: "Email del usuario",
        User_Create_Sub_User_Desc_1: "Introduzca la dirección de correo electrónico del usuario que desea invitar como subusuario para este servidor.",
        User_Create_Sub_User_Desc_2: "Las direcciones de correo electrónico no deben superar los 191 caracteres.",
        User_Create_Sub_User_Desc_3: "Debe proporcionarse una dirección de correo electrónico válida.",
        User_Modify_Or_View_Email_Title: "permisos para {{subuser}}",
        User_Modify_Title: "Modificar",
        User_View_Title: "Vista",
        User_Modify_Button: "Ahorrar",
        User_Create_Button_1: "Invitar usuario",
        User_Create_Button_2: "Nuevo usuario",
        User_Create_Sub_User_Desc: "Al crear o modificar otros usuarios, sólo se pueden seleccionar los permisos que su cuenta tiene asignados actualmente.",
        User_Delete_Title: "¿Borrar este subusuario?",
        User_Delete_Desc_1: "¿Está seguro de que desea eliminar este subusuario? Se les revocará inmediatamente todo el acceso a este servidor.",
        User_Delete_Button: "Sí, eliminar el subusuario",
        User_Show_2FA: "2FA habilitado",
        User_Show_Permissions: "Permisos",
        User_Create_Sub_Title_1: "Controlar",
        User_Create_Sub_Title_2: "Usuario",
        User_Create_Sub_Title_3: "Archivo",
        User_Create_Sub_Title_4: "Copia de seguridad",
        User_Create_Sub_Title_5: "Asignación",
        User_Create_Sub_Title_6: "Inicio",
        User_Create_Sub_Title_7: "Base de datos",
        User_Create_Sub_Title_8: "Programar",
        User_Create_Sub_Title_9: "Ajustes",
        User_Create_Desc_1: "Permisos que controlan la capacidad de un usuario para controlar el estado de energía de un servidor, o enviar comandos.",
        User_Create_Desc_2: "Permisos que permiten a un usuario gestionar otros subusuarios en un servidor. Nunca podrán editar su propia cuenta, ni asignar permisos que no tengan ellos mismos.",
        User_Create_Desc_3: "Permisos que controlan la capacidad de un usuario para modificar el sistema de archivos de este servidor.",
        User_Create_Desc_4: "Permisos que controlan la capacidad de un usuario para generar y gestionar las copias de seguridad del servidor.",
        User_Create_Desc_5: "Permisos que controlan la capacidad de un usuario para modificar las asignaciones de puertos para este servidor.",
        User_Create_Desc_6: "Permisos que controlan la capacidad de un usuario para ver los parámetros de inicio de este servidor.",
        User_Create_Desc_7: "Permisos que controlan el acceso de un usuario a la gestión de la base de datos para este servidor.",
        User_Create_Desc_8: "Permisos que controlan el acceso de un usuario a la gestión de horarios para este servidor.",
        User_Create_Desc_9: "Permisos que controlan el acceso de un usuario a la configuración de este servidor.",
        User_Create_Option_Desc_1: "Consola",
        User_Create_Option_Desc_2: "Inicie",
        User_Create_Option_Desc_3: "Detener",
        User_Create_Option_Desc_4: "Reiniciar",
        User_Create_Option_Desc_5: "Crear",
        User_Create_Option_Desc_6: "Leer",
        User_Create_Option_Desc_7: "Actualización",
        User_Create_Option_Desc_8: "Borrar",
        User_Create_Option_Desc_9: "Leer contenido",
        User_Create_Option_Desc_10: "Archivo",
        User_Create_Option_Desc_11: "SFTP",
        User_Create_Option_Desc_12: "Descargar",
        User_Create_Option_Desc_13: "Restaurar",
        User_Create_Option_Desc_14: "Docker-image",
        User_Create_Option_Desc_15: "Ver_contraseña",
        User_Create_Option_Desc_16: "Rebautizar",
        User_Create_Option_Desc_17: "Reinstalar",
        User_Create_Option_Description_1: "Permite a un usuario enviar comandos a la instancia del servidor a través de la consola.",
        User_Create_Option_Description_2: "Permite a un usuario iniciar el servidor si está parado.",
        User_Create_Option_Description_3: "Permite al usuario detener un servidor si se está ejecutando.",
        User_Create_Option_Description_4: "Permite a un usuario realizar un reinicio del servidor. Esto les permite iniciar el servidor si está fuera de línea, pero no poner el servidor en un estado completamente detenido.",
        User_Create_Option_Description_5: "Permite a un usuario crear nuevos subusuarios para el servidor.",
        User_Create_Option_Description_6: "Permite al usuario ver los subusuarios y sus permisos para el servidor.",
        User_Create_Option_Description_7: "Permite a un usuario modificar otros subusuarios.",
        User_Create_Option_Description_8: "Permite a un usuario eliminar un subusuario del servidor.",
        User_Create_Option_Description_9: "Permite al usuario crear archivos y carpetas adicionales a través del Panel o de la carga directa.",
        User_Create_Option_Description_10: "Permite al usuario ver el contenido de un directorio, pero no ver el contenido ni descargar archivos.",
        User_Create_Option_Description_11: "Permite al usuario ver el contenido de un archivo determinado. Esto también permitirá al usuario descargar archivos.",
        User_Create_Option_Description_12: "Permite al usuario actualizar el contenido de un archivo o directorio existente.",
        User_Create_Option_Description_13: "Permite a un usuario eliminar archivos o directorios.",
        User_Create_Option_Description_14: "Permite al usuario archivar el contenido de un directorio, así como descomprimir los archivos existentes en el sistema.",
        User_Create_Option_Description_15: "Permite a un usuario conectarse a SFTP y gestionar los archivos del servidor utilizando los otros permisos de archivo asignados.",
        User_Create_Option_Description_16: "Permite a un usuario crear nuevas copias de seguridad para este servidor.",
        User_Create_Option_Description_17: "Permite al usuario ver todas las copias de seguridad que existen para este servidor.",
        User_Create_Option_Description_18: "Permite al usuario eliminar las copias de seguridad del sistema.",
        User_Create_Option_Description_19: "Permite al usuario descargar una copia de seguridad del servidor. Peligro: permite al usuario acceder a todos los archivos del servidor en la copia de seguridad.",
        User_Create_Option_Description_20: "Permite al usuario restaurar una copia de seguridad del servidor. Peligro: permite al usuario eliminar todos los archivos del servidor en el proceso.",
        User_Create_Option_Description_21: "Permite a un usuario ver todas las asignaciones actualmente asignadas a este servidor. Los usuarios con cualquier nivel de acceso a este servidor siempre pueden ver la asignación principal.",
        User_Create_Option_Description_22: "Permite a un usuario asignar asignaciones adicionales al servidor.",
        User_Create_Option_Description_23: "Permite al usuario cambiar la asignación del servidor primario y adjuntar notas a cada asignación.",
        User_Create_Option_Description_24: "Permite a un usuario eliminar una asignación del servidor.",
        User_Create_Option_Description_25: "Permite al usuario ver las variables de inicio de un servidor.",
        User_Create_Option_Description_26: "Permite al usuario modificar las variables de inicio del servidor.",
        User_Create_Option_Description_27: "Permite al usuario modificar la imagen Docker utilizada al ejecutar el servidor.",
        User_Create_Option_Description_28: "Permite al usuario crear una nueva base de datos para este servidor.",
        User_Create_Option_Description_29: "Permite a un usuario ver la base de datos asociada a este servidor.",
        User_Create_Option_Description_30: "Permite a un usuario rotar la contraseña en una instancia de base de datos. Si el usuario no tiene el permiso view_password no verá la contraseña actualizada.",
        User_Create_Option_Description_31: "Permite a un usuario eliminar una instancia de base de datos de este servidor.",
        User_Create_Option_Description_32: "Permite a un usuario ver la contraseña asociada a una instancia de base de datos para este servidor.",
        User_Create_Option_Description_33: "Permite al usuario crear nuevos horarios para este servidor.",
        User_Create_Option_Description_34: "Permite al usuario ver los horarios y las tareas asociadas a ellos para este servidor.",
        User_Create_Option_Description_35: "Permite a un usuario actualizar los horarios y programar las tareas para este servidor.",
        User_Create_Option_Description_36: "Permite al usuario eliminar los horarios de este servidor.",
        User_Create_Option_Description_37: "Permite al usuario cambiar el nombre de este servidor.",
        User_Create_Option_Description_38: "Permite a un usuario activar una reinstalación de este servidor."
      },
      Server_Network: {
        Network_Page_Title: "Red",
        Network_Alocations_Desc_1: "Actualmente está utilizando {{data}} de {{limit}} asignaciones permitidas para este servidor.",
        Network_Create_Alocation_Button: "Crear asignación",
        Network_Hostname: "Nombre de host",
        Network_IP_Address: "Dirección IP",
        Network_Port: "Puerto",
        Network_Notes: "Notas",
        Network_Primary: "Primaria",
        Network_Primary_Button: "Hacer primaria",
        Network_Delete_Title: "¿Quitar esta asignación?",
        Network_Delete_Button: "Borrar",
        Network_Delete_Desc_1: "Esta asignación se eliminará inmediatamente de su servidor. Está seguro de que quiere continuar?",
        Network_Error_1: "La asignación automática de servidores no está activada para esta instancia.",
      },
      Server_Schedules: {
        Task_Page_Title: "Horarios",
        Task_Empty_Message: "No hay horarios configurados para este servidor.",
        Task_Create_Button: "Crear horario",
        Task_Edit_Button: "Guardar los cambios",
        Task_Delete_Title: "¿Borrar el horario?",
        Task_Delete_Button_1: "Sí, eliminar el horario",
        Task_Delete_Desc: "¿Está seguro de que quiere eliminar esta programación? Se eliminarán todas las tareas y se terminarán los procesos en ejecución.",
        Task_Delete_Button_2: "Borrar",
        Task_Create_Title: "Crear un nuevo horario",
        Task_Edit_Title: "Editar el programa",
        Task_Create_Or_Edit_Title_1: "Nombre del programa",
        Task_Create_Or_Edit_Title_2: "Sólo cuando el servidor está en línea",
        Task_Create_Or_Edit_Title_3: "Programa habilitado",
        Task_Create_Or_Edit_Desc_1: "Un identificador legible para este horario.",
        Task_Create_Or_Edit_Desc_2: "El sistema de planificación admite el uso de la sintaxis Cronjob para definir cuándo deben comenzar a ejecutarse las tareas. Utilice los campos anteriores para especificar cuándo deben comenzar a ejecutarse estas tareas.",
        Task_Create_Or_Edit_Desc_3: "Ejecute esta programación sólo cuando el servidor esté en estado de funcionamiento.",
        Task_Create_Or_Edit_Desc_4: "Esta programación se ejecutará automáticamente si está activada.",
        Task_Create_Or_Edit_Minute: "Minuta",
        Task_Create_Or_Edit_Hour: "Hora",
        Task_Create_Or_Edit_Day_Of_Month: "Día del mes",
        Task_Create_Or_Edit_Month: "Mes",
        Task_Create_Or_Edit_Day_Of_Week: "Día de la semana",
        Task_New_Task_Button: "Nueva tarea",
        Task_Run_Task_Button: "Corre ahora",
        Task_Cron_Row_Minute: "Minuta",
        Task_Cron_Row_Hour: "Hora",
        Task_Cron_Row_Day_Month: "Día (mes)",
        Task_Cron_Row_Month: "Mes",
        Task_Cron_Row_Day_Week: "Día (semana)",
        Task_Task_Page_Title: "Tareas",
        Task_Task_Processing: "Procesamiento",
        Task_Task_Last_Run: "Última carrera en:",
        Task_Task_Next_Run: "Próxima carrera en:",
        Task_Task_Never: "Nunca",
        Task_Task_Date_Format: "MM do 'en' h:mma",
        Task_Task_NA: "n/a",
        Task_Task_Edit_Button: "Editar",
        Task_Task_Active: "Activo",
        Task_Task_Inactive: "Inactivo",
        Task_Task_Delete_Title: "Confirmar la eliminación de la tarea",
        Task_Task_Delete_Button: "Eliminar tarea",
        Task_Task_Delete_Desc: "¿Está seguro de que quiere eliminar esta tarea? Esta acción no se puede deshacer.",
        Task_Task_Files_And_Folders_Message: "Ignorar archivos y carpetas:",
        Task_Task_Continue_Message: "Continúa en el fracaso",
        Task_Task_Time_Message: "{{time}}s más tarde",
        Task_Task_Edit_Title: "Editar tarea",
        Task_Task_Create_Title: "Crear tarea",
        Task_Task_Create_Or_Edit_Command: "Enviar comando",
        Task_Task_Create_Or_Edit_Power: "Enviar acción de poder",
        Task_Task_Create_Or_Edit_Backup: "Crear copia de seguridad",
        Task_Task_Create_Or_Edit_Title_1: "Desplazamiento de tiempo (en segundos)",
        Task_Task_Create_Or_Edit_Title_2: "Carga útil",
        Task_Task_Create_Or_Edit_Title_3: "Archivos ignorados",
        Task_Task_Create_Or_Edit_Title_4: "Continuar con el fracaso",
        Task_Task_Create_Or_Edit_Title_5: "Acción",
        Task_Task_Create_Or_Edit_Desc_1: "La cantidad de tiempo que se debe esperar después de la ejecución de la tarea anterior antes de ejecutar esta. Si esta es la primera tarea de un programa, esto no se aplicará.",
        Task_Task_Create_Or_Edit_Desc_2: "Opcional. Incluya los archivos y carpetas que deben ser excluidos en esta copia de seguridad. Por defecto, se utilizará el contenido de su archivo .pteroignore. Si ha alcanzado el límite de copias de seguridad, se rotará la copia de seguridad más antigua.",
        Task_Task_Create_Or_Edit_Desc_3: "Las tareas futuras se ejecutarán cuando esta tarea falle.",
        Task_Task_Create_Or_Edit_Option_1: "Iniciar el servidor",
        Task_Task_Create_Or_Edit_Option_2: "Reiniciar el servidor",
        Task_Task_Create_Or_Edit_Option_3: "Detener el servidor",
        Task_Task_Create_Or_Edit_Option_4: "Terminar el servidor",
        Task_Task_Create_Or_Edit_Error_1: "Se debe proporcionar una carga útil de la tarea.",
        Task_Task_Create_Or_Edit_Error_2: "El desplazamiento de tiempo debe ser un número válido entre 0 y 900.",
        Task_Task_Create_Or_Edit_Error_3: "Se debe proporcionar un valor de desplazamiento de tiempo.",
        Task_Task_Create_Or_Edit_Error_4: "El desplazamiento de tiempo debe ser de al menos 0 segundos.",
        Task_Task_Create_Or_Edit_Error_5: "El desfase temporal debe ser inferior a 900 segundos.",
        Task_Task_Create_Or_Edit_Error_6: "No se puede crear una tarea de copia de seguridad cuando el límite de copias de seguridad del servidor está fijado en 0."
      },
      Server_Settings: {
        Settings_Page_Title: "Ajustes",
        Settings_SFTP_Title_1: "Detalles de SFTP",
        Settings_SFTP_Title_2: "Dirección del servidor",
        Settings_SFTP_Title_3: "Nombre de usuario",
        Settings_SFTP_Desc_1: "Su contraseña de SFTP es la misma que utiliza para acceder a este panel.",
        Settings_SFTP_Button: "Iniciar SFTP",
        Settings_Debug_Title_1: "Información de depuración",
        Settings_Debug_Title_2: "Nodo",
        Settings_Debug_Title_3: "ID del servidor",
        Settings_Reinstall_Title_1: "Reinstalar el servidor",
        Settings_Reinstall_Title_2: "Confirmar la reinstalación del servidor",
        Settings_Reinstall_Button: "Sí, reinstalar el servidor",
        Settings_Reinstall_Desc_1: "Su servidor se detendrá y algunos archivos pueden ser eliminados o modificados durante este proceso, ¿está seguro de que desea continuar?",
        Settings_Reinstall_Desc_2: "Al reinstalar el servidor, éste se detendrá y volverá a ejecutar el script de instalación que lo configuró inicialmente.",
        Settings_Reinstall_Desc_3: "Algunos archivos pueden ser borrados o modificados durante este proceso, por favor haga una copia de seguridad de sus datos antes de continuar.",
        Settings_Reinstall_Success: "Su servidor ha comenzado el proceso de reinstalación.",
        Settings_Reinstall_Error: "No se ha podido establecer una conexión con la máquina que ejecuta este servidor. Por favor, inténtelo de nuevo.",
        Settings_Rename_Server_Title_1: "Cambiar el nombre del servidor",
        Settings_Rename_Server_Title_2: "Nombre del servidor",
        Settings_Rename_Server_Button: "Guardar",
        Settings_Rename_Required: "El nombre es un campo obligatorio"
      },
      Server_Startup: {
        Startup_Page_Title: "Configuración de inicio",
        Startup_Command_Title_1: "Comando de inicio",
        Startup_Docker_Title: "Imagen Docker",
        Startup_Docker_Desc: "Esta es una característica avanzada que le permite seleccionar una imagen Docker para usar cuando se ejecuta esta instancia de servidor.",
        Startup_Docker_Error: "La imagen Docker de este servidor ha sido configurada manualmente por un administrador y no puede ser modificada a través de esta interfaz.",
        Startup_Variables_Title: "Variables",
        Startup_Variables_Read: "Sólo lectura",
        Startup_Server_Error_Title: "Oops!",
      },
      Server_Features: {
        Features_Invalid_Java_Title_1: "Versión de Java no válida, actualizar imagen Docker?",
        Features_Invalid_Java_Desc_1: "Este servidor no puede iniciarse debido a que la versión de Java requerida no se cumple.",
        Features_Invalid_Java_Desc_2: `Al pulsar "Actualizar imagen Docker" a continuación, está reconociendo que la imagen Docker que utiliza este servidor se cambiará por una imagen a continuación que tenga la versión de Java que está solicitando.`,
        Features_Invalid_Java_Desc_3: "Seleccione una versión de Java de la lista siguiente.",
        Features_Invalid_Java_Button_1: "Actualizar imagen Docker",
        Features_Invalid_Java_Button_2: "Cancelar",
        Features_Accept_Eula_Title: "Acepta el EULA de Minecraft®",
        Features_Accept_Eula_Desc_1: `Al pulsar "Acepto" a continuación, está indicando su acuerdo con la`,
        Features_Accept_Eula_Desc_2: "EULA de Minecraft®",
        Features_Accept_Eula_Button_1: "Acepto",
        Features_Accept_Eula_Button_2: "Cancelar",
      },
      Server_States: {
        Server_Installing_Title: "Ejecución del instalador",
        Server_Installing_Desc: "Su servidor debería estar listo pronto, por favor inténtelo de nuevo en unos minutos.",
        Server_Suspended_Title: "Servidor suspendido",
        Server_Suspended_Desc: "Este servidor está suspendido y no se puede acceder a él.",
        Server_Transferring_Title: "Transfiriendo",
        Server_Transferring_Desc: "Su servidor está siendo transferido a un nuevo nodo, por favor, vuelva más tarde.",
        Server_Restoring_Title: "Restauración a partir de una copia de seguridad",
        Server_Restoring_Desc: "Su servidor está siendo restaurado desde una copia de seguridad, por favor, vuelva a comprobarlo en unos minutos."
      },
      Page_Titles: {
        Title_Console: "Consola",
        Title_File_Manager: "Gestor de archivos",
        Title_Databases: "Bases de datos",
        Title_Schedules: "Horarios",
        Title_Users: "Usuarios",
        Title_Backups: "Copias de seguridad",
        Title_Network: "Red",
        Title_Startup: "Inicio",
        Title_Settings: "Ajustes",
        Title_API_Credentials: "Credenciales de la API"
      },
      Errors: {
        Error_Key_Undefined: "Error interno: La clave de este mensaje no se ha establecido, póngase en contacto con el autor: Ferks#7575",
        Error_Server_Title: "Algo salió mal",
        Error_Server_Desc: "No se ha encontrado el recurso solicitado.",
        Error_Permission_Title: "Acceso denegado",
        Error_Permission_Desc: "No tiene permiso para acceder a esta página.",
        Error_Variables_1: "El campo de valor es obligatorio.",
        Error_Variables_2: "El valor debe ser de 1 dígito.",
        Error_Variables_3: "Este valor no es válido.",
        Error_Variables_4: "El valor debe ser al menos 1.",
        Error_Variables_5: "Este valor es mayor que el límite.",
        Error_Variables_6: "El formato del valor no es válido.",
        Error_Variables_7: "El valor sólo puede contener letras, números y guiones."
      },
    }
}